-- DailyEng — seed nhóm "cong-viec". SINH TỰ ĐỘNG bởi scripts/generate-decks.mts, đừng sửa tay.
-- Chạy SAU schema-07-nhom-bo-tu.sql. Chạy lại nhiều lần được: bộ đã có thì cập nhật tên/mô tả,
-- từ đã có (deck_id, term) thì giữ nguyên để không mất tiến độ học của người dùng.

-- Email & giao tiếp công sở (100 từ)
insert into public.decks (slug, name, description, level, category, position)
values ('cong-viec-email', 'Email & giao tiếp công sở', 'Viết email, gọi điện, nhắn tin chuyên nghiệp', 'intermediate', 'cong-viec', 10)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, level = excluded.level,
  category = excluded.category, position = excluded.position;

insert into public.words (deck_id, term, phonetic, meaning_vi, example_en, example_vi, position)
select d.id, w.term, w.phonetic, w.meaning_vi, w.example_en, w.example_vi, w.position
from public.decks d
join (values
  ('Dear', '/dɪə/', 'Kính gửi, Thân gửi (mở đầu thư)', 'Dear Ms. Tran, thank you for your email.', 'Kính gửi bà Trần, cảm ơn email của bà.', 1),
  ('Hi there', '/haɪ ðeə/', 'Chào bạn (thân mật)', 'Hi there, just a quick question.', 'Chào bạn, tôi có câu hỏi nhanh.', 2),
  ('I hope this email finds you well', '/aɪ həʊp ðɪs ˈiːmeɪl faɪndz juː wel/', 'Hy vọng bạn vẫn khoẻ (câu mở đầu)', 'I hope this email finds you well.', 'Hy vọng anh/chị vẫn khoẻ.', 3),
  ('I am writing to', '/aɪ æm ˈraɪtɪŋ tuː/', 'Tôi viết thư này để', 'I am writing to confirm our meeting.', 'Tôi viết thư này để xác nhận cuộc họp.', 4),
  ('regarding', '/rɪˈɡɑːdɪŋ/', 'về việc (prep)', 'I''m writing regarding your invoice.', 'Tôi viết về hoá đơn của bạn.', 5),
  ('with reference to', '/wɪð ˈrefrəns tuː/', 'liên quan đến, tham chiếu', 'With reference to your email of May 3…', 'Liên quan đến email ngày 3/5 của bạn…', 6),
  ('further to', '/ˈfɜːðə tuː/', 'tiếp theo (cuộc trao đổi trước)', 'Further to our call, here are the details.', 'Tiếp theo cuộc gọi, đây là chi tiết.', 7),
  ('as discussed', '/əz dɪˈskʌst/', 'như đã trao đổi', 'As discussed, I''ve attached the quote.', 'Như đã trao đổi, tôi đính kèm báo giá.', 8),
  ('please find attached', '/pliːz faɪnd əˈtætʃt/', 'vui lòng xem tệp đính kèm', 'Please find attached the report.', 'Vui lòng xem báo cáo đính kèm.', 9),
  ('attachment', '/əˈtætʃmənt/', 'tệp đính kèm (n)', 'I forgot the attachment, sorry!', 'Tôi quên tệp đính kèm, xin lỗi!', 10),
  ('cc', '/ˌsiː ˈsiː/', 'gửi đồng thời (v)', 'Please cc my manager.', 'Vui lòng cc quản lý của tôi.', 11),
  ('subject line', '/ˈsʌbdʒɪkt laɪn/', 'dòng tiêu đề (n)', 'Use a clear subject line.', 'Dùng tiêu đề email rõ ràng.', 12),
  ('recipient', '/rɪˈsɪpiənt/', 'người nhận (n)', 'Check the recipient before sending.', 'Kiểm tra người nhận trước khi gửi.', 13),
  ('reply all', '/rɪˈplaɪ ɔːl/', 'trả lời tất cả', 'Don''t reply all for personal notes.', 'Đừng trả lời tất cả cho việc cá nhân.', 14),
  ('forward', '/ˈfɔːwəd/', 'chuyển tiếp (v)', 'I''ll forward you the details.', 'Tôi sẽ chuyển tiếp chi tiết cho bạn.', 15),
  ('follow up', '/ˈfɒləʊ ʌp/', 'hỏi thăm tiếp, nhắc lại', 'I''m following up on my last email.', 'Tôi nhắc lại email trước của mình.', 16),
  ('just a reminder', '/dʒʌst ə rɪˈmaɪndə/', 'chỉ nhắc nhẹ rằng', 'Just a reminder that the report is due Friday.', 'Nhắc nhẹ là báo cáo đến hạn thứ Sáu.', 17),
  ('could you please', '/kʊd juː pliːz/', 'bạn vui lòng… được không', 'Could you please send the file again?', 'Bạn vui lòng gửi lại tệp được không?', 18),
  ('I would appreciate it if', '/aɪ wʊd əˈpriːʃieɪt ɪt ɪf/', 'tôi sẽ rất cảm kích nếu', 'I would appreciate it if you could reply today.', 'Tôi rất cảm kích nếu bạn trả lời hôm nay.', 19),
  ('at your earliest convenience', '/ət jɔːr ˈɜːliɪst kənˈviːniəns/', 'sớm nhất khi bạn tiện', 'Please reply at your earliest convenience.', 'Vui lòng trả lời sớm nhất khi tiện.', 20),
  ('as soon as possible', '/əz suːn əz ˈpɒsəbl/', 'càng sớm càng tốt', 'Send the contract as soon as possible.', 'Gửi hợp đồng càng sớm càng tốt.', 21),
  ('by the end of the day', '/baɪ ði end əv ðə deɪ/', 'trước cuối ngày', 'I need the numbers by the end of the day.', 'Tôi cần số liệu trước cuối ngày.', 22),
  ('let me know', '/let miː nəʊ/', 'cho tôi biết', 'Let me know if you have questions.', 'Cho tôi biết nếu bạn có câu hỏi.', 23),
  ('feel free to', '/fiːl friː tuː/', 'cứ thoải mái', 'Feel free to contact me anytime.', 'Cứ liên hệ tôi bất cứ lúc nào.', 24),
  ('do not hesitate to', '/duː nɒt ˈhezɪteɪt tuː/', 'đừng ngần ngại', 'Do not hesitate to ask for help.', 'Đừng ngần ngại nhờ giúp đỡ.', 25),
  ('I look forward to', '/aɪ lʊk ˈfɔːwəd tuː/', 'tôi mong đợi', 'I look forward to hearing from you.', 'Tôi mong nhận được phản hồi từ bạn.', 26),
  ('Best regards', '/best rɪˈɡɑːdz/', 'Trân trọng (kết thư)', 'Best regards, Minh', 'Trân trọng, Minh', 27),
  ('Kind regards', '/kaɪnd rɪˈɡɑːdz/', 'Trân trọng (kết thư)', 'Kind regards, Anna Lee', 'Trân trọng, Anna Lee', 28),
  ('Sincerely', '/sɪnˈsɪəli/', 'Trân trọng (trang trọng)', 'Sincerely, David Park', 'Trân trọng, David Park', 29),
  ('Cheers', '/tʃɪəz/', 'Cảm ơn nhé (kết thư thân mật)', 'Cheers, Tom', 'Cảm ơn nhé, Tom', 30),
  ('acknowledge', '/əkˈnɒlɪdʒ/', 'xác nhận đã nhận (v)', 'Please acknowledge receipt of this email.', 'Vui lòng xác nhận đã nhận email này.', 31),
  ('noted', '/ˈnəʊtɪd/', 'đã ghi nhận', 'Noted, thanks for the update.', 'Đã ghi nhận, cảm ơn cập nhật.', 32),
  ('apologies for', '/əˈpɒlədʒiz fɔː/', 'xin lỗi vì', 'Apologies for the late reply.', 'Xin lỗi vì trả lời muộn.', 33),
  ('thank you for your patience', '/θæŋk juː fɔː jɔː ˈpeɪʃns/', 'cảm ơn bạn đã kiên nhẫn', 'Thank you for your patience while we fix this.', 'Cảm ơn bạn đã kiên nhẫn trong lúc chúng tôi khắc phục.', 34),
  ('out of office', '/aʊt əv ˈɒfɪs/', 'vắng mặt (tự động trả lời)', 'I''m out of office until Monday.', 'Tôi vắng mặt đến thứ Hai.', 35),
  ('urgent', '/ˈɜːdʒənt/', 'khẩn (adj)', 'This is urgent; please call me.', 'Việc này khẩn; vui lòng gọi tôi.', 36),
  ('FYI', '/ˌef waɪ ˈaɪ/', 'để bạn biết (for your information)', 'FYI, the office closes early Friday.', 'Để bạn biết, văn phòng đóng cửa sớm thứ Sáu.', 37),
  ('ASAP', '/ˌeɪ es eɪ ˈpiː/', 'càng sớm càng tốt (viết tắt)', 'Please send it ASAP.', 'Vui lòng gửi càng sớm càng tốt.', 38),
  ('TBD', '/ˌtiː biː ˈdiː/', 'sẽ quyết định sau (to be decided)', 'The venue is TBD.', 'Địa điểm sẽ quyết định sau.', 39),
  ('EOD', '/ˌiː əʊ ˈdiː/', 'cuối ngày (end of day)', 'I''ll have it ready by EOD.', 'Tôi sẽ xong trước cuối ngày.', 40),
  ('draft', '/drɑːft/', 'bản nháp (n)', 'Here is the first draft of the proposal.', 'Đây là bản nháp đầu tiên của đề xuất.', 41),
  ('proofread', '/ˈpruːfriːd/', 'đọc soát lỗi (v)', 'Please proofread before sending.', 'Vui lòng soát lỗi trước khi gửi.', 42),
  ('typo', '/ˈtaɪpəʊ/', 'lỗi đánh máy (n)', 'There''s a typo in the subject.', 'Có lỗi đánh máy ở tiêu đề.', 43),
  ('formal', '/ˈfɔːml/', 'trang trọng (adj)', 'Use a formal tone with new clients.', 'Dùng giọng trang trọng với khách mới.', 44),
  ('informal', '/ɪnˈfɔːml/', 'thân mật (adj)', 'An informal email is fine for colleagues.', 'Email thân mật thì ổn với đồng nghiệp.', 45),
  ('tone', '/təʊn/', 'giọng điệu (n)', 'Keep the tone polite.', 'Giữ giọng điệu lịch sự.', 46),
  ('concise', '/kənˈsaɪs/', 'ngắn gọn (adj)', 'Keep your emails concise.', 'Viết email ngắn gọn.', 47),
  ('clarify', '/ˈklærəfaɪ/', 'làm rõ (v)', 'Could you clarify the deadline?', 'Bạn làm rõ hạn chót được không?', 48),
  ('confirm', '/kənˈfɜːm/', 'xác nhận (v)', 'Please confirm your attendance.', 'Vui lòng xác nhận tham dự.', 49),
  ('reschedule', '/ˌriːˈʃedjuːl/', 'dời lịch (v)', 'Can we reschedule to Thursday?', 'Mình dời sang thứ Năm được không?', 50),
  ('availability', '/əˌveɪləˈbɪləti/', 'lịch rảnh (n)', 'Please share your availability next week.', 'Vui lòng cho biết lịch rảnh tuần sau.', 51),
  ('phone call', '/fəʊn kɔːl/', 'cuộc gọi (n)', 'Let''s set up a phone call.', 'Mình sắp xếp một cuộc gọi nhé.', 52),
  ('this is … speaking', '/ðɪs ɪz ˈspiːkɪŋ/', 'tôi là … đang nghe (khi nghe máy)', 'Hello, this is Lan speaking.', 'Alo, Lan nghe đây.', 53),
  ('may I speak to', '/meɪ aɪ spiːk tuː/', 'cho tôi gặp', 'May I speak to Mr. Hung, please?', 'Cho tôi gặp ông Hùng được không?', 54),
  ('hold the line', '/həʊld ðə laɪn/', 'giữ máy', 'Please hold the line.', 'Vui lòng giữ máy.', 55),
  ('put through', '/pʊt θruː/', 'nối máy', 'I''ll put you through to sales.', 'Tôi nối máy bạn sang phòng kinh doanh.', 56),
  ('leave a message', '/liːv ə ˈmesɪdʒ/', 'để lại lời nhắn', 'Would you like to leave a message?', 'Bạn muốn để lại lời nhắn không?', 57),
  ('call back', '/kɔːl bæk/', 'gọi lại', 'I''ll call you back in ten minutes.', 'Tôi gọi lại bạn sau mười phút.', 58),
  ('bad connection', '/bæd kəˈnekʃn/', 'sóng yếu, kết nối kém', 'Sorry, we have a bad connection.', 'Xin lỗi, kết nối kém quá.', 59),
  ('you''re breaking up', '/jɔː ˈbreɪkɪŋ ʌp/', 'tiếng bạn bị ngắt quãng', 'You''re breaking up; can you repeat that?', 'Tiếng bạn ngắt quãng; nhắc lại được không?', 60),
  ('speak up', '/spiːk ʌp/', 'nói to lên', 'Could you speak up a little?', 'Bạn nói to hơn chút được không?', 61),
  ('extension number', '/ɪkˈstenʃn ˈnʌmbə/', 'số máy lẻ (n)', 'What''s your extension number?', 'Số máy lẻ của bạn là gì?', 62),
  ('voicemail', '/ˈvɔɪsmeɪl/', 'hộp thư thoại (n)', 'It went to voicemail.', 'Cuộc gọi chuyển vào hộp thư thoại.', 63),
  ('text message', '/tekst ˈmesɪdʒ/', 'tin nhắn (n)', 'Send me a text message when you''re free.', 'Nhắn tin cho tôi khi bạn rảnh.', 64),
  ('group chat', '/ɡruːp tʃæt/', 'nhóm chat (n)', 'Post the update in the group chat.', 'Đăng cập nhật vào nhóm chat.', 65),
  ('instant messaging', '/ˈɪnstənt ˈmesɪdʒɪŋ/', 'nhắn tin tức thời (n)', 'We use instant messaging for quick questions.', 'Chúng tôi nhắn tin nhanh cho câu hỏi ngắn.', 66),
  ('notification', '/ˌnəʊtɪfɪˈkeɪʃn/', 'thông báo (n)', 'Turn off notifications during the meeting.', 'Tắt thông báo trong lúc họp.', 67),
  ('inbox', '/ˈɪnbɒks/', 'hộp thư đến (n)', 'My inbox is full.', 'Hộp thư đến của tôi đầy rồi.', 68),
  ('spam', '/spæm/', 'thư rác (n)', 'Check your spam folder.', 'Kiểm tra thư mục thư rác.', 69),
  ('signature', '/ˈsɪɡnətʃə/', 'chữ ký email (n)', 'Add your phone number to your email signature.', 'Thêm số điện thoại vào chữ ký email.', 70),
  ('template', '/ˈtempleɪt/', 'mẫu có sẵn (n)', 'Use the email template for quotes.', 'Dùng mẫu email cho báo giá.', 71),
  ('greeting', '/ˈɡriːtɪŋ/', 'lời chào (n)', 'Start with a proper greeting.', 'Bắt đầu bằng lời chào đúng mực.', 72),
  ('sign off', '/saɪn ɒf/', 'kết thư', 'Sign off with your full name.', 'Kết thư bằng tên đầy đủ.', 73),
  ('request', '/rɪˈkwest/', 'yêu cầu (n, v)', 'I have a small request.', 'Tôi có một yêu cầu nhỏ.', 74),
  ('enquiry', '/ɪnˈkwaɪəri/', 'câu hỏi, yêu cầu thông tin (n)', 'Thank you for your enquiry.', 'Cảm ơn yêu cầu của bạn.', 75),
  ('response', '/rɪˈspɒns/', 'phản hồi (n)', 'Thanks for the quick response.', 'Cảm ơn phản hồi nhanh.', 76),
  ('prompt', '/prɒmpt/', 'nhanh chóng, kịp thời (adj)', 'Thank you for your prompt reply.', 'Cảm ơn bạn đã trả lời nhanh.', 77),
  ('in advance', '/ɪn ədˈvɑːns/', 'trước', 'Thank you in advance for your help.', 'Cảm ơn trước vì sự giúp đỡ của bạn.', 78),
  ('keep me posted', '/kiːp miː ˈpəʊstɪd/', 'cập nhật cho tôi nhé', 'Keep me posted on the progress.', 'Cập nhật tiến độ cho tôi nhé.', 79),
  ('touch base', '/tʌtʃ beɪs/', 'liên hệ ngắn để trao đổi', 'Let''s touch base next week.', 'Tuần sau mình trao đổi nhanh nhé.', 80),
  ('loop in', '/luːp ɪn/', 'đưa (ai) vào cuộc trao đổi', 'Let me loop in our designer.', 'Để tôi thêm designer vào cuộc trao đổi.', 81),
  ('circle back', '/ˈsɜːkl bæk/', 'quay lại bàn sau', 'I''ll circle back after the meeting.', 'Tôi sẽ quay lại việc này sau cuộc họp.', 82),
  ('on the same page', '/ɒn ðə seɪm peɪdʒ/', 'cùng hiểu một ý', 'Let''s make sure we''re on the same page.', 'Hãy chắc là chúng ta hiểu giống nhau.', 83),
  ('heads-up', '/ˈhedz ʌp/', 'báo trước (n)', 'Just a heads-up: the client is visiting tomorrow.', 'Báo trước: mai khách hàng đến thăm.', 84),
  ('bear with me', '/beə wɪð miː/', 'chịu khó chờ tôi chút', 'Bear with me while I find the file.', 'Chờ tôi chút, tôi tìm tệp.', 85),
  ('get back to', '/ɡet bæk tuː/', 'trả lời lại (ai)', 'I''ll get back to you by Friday.', 'Tôi sẽ trả lời bạn trước thứ Sáu.', 86),
  ('professional', '/prəˈfeʃənl/', 'chuyên nghiệp (adj)', 'Keep the email professional.', 'Giữ email chuyên nghiệp.', 87),
  ('courtesy', '/ˈkɜːtəsi/', 'sự lịch sự (n)', 'A quick thank-you is basic courtesy.', 'Cảm ơn nhanh là phép lịch sự cơ bản.', 88),
  ('misunderstanding', '/ˌmɪsʌndəˈstændɪŋ/', 'sự hiểu lầm (n)', 'Sorry, there was a misunderstanding.', 'Xin lỗi, có sự hiểu lầm.', 89),
  ('correction', '/kəˈrekʃn/', 'sự đính chính (n)', 'Correction: the meeting is at 3, not 2.', 'Đính chính: họp lúc 3 giờ, không phải 2.', 90),
  ('resend', '/ˌriːˈsend/', 'gửi lại (v)', 'Could you resend the invoice?', 'Bạn gửi lại hoá đơn được không?', 91),
  ('recall', '/rɪˈkɔːl/', 'thu hồi (email) (v)', 'I tried to recall the email.', 'Tôi đã cố thu hồi email.', 92),
  ('bcc', '/ˌbiː siː ˈsiː/', 'gửi ẩn (v)', 'Bcc the whole list to protect privacy.', 'Gửi ẩn cho cả danh sách để bảo mật.', 93),
  ('read receipt', '/riːd rɪˈsiːt/', 'xác nhận đã đọc (n)', 'Request a read receipt for important emails.', 'Yêu cầu xác nhận đã đọc với email quan trọng.', 94),
  ('schedule send', '/ˈʃedjuːl send/', 'hẹn giờ gửi', 'Schedule send for 8 a.m. tomorrow.', 'Hẹn gửi lúc 8 giờ sáng mai.', 95),
  ('unsubscribe', '/ˌʌnsəbˈskraɪb/', 'huỷ đăng ký (v)', 'Click here to unsubscribe.', 'Bấm vào đây để huỷ đăng ký.', 96),
  ('internal', '/ɪnˈtɜːnl/', 'nội bộ (adj)', 'This is an internal memo.', 'Đây là thông báo nội bộ.', 97),
  ('external', '/ɪkˈstɜːnl/', 'bên ngoài (adj)', 'Be careful with external emails.', 'Cẩn thận với email từ bên ngoài.', 98),
  ('distribution list', '/ˌdɪstrɪˈbjuːʃn lɪst/', 'danh sách người nhận chung (n)', 'Add the new hire to the distribution list.', 'Thêm nhân viên mới vào danh sách nhận email.', 99),
  ('quick question', '/kwɪk ˈkwestʃən/', 'câu hỏi nhanh', 'Quick question: is the office open Saturday?', 'Hỏi nhanh: thứ Bảy văn phòng có mở không?', 100)
) as w(term, phonetic, meaning_vi, example_en, example_vi, position) on true
where d.slug = 'cong-viec-email'
on conflict (deck_id, term) do nothing;

-- Họp & thuyết trình (100 từ)
insert into public.decks (slug, name, description, level, category, position)
values ('cong-viec-hop', 'Họp & thuyết trình', 'Điều hành cuộc họp, trình bày, phản hồi', 'intermediate', 'cong-viec', 20)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, level = excluded.level,
  category = excluded.category, position = excluded.position;

insert into public.words (deck_id, term, phonetic, meaning_vi, example_en, example_vi, position)
select d.id, w.term, w.phonetic, w.meaning_vi, w.example_en, w.example_vi, w.position
from public.decks d
join (values
  ('agenda', '/əˈdʒendə/', 'chương trình họp (n)', 'I''ve sent the agenda for tomorrow''s meeting.', 'Tôi đã gửi chương trình cho cuộc họp ngày mai.', 1),
  ('minutes', '/ˈmɪnɪts/', 'biên bản họp (n)', 'Who is taking the minutes today?', 'Hôm nay ai ghi biên bản?', 2),
  ('chair', '/tʃeə/', 'chủ trì (v); người chủ trì (n)', 'Linh will chair the meeting.', 'Linh sẽ chủ trì cuộc họp.', 3),
  ('attendee', '/əˌtenˈdiː/', 'người tham dự (n)', 'There were twelve attendees.', 'Có mười hai người tham dự.', 4),
  ('call the meeting to order', '/kɔːl ðə ˈmiːtɪŋ tuː ˈɔːdə/', 'tuyên bố bắt đầu họp', 'Let''s call the meeting to order.', 'Chúng ta bắt đầu cuộc họp nhé.', 5),
  ('kick off', '/kɪk ɒf/', 'bắt đầu, khởi động', 'Let''s kick off with the sales update.', 'Bắt đầu với cập nhật doanh số nhé.', 6),
  ('purpose of the meeting', '/ˈpɜːpəs əv ðə ˈmiːtɪŋ/', 'mục đích cuộc họp', 'The purpose of the meeting is to pick a vendor.', 'Mục đích cuộc họp là chọn nhà cung cấp.', 7),
  ('item', '/ˈaɪtəm/', 'mục, điểm (trong chương trình) (n)', 'Let''s move on to the next item.', 'Chuyển sang mục tiếp theo nhé.', 8),
  ('move on', '/muːv ɒn/', 'chuyển sang phần tiếp', 'If there are no questions, let''s move on.', 'Nếu không có câu hỏi, ta chuyển tiếp.', 9),
  ('go around the table', '/ɡəʊ əˈraʊnd ðə ˈteɪbl/', 'lần lượt từng người phát biểu', 'Let''s go around the table for quick updates.', 'Mỗi người lần lượt cập nhật nhanh nhé.', 10),
  ('the floor is yours', '/ðə flɔːr ɪz jɔːz/', 'mời bạn phát biểu', 'Mai, the floor is yours.', 'Mai, mời bạn phát biểu.', 11),
  ('interrupt', '/ˌɪntəˈrʌpt/', 'ngắt lời (v)', 'Sorry to interrupt, but we''re out of time.', 'Xin lỗi ngắt lời, nhưng hết giờ rồi.', 12),
  ('may I add', '/meɪ aɪ æd/', 'cho tôi bổ sung', 'May I add one point?', 'Cho tôi bổ sung một ý?', 13),
  ('in my opinion', '/ɪn maɪ əˈpɪnjən/', 'theo ý tôi', 'In my opinion, we should wait.', 'Theo ý tôi, chúng ta nên chờ.', 14),
  ('from my perspective', '/frəm maɪ pəˈspektɪv/', 'theo góc nhìn của tôi', 'From my perspective, the risk is low.', 'Theo góc nhìn của tôi, rủi ro thấp.', 15),
  ('I''d like to point out', '/aɪd laɪk tuː pɔɪnt aʊt/', 'tôi muốn chỉ ra rằng', 'I''d like to point out that costs have doubled.', 'Tôi muốn chỉ ra rằng chi phí đã tăng gấp đôi.', 16),
  ('I agree with', '/aɪ əˈɡriː wɪð/', 'tôi đồng ý với', 'I agree with Tuan on this.', 'Tôi đồng ý với Tuấn về việc này.', 17),
  ('I''m afraid I disagree', '/aɪm əˈfreɪd aɪ ˌdɪsəˈɡriː/', 'e rằng tôi không đồng ý', 'I''m afraid I disagree with that plan.', 'E rằng tôi không đồng ý với kế hoạch đó.', 18),
  ('I see your point, but', '/aɪ siː jɔː pɔɪnt bʌt/', 'tôi hiểu ý bạn, nhưng', 'I see your point, but the budget is fixed.', 'Tôi hiểu ý bạn, nhưng ngân sách đã cố định.', 19),
  ('fair enough', '/feər ɪˈnʌf/', 'cũng hợp lý', 'Fair enough, let''s try it your way.', 'Cũng hợp lý, thử theo cách của bạn.', 20),
  ('consensus', '/kənˈsensəs/', 'sự đồng thuận (n)', 'We reached a consensus quickly.', 'Chúng tôi đạt đồng thuận nhanh chóng.', 21),
  ('vote', '/vəʊt/', 'biểu quyết (v, n)', 'Let''s vote on the two options.', 'Chúng ta biểu quyết hai phương án nhé.', 22),
  ('unanimous', '/juˈnænɪməs/', 'nhất trí hoàn toàn (adj)', 'The decision was unanimous.', 'Quyết định được nhất trí hoàn toàn.', 23),
  ('objection', '/əbˈdʒekʃn/', 'sự phản đối (n)', 'Any objections to the proposal?', 'Có ai phản đối đề xuất không?', 24),
  ('postpone', '/pəˈspəʊn/', 'hoãn lại (v)', 'Let''s postpone this until next week.', 'Hoãn việc này đến tuần sau nhé.', 25),
  ('table the discussion', '/ˈteɪbl ðə dɪˈskʌʃn/', 'gác lại thảo luận', 'Let''s table the discussion for now.', 'Tạm gác lại thảo luận này.', 26),
  ('parking lot', '/ˈpɑːkɪŋ lɒt/', 'danh sách ý để bàn sau (n)', 'Put that idea in the parking lot.', 'Để ý đó vào danh sách bàn sau.', 27),
  ('off topic', '/ɒf ˈtɒpɪk/', 'lạc đề', 'That''s a bit off topic.', 'Cái đó hơi lạc đề.', 28),
  ('get back on track', '/ɡet bæk ɒn træk/', 'quay lại đúng hướng', 'Let''s get back on track.', 'Quay lại chủ đề chính nhé.', 29),
  ('time check', '/taɪm tʃek/', 'nhắc giờ', 'Quick time check: ten minutes left.', 'Nhắc giờ: còn mười phút.', 30),
  ('wrap up', '/ræp ʌp/', 'kết thúc, tổng kết', 'Let''s wrap up in five minutes.', 'Kết thúc trong năm phút nữa nhé.', 31),
  ('to sum up', '/tuː sʌm ʌp/', 'tóm lại', 'To sum up, we launch in June.', 'Tóm lại, chúng ta ra mắt vào tháng Sáu.', 32),
  ('action item', '/ˈækʃn ˈaɪtəm/', 'việc cần làm sau họp (n)', 'I''ll list the action items.', 'Tôi sẽ liệt kê các việc cần làm.', 33),
  ('takeaway', '/ˈteɪkəweɪ/', 'điểm rút ra (n)', 'The key takeaway is to focus on retention.', 'Điểm rút ra chính là tập trung giữ khách.', 34),
  ('next steps', '/nekst steps/', 'các bước tiếp theo', 'What are the next steps?', 'Các bước tiếp theo là gì?', 35),
  ('adjourn', '/əˈdʒɜːn/', 'kết thúc, tạm nghỉ họp (v)', 'The meeting was adjourned at noon.', 'Cuộc họp kết thúc lúc trưa.', 36),
  ('stand-up', '/ˈstænd ʌp/', 'họp đứng ngắn hằng ngày (n)', 'Our stand-up is at 9 a.m.', 'Họp đứng của chúng tôi lúc 9 giờ sáng.', 37),
  ('one-on-one', '/ˌwʌn ɒn ˈwʌn/', 'họp riêng hai người (n)', 'I have a one-on-one with my manager.', 'Tôi có buổi họp riêng với quản lý.', 38),
  ('brainstorm', '/ˈbreɪnstɔːm/', 'động não, nêu ý tưởng (v)', 'Let''s brainstorm names for the app.', 'Cùng động não đặt tên cho ứng dụng.', 39),
  ('briefing', '/ˈbriːfɪŋ/', 'buổi phổ biến ngắn (n)', 'There''s a briefing before the launch.', 'Có buổi phổ biến trước khi ra mắt.', 40),
  ('conference call', '/ˈkɒnfərəns kɔːl/', 'họp qua điện thoại (n)', 'We have a conference call with Tokyo.', 'Chúng tôi họp qua điện thoại với Tokyo.', 41),
  ('video call', '/ˈvɪdiəʊ kɔːl/', 'gọi video (n)', 'Let''s switch to a video call.', 'Chuyển sang gọi video nhé.', 42),
  ('you''re on mute', '/jɔːr ɒn mjuːt/', 'bạn đang tắt mic', 'Sorry, you''re on mute.', 'Xin lỗi, bạn đang tắt mic.', 43),
  ('share your screen', '/ʃeə jɔː skriːn/', 'chia sẻ màn hình', 'Could you share your screen?', 'Bạn chia sẻ màn hình được không?', 44),
  ('can everyone see this', '/kæn ˈevriwʌn siː ðɪs/', 'mọi người thấy chưa', 'Can everyone see this slide?', 'Mọi người thấy slide này chưa?', 45),
  ('breakout room', '/ˈbreɪkaʊt ruːm/', 'phòng thảo luận nhóm nhỏ (n)', 'We''ll split into breakout rooms.', 'Chúng ta sẽ chia vào phòng nhóm nhỏ.', 46),
  ('presentation', '/ˌpreznˈteɪʃn/', 'bài thuyết trình (n)', 'Her presentation was excellent.', 'Bài thuyết trình của cô ấy rất tốt.', 47),
  ('slide', '/slaɪd/', 'trang trình chiếu (n)', 'Go back to the previous slide.', 'Quay lại slide trước.', 48),
  ('handout', '/ˈhændaʊt/', 'tài liệu phát tay (n)', 'The figures are in your handout.', 'Số liệu có trong tài liệu phát tay.', 49),
  ('outline', '/ˈaʊtlaɪn/', 'dàn ý (n); phác thảo (v)', 'Let me outline the three parts.', 'Để tôi phác thảo ba phần.', 50),
  ('I''ll walk you through', '/aɪl wɔːk juː θruː/', 'tôi sẽ dẫn bạn qua từng bước', 'I''ll walk you through the process.', 'Tôi sẽ dẫn bạn qua từng bước quy trình.', 51),
  ('as you can see', '/əz juː kæn siː/', 'như bạn thấy', 'As you can see, sales rose in May.', 'Như bạn thấy, doanh số tăng vào tháng Năm.', 52),
  ('this chart shows', '/ðɪs tʃɑːt ʃəʊz/', 'biểu đồ này cho thấy', 'This chart shows monthly revenue.', 'Biểu đồ này cho thấy doanh thu theo tháng.', 53),
  ('highlight', '/ˈhaɪlaɪt/', 'nhấn mạnh (v); điểm nổi bật (n)', 'I want to highlight two results.', 'Tôi muốn nhấn mạnh hai kết quả.', 54),
  ('key point', '/kiː pɔɪnt/', 'điểm chính (n)', 'The key point is speed.', 'Điểm chính là tốc độ.', 55),
  ('in a nutshell', '/ɪn ə ˈnʌtʃel/', 'nói ngắn gọn', 'In a nutshell, we need more staff.', 'Nói ngắn gọn, chúng ta cần thêm người.', 56),
  ('let''s move to', '/lets muːv tuː/', 'chuyển sang', 'Let''s move to the second part.', 'Chuyển sang phần thứ hai.', 57),
  ('that brings me to', '/ðæt brɪŋz miː tuː/', 'điều đó dẫn tôi đến', 'That brings me to the budget.', 'Điều đó dẫn tôi đến phần ngân sách.', 58),
  ('Q&A', '/ˌkjuː ən ˈeɪ/', 'phần hỏi đáp (n)', 'We''ll have a Q&A at the end.', 'Sẽ có phần hỏi đáp ở cuối.', 59),
  ('any questions', '/ˈeni ˈkwestʃənz/', 'có câu hỏi nào không', 'Any questions so far?', 'Đến đây có câu hỏi nào không?', 60),
  ('good question', '/ɡʊd ˈkwestʃən/', 'câu hỏi hay', 'Good question, let me check.', 'Câu hỏi hay, để tôi kiểm tra.', 61),
  ('I''ll get back to you on that', '/aɪl ɡet bæk tuː juː ɒn ðæt/', 'tôi sẽ trả lời bạn sau về việc đó', 'I''ll get back to you on that after the meeting.', 'Tôi sẽ trả lời bạn việc đó sau cuộc họp.', 62),
  ('rehearse', '/rɪˈhɜːs/', 'tập dượt (v)', 'Rehearse the pitch twice.', 'Tập dượt bài thuyết trình hai lần.', 63),
  ('body language', '/ˈbɒdi ˈlæŋɡwɪdʒ/', 'ngôn ngữ cơ thể (n)', 'Confident body language helps.', 'Ngôn ngữ cơ thể tự tin rất hữu ích.', 64),
  ('eye contact', '/aɪ ˈkɒntækt/', 'giao tiếp bằng mắt (n)', 'Keep eye contact with the audience.', 'Giữ giao tiếp bằng mắt với khán giả.', 65),
  ('audience', '/ˈɔːdiəns/', 'khán giả (n)', 'Know your audience.', 'Hiểu khán giả của bạn.', 66),
  ('projector', '/prəˈdʒektə/', 'máy chiếu (n)', 'The projector isn''t working.', 'Máy chiếu không hoạt động.', 67),
  ('whiteboard', '/ˈwaɪtbɔːd/', 'bảng trắng (n)', 'Let me draw it on the whiteboard.', 'Để tôi vẽ lên bảng trắng.', 68),
  ('feedback', '/ˈfiːdbæk/', 'phản hồi, góp ý (n)', 'I''d love your feedback on the slides.', 'Tôi muốn nghe góp ý về slide.', 69),
  ('constructive', '/kənˈstrʌktɪv/', 'mang tính xây dựng (adj)', 'Please keep the feedback constructive.', 'Vui lòng góp ý mang tính xây dựng.', 70),
  ('suggestion', '/səˈdʒestʃən/', 'gợi ý (n)', 'I have a suggestion for the layout.', 'Tôi có gợi ý cho bố cục.', 71),
  ('concern', '/kənˈsɜːn/', 'mối lo ngại (n)', 'My main concern is the timeline.', 'Lo ngại chính của tôi là tiến độ.', 72),
  ('raise an issue', '/reɪz ən ˈɪʃuː/', 'nêu vấn đề', 'I''d like to raise an issue with delivery.', 'Tôi muốn nêu vấn đề về giao hàng.', 73),
  ('clarification', '/ˌklærəfɪˈkeɪʃn/', 'sự làm rõ (n)', 'Can I ask for clarification?', 'Tôi xin hỏi để làm rõ được không?', 74),
  ('elaborate', '/ɪˈlæbəreɪt/', 'nói rõ thêm (v)', 'Could you elaborate on that?', 'Bạn nói rõ thêm được không?', 75),
  ('rephrase', '/ˌriːˈfreɪz/', 'diễn đạt lại (v)', 'Let me rephrase the question.', 'Để tôi diễn đạt lại câu hỏi.', 76),
  ('if I understand correctly', '/ɪf aɪ ˌʌndəˈstænd kəˈrektli/', 'nếu tôi hiểu đúng', 'If I understand correctly, we start Monday.', 'Nếu tôi hiểu đúng, ta bắt đầu thứ Hai.', 77),
  ('correct me if I''m wrong', '/kəˈrekt miː ɪf aɪm rɒŋ/', 'sửa nếu tôi sai', 'Correct me if I''m wrong, but the budget is 50k.', 'Sửa nếu tôi sai, nhưng ngân sách là 50k.', 78),
  ('decision', '/dɪˈsɪʒn/', 'quyết định (n)', 'We need a decision by Friday.', 'Cần quyết định trước thứ Sáu.', 79),
  ('proposal', '/prəˈpəʊzl/', 'đề xuất (n)', 'The proposal was approved.', 'Đề xuất đã được duyệt.', 80),
  ('recommend', '/ˌrekəˈmend/', 'đề nghị, khuyến nghị (v)', 'I recommend option B.', 'Tôi khuyến nghị phương án B.', 81),
  ('priority', '/praɪˈɒrəti/', 'ưu tiên (n)', 'Security is our top priority.', 'Bảo mật là ưu tiên hàng đầu.', 82),
  ('trade-off', '/ˈtreɪd ɒf/', 'sự đánh đổi (n)', 'There''s a trade-off between cost and speed.', 'Có sự đánh đổi giữa chi phí và tốc độ.', 83),
  ('pros and cons', '/prəʊz ənd kɒnz/', 'ưu và nhược điểm', 'Let''s weigh the pros and cons.', 'Cùng cân nhắc ưu và nhược điểm.', 84),
  ('alternative', '/ɔːlˈtɜːnətɪv/', 'phương án thay thế (n)', 'Is there an alternative?', 'Có phương án thay thế không?', 85),
  ('compromise', '/ˈkɒmprəmaɪz/', 'thoả hiệp (n, v)', 'We found a compromise.', 'Chúng tôi tìm được thoả hiệp.', 86),
  ('input', '/ˈɪnpʊt/', 'ý kiến đóng góp (n)', 'Thanks for your input.', 'Cảm ơn ý kiến đóng góp của bạn.', 87),
  ('participate', '/pɑːˈtɪsɪpeɪt/', 'tham gia (v)', 'Everyone is welcome to participate.', 'Mọi người đều có thể tham gia.', 88),
  ('punctual', '/ˈpʌŋktʃuəl/', 'đúng giờ (adj)', 'Please be punctual.', 'Vui lòng đúng giờ.', 89),
  ('run late', '/rʌn leɪt/', 'bị trễ giờ', 'The meeting is running late.', 'Cuộc họp đang bị trễ giờ.', 90),
  ('cut short', '/kʌt ʃɔːt/', 'rút ngắn', 'We had to cut the meeting short.', 'Chúng tôi phải rút ngắn cuộc họp.', 91),
  ('book a room', '/bʊk ə ruːm/', 'đặt phòng họp', 'I''ll book a room for 2 p.m.', 'Tôi sẽ đặt phòng lúc 2 giờ chiều.', 92),
  ('meeting room', '/ˈmiːtɪŋ ruːm/', 'phòng họp (n)', 'The meeting room is on the third floor.', 'Phòng họp ở tầng ba.', 93),
  ('invite', '/ɪnˈvaɪt/', 'mời (v); lời mời họp (n)', 'I''ll send a calendar invite.', 'Tôi sẽ gửi lời mời trên lịch.', 94),
  ('decline', '/dɪˈklaɪn/', 'từ chối (v)', 'I had to decline the invite.', 'Tôi phải từ chối lời mời.', 95),
  ('sit in', '/sɪt ɪn/', 'dự thính', 'Can I sit in on the meeting?', 'Tôi dự thính cuộc họp được không?', 96),
  ('debrief', '/ˌdiːˈbriːf/', 'họp rút kinh nghiệm (n, v)', 'Let''s debrief after the client call.', 'Rút kinh nghiệm sau cuộc gọi với khách nhé.', 97),
  ('recap', '/ˈriːkæp/', 'tóm tắt lại (n, v)', 'Here''s a quick recap of the meeting.', 'Đây là tóm tắt nhanh cuộc họp.', 98),
  ('assign', '/əˈsaɪn/', 'giao (việc) (v)', 'I''ll assign the task to Nam.', 'Tôi sẽ giao việc cho Nam.', 99),
  ('owner', '/ˈəʊnə/', 'người phụ trách (n)', 'Who''s the owner of this action item?', 'Ai phụ trách việc này?', 100)
) as w(term, phonetic, meaning_vi, example_en, example_vi, position) on true
where d.slug = 'cong-viec-hop'
on conflict (deck_id, term) do nothing;

-- Quản lý dự án (100 từ)
insert into public.decks (slug, name, description, level, category, position)
values ('cong-viec-du-an', 'Quản lý dự án', 'Kế hoạch, tiến độ, rủi ro, nhóm', 'intermediate', 'cong-viec', 30)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, level = excluded.level,
  category = excluded.category, position = excluded.position;

insert into public.words (deck_id, term, phonetic, meaning_vi, example_en, example_vi, position)
select d.id, w.term, w.phonetic, w.meaning_vi, w.example_en, w.example_vi, w.position
from public.decks d
join (values
  ('project', '/ˈprɒdʒekt/', 'dự án (n)', 'The project starts next month.', 'Dự án bắt đầu vào tháng sau.', 1),
  ('project manager', '/ˈprɒdʒekt ˈmænɪdʒə/', 'quản lý dự án (n)', 'The project manager set the schedule.', 'Quản lý dự án lập lịch trình.', 2),
  ('scope', '/skəʊp/', 'phạm vi (n)', 'Let''s define the scope clearly.', 'Hãy xác định phạm vi rõ ràng.', 3),
  ('scope creep', '/skəʊp kriːp/', 'phình phạm vi (n)', 'Scope creep delayed the launch.', 'Phình phạm vi làm chậm ra mắt.', 4),
  ('deliverable', '/dɪˈlɪvərəbl/', 'sản phẩm bàn giao (n)', 'The first deliverable is a prototype.', 'Sản phẩm bàn giao đầu tiên là bản mẫu.', 5),
  ('milestone', '/ˈmaɪlstəʊn/', 'cột mốc (n)', 'We hit the first milestone on time.', 'Chúng tôi đạt cột mốc đầu tiên đúng hạn.', 6),
  ('timeline', '/ˈtaɪmlaɪn/', 'dòng thời gian, tiến độ (n)', 'The timeline is very tight.', 'Tiến độ rất gấp.', 7),
  ('deadline', '/ˈdedlaɪn/', 'hạn chót (n)', 'The deadline is March 31.', 'Hạn chót là ngày 31/3.', 8),
  ('kick-off meeting', '/ˈkɪk ɒf ˈmiːtɪŋ/', 'họp khởi động dự án (n)', 'The kick-off meeting is on Monday.', 'Họp khởi động vào thứ Hai.', 9),
  ('planning', '/ˈplænɪŋ/', 'lập kế hoạch (n)', 'Good planning saves time later.', 'Lập kế hoạch tốt tiết kiệm thời gian sau này.', 10),
  ('roadmap', '/ˈrəʊdmæp/', 'lộ trình (n)', 'The roadmap covers the next year.', 'Lộ trình bao gồm năm tới.', 11),
  ('phase', '/feɪz/', 'giai đoạn (n)', 'We''re in the testing phase.', 'Chúng tôi đang ở giai đoạn kiểm thử.', 12),
  ('task', '/tɑːsk/', 'nhiệm vụ (n)', 'Break the work into small tasks.', 'Chia công việc thành các nhiệm vụ nhỏ.', 13),
  ('subtask', '/ˈsʌbtɑːsk/', 'nhiệm vụ con (n)', 'Each task has three subtasks.', 'Mỗi nhiệm vụ có ba nhiệm vụ con.', 14),
  ('dependency', '/dɪˈpendənsi/', 'sự phụ thuộc (n)', 'Design is a dependency for development.', 'Thiết kế là điều kiện phụ thuộc cho phát triển.', 15),
  ('critical path', '/ˈkrɪtɪkl pɑːθ/', 'đường găng (n)', 'Testing is on the critical path.', 'Kiểm thử nằm trên đường găng.', 16),
  ('Gantt chart', '/ɡænt tʃɑːt/', 'biểu đồ Gantt (n)', 'The Gantt chart shows all phases.', 'Biểu đồ Gantt hiển thị mọi giai đoạn.', 17),
  ('resource', '/rɪˈzɔːs/', 'nguồn lực (n)', 'We lack resources for phase two.', 'Chúng tôi thiếu nguồn lực cho giai đoạn hai.', 18),
  ('allocate', '/ˈæləkeɪt/', 'phân bổ (v)', 'Allocate two developers to the app.', 'Phân bổ hai lập trình viên cho ứng dụng.', 19),
  ('budget', '/ˈbʌdʒɪt/', 'ngân sách (n)', 'We''re under budget so far.', 'Đến giờ ta vẫn dưới ngân sách.', 20),
  ('over budget', '/ˈəʊvə ˈbʌdʒɪt/', 'vượt ngân sách', 'The project went over budget.', 'Dự án vượt ngân sách.', 21),
  ('estimate', '/ˈestɪmeɪt/', 'ước tính (v, n)', 'Estimate the effort for each task.', 'Ước tính công sức cho mỗi nhiệm vụ.', 22),
  ('effort', '/ˈefət/', 'công sức, khối lượng (n)', 'This feature takes a lot of effort.', 'Tính năng này tốn nhiều công sức.', 23),
  ('workload', '/ˈwɜːkləʊd/', 'khối lượng công việc (n)', 'Our workload is heavy this month.', 'Khối lượng việc tháng này nặng.', 24),
  ('capacity', '/kəˈpæsəti/', 'năng lực, sức chứa (n)', 'The team is at full capacity.', 'Nhóm đã hết công suất.', 25),
  ('stakeholder', '/ˈsteɪkhəʊldə/', 'bên liên quan (n)', 'Keep stakeholders informed.', 'Giữ các bên liên quan được cập nhật.', 26),
  ('sponsor', '/ˈspɒnsə/', 'nhà bảo trợ dự án (n)', 'The sponsor approved the budget.', 'Nhà bảo trợ đã duyệt ngân sách.', 27),
  ('requirement', '/rɪˈkwaɪəmənt/', 'yêu cầu (n)', 'Gather the requirements first.', 'Thu thập yêu cầu trước.', 28),
  ('specification', '/ˌspesɪfɪˈkeɪʃn/', 'bản đặc tả (n)', 'Read the specification carefully.', 'Đọc kỹ bản đặc tả.', 29),
  ('risk', '/rɪsk/', 'rủi ro (n)', 'List every risk in the register.', 'Liệt kê mọi rủi ro vào sổ.', 30),
  ('mitigate', '/ˈmɪtɪɡeɪt/', 'giảm thiểu (v)', 'How can we mitigate this risk?', 'Làm sao giảm thiểu rủi ro này?', 31),
  ('contingency plan', '/kənˈtɪndʒənsi plæn/', 'kế hoạch dự phòng (n)', 'We need a contingency plan.', 'Chúng ta cần kế hoạch dự phòng.', 32),
  ('assumption', '/əˈsʌmpʃn/', 'giả định (n)', 'Document your assumptions.', 'Ghi lại các giả định của bạn.', 33),
  ('constraint', '/kənˈstreɪnt/', 'ràng buộc (n)', 'Time is the main constraint.', 'Thời gian là ràng buộc chính.', 34),
  ('issue', '/ˈɪʃuː/', 'vấn đề (n)', 'We found an issue with the login.', 'Chúng tôi phát hiện vấn đề ở đăng nhập.', 35),
  ('blocker', '/ˈblɒkə/', 'trở ngại chặn tiến độ (n)', 'Any blockers today?', 'Hôm nay có trở ngại gì không?', 36),
  ('escalate', '/ˈeskəleɪt/', 'báo lên cấp trên (v)', 'Escalate the issue to the director.', 'Báo vấn đề lên giám đốc.', 37),
  ('status update', '/ˈsteɪtəs ˈʌpdeɪt/', 'cập nhật tình trạng (n)', 'Send a weekly status update.', 'Gửi cập nhật tình trạng hằng tuần.', 38),
  ('progress report', '/ˈprəʊɡres rɪˈpɔːt/', 'báo cáo tiến độ (n)', 'The progress report is due Friday.', 'Báo cáo tiến độ đến hạn thứ Sáu.', 39),
  ('on track', '/ɒn træk/', 'đúng tiến độ', 'The project is on track.', 'Dự án đang đúng tiến độ.', 40),
  ('behind schedule', '/bɪˈhaɪnd ˈʃedjuːl/', 'chậm tiến độ', 'We''re two weeks behind schedule.', 'Chúng tôi chậm tiến độ hai tuần.', 41),
  ('ahead of schedule', '/əˈhed əv ˈʃedjuːl/', 'vượt tiến độ', 'Design finished ahead of schedule.', 'Thiết kế hoàn thành vượt tiến độ.', 42),
  ('delay', '/dɪˈleɪ/', 'sự chậm trễ (n); trì hoãn (v)', 'The delay cost us a week.', 'Sự chậm trễ khiến ta mất một tuần.', 43),
  ('bottleneck', '/ˈbɒtlnek/', 'nút thắt cổ chai (n)', 'Approval is the bottleneck.', 'Khâu phê duyệt là nút thắt.', 44),
  ('bandwidth', '/ˈbændwɪdθ/', 'thời gian/sức lực rảnh (n)', 'I don''t have bandwidth this week.', 'Tuần này tôi không có thời gian.', 45),
  ('prioritize', '/praɪˈɒrətaɪz/', 'ưu tiên (v)', 'Prioritize the bug fixes.', 'Ưu tiên sửa lỗi.', 46),
  ('backlog', '/ˈbæklɒɡ/', 'danh sách việc tồn (n)', 'Add the idea to the backlog.', 'Thêm ý tưởng vào backlog.', 47),
  ('sprint', '/sprɪnt/', 'chu kỳ sprint (n)', 'Each sprint lasts two weeks.', 'Mỗi sprint kéo dài hai tuần.', 48),
  ('sprint planning', '/sprɪnt ˈplænɪŋ/', 'họp lập kế hoạch sprint (n)', 'Sprint planning is on Monday morning.', 'Họp kế hoạch sprint vào sáng thứ Hai.', 49),
  ('retrospective', '/ˌretrəˈspektɪv/', 'họp nhìn lại (n)', 'We hold a retrospective after each sprint.', 'Chúng tôi họp nhìn lại sau mỗi sprint.', 50),
  ('agile', '/ˈædʒaɪl/', 'linh hoạt (phương pháp) (adj)', 'Our team uses agile methods.', 'Nhóm chúng tôi dùng phương pháp agile.', 51),
  ('scrum', '/skrʌm/', 'khung Scrum (n)', 'Scrum has short daily meetings.', 'Scrum có họp ngắn hằng ngày.', 52),
  ('user story', '/ˈjuːzə ˈstɔːri/', 'câu chuyện người dùng (n)', 'Write a user story for login.', 'Viết user story cho đăng nhập.', 53),
  ('iteration', '/ˌɪtəˈreɪʃn/', 'vòng lặp, lần lặp (n)', 'Each iteration adds new features.', 'Mỗi vòng lặp thêm tính năng mới.', 54),
  ('increment', '/ˈɪŋkrəmənt/', 'phần tăng thêm (n)', 'Deliver a working increment each sprint.', 'Bàn giao phần tăng thêm hoạt động được mỗi sprint.', 55),
  ('velocity', '/vəˈlɒsəti/', 'tốc độ hoàn thành (n)', 'Our velocity is 30 points per sprint.', 'Velocity của nhóm là 30 điểm mỗi sprint.', 56),
  ('kanban board', '/ˈkænbæn bɔːd/', 'bảng Kanban (n)', 'Move the card on the kanban board.', 'Di chuyển thẻ trên bảng Kanban.', 57),
  ('in progress', '/ɪn ˈprəʊɡres/', 'đang thực hiện', 'Three tasks are in progress.', 'Ba nhiệm vụ đang thực hiện.', 58),
  ('done', '/dʌn/', 'hoàn thành', 'Mark the task as done.', 'Đánh dấu nhiệm vụ hoàn thành.', 59),
  ('definition of done', '/ˌdefɪˈnɪʃn əv dʌn/', 'tiêu chí hoàn thành (n)', 'Tests are part of our definition of done.', 'Kiểm thử là một phần tiêu chí hoàn thành.', 60),
  ('acceptance criteria', '/əkˈseptəns kraɪˈtɪəriə/', 'tiêu chí nghiệm thu (n)', 'Write clear acceptance criteria.', 'Viết tiêu chí nghiệm thu rõ ràng.', 61),
  ('sign-off', '/ˈsaɪn ɒf/', 'sự phê duyệt cuối (n)', 'We need client sign-off.', 'Chúng ta cần khách hàng phê duyệt.', 62),
  ('approve', '/əˈpruːv/', 'phê duyệt (v)', 'The board approved the plan.', 'Ban lãnh đạo đã phê duyệt kế hoạch.', 63),
  ('review', '/rɪˈvjuː/', 'xem xét, rà soát (v, n)', 'Please review the design by Tuesday.', 'Vui lòng rà soát thiết kế trước thứ Ba.', 64),
  ('handover', '/ˈhændəʊvə/', 'bàn giao (n)', 'The handover is next week.', 'Bàn giao vào tuần sau.', 65),
  ('launch', '/lɔːntʃ/', 'ra mắt (v, n)', 'We launch the app in May.', 'Chúng tôi ra mắt ứng dụng vào tháng Năm.', 66),
  ('rollout', '/ˈrəʊlaʊt/', 'triển khai dần (n)', 'The rollout starts with two cities.', 'Triển khai bắt đầu với hai thành phố.', 67),
  ('pilot', '/ˈpaɪlət/', 'thử nghiệm quy mô nhỏ (n)', 'We ran a pilot with 50 users.', 'Chúng tôi thử nghiệm với 50 người dùng.', 68),
  ('prototype', '/ˈprəʊtətaɪp/', 'bản mẫu (n)', 'The prototype is ready for testing.', 'Bản mẫu đã sẵn sàng thử nghiệm.', 69),
  ('feasibility', '/ˌfiːzəˈbɪləti/', 'tính khả thi (n)', 'We did a feasibility study.', 'Chúng tôi làm nghiên cứu khả thi.', 70),
  ('lessons learned', '/ˈlesnz lɜːnd/', 'bài học rút ra', 'Record lessons learned at the end.', 'Ghi lại bài học rút ra ở cuối dự án.', 71),
  ('post-mortem', '/ˌpəʊst ˈmɔːtəm/', 'họp mổ xẻ sau sự cố (n)', 'We held a post-mortem after the outage.', 'Chúng tôi họp mổ xẻ sau sự cố.', 72),
  ('KPI', '/ˌkeɪ piː ˈaɪ/', 'chỉ số hiệu suất chính (n)', 'Set KPIs for the project.', 'Đặt KPI cho dự án.', 73),
  ('metric', '/ˈmetrɪk/', 'chỉ số đo lường (n)', 'Which metrics do we track?', 'Chúng ta theo dõi chỉ số nào?', 74),
  ('outcome', '/ˈaʊtkʌm/', 'kết quả (n)', 'Focus on outcomes, not outputs.', 'Tập trung vào kết quả, không phải sản lượng.', 75),
  ('objective', '/əbˈdʒektɪv/', 'mục tiêu (n)', 'The project has three objectives.', 'Dự án có ba mục tiêu.', 76),
  ('goal', '/ɡəʊl/', 'mục đích (n)', 'The goal is to cut costs by 10%.', 'Mục đích là giảm 10% chi phí.', 77),
  ('team lead', '/tiːm liːd/', 'trưởng nhóm (n)', 'Ask the team lead for access.', 'Hỏi trưởng nhóm để được cấp quyền.', 78),
  ('cross-functional', '/ˌkrɒs ˈfʌŋkʃənl/', 'liên phòng ban (adj)', 'It''s a cross-functional team.', 'Đây là nhóm liên phòng ban.', 79),
  ('collaborate', '/kəˈlæbəreɪt/', 'cộng tác (v)', 'Design and dev collaborate daily.', 'Thiết kế và lập trình cộng tác hằng ngày.', 80),
  ('coordinate', '/kəʊˈɔːdɪneɪt/', 'điều phối (v)', 'She coordinates the three vendors.', 'Cô ấy điều phối ba nhà cung cấp.', 81),
  ('delegate', '/ˈdelɪɡeɪt/', 'uỷ quyền, giao việc (v)', 'Delegate routine tasks.', 'Giao các việc thường ngày cho người khác.', 82),
  ('accountable', '/əˈkaʊntəbl/', 'chịu trách nhiệm (adj)', 'Who is accountable for quality?', 'Ai chịu trách nhiệm về chất lượng?', 83),
  ('responsibility', '/rɪˌspɒnsəˈbɪləti/', 'trách nhiệm (n)', 'Clarify each person''s responsibility.', 'Làm rõ trách nhiệm từng người.', 84),
  ('workflow', '/ˈwɜːkfləʊ/', 'quy trình làm việc (n)', 'We simplified the approval workflow.', 'Chúng tôi đơn giản hoá quy trình duyệt.', 85),
  ('track', '/træk/', 'theo dõi (v)', 'Track progress in the tool.', 'Theo dõi tiến độ trong công cụ.', 86),
  ('monitor', '/ˈmɒnɪtə/', 'giám sát (v)', 'Monitor spending every week.', 'Giám sát chi tiêu mỗi tuần.', 87),
  ('adjust', '/əˈdʒʌst/', 'điều chỉnh (v)', 'We adjusted the plan after feedback.', 'Chúng tôi điều chỉnh kế hoạch sau phản hồi.', 88),
  ('change request', '/tʃeɪndʒ rɪˈkwest/', 'yêu cầu thay đổi (n)', 'Submit a change request for new features.', 'Gửi yêu cầu thay đổi cho tính năng mới.', 89),
  ('trade show', '/treɪd ʃəʊ/', 'hội chợ triển lãm (n)', 'The demo is due before the trade show.', 'Bản demo phải xong trước hội chợ.', 90),
  ('vendor', '/ˈvendə/', 'nhà cung cấp (n)', 'We chose a new vendor for hosting.', 'Chúng tôi chọn nhà cung cấp hosting mới.', 91),
  ('outsource', '/ˈaʊtsɔːs/', 'thuê ngoài (v)', 'We outsource the testing.', 'Chúng tôi thuê ngoài phần kiểm thử.', 92),
  ('in-house', '/ˌɪn ˈhaʊs/', 'làm nội bộ (adj, adv)', 'Design is done in-house.', 'Thiết kế được làm nội bộ.', 93),
  ('quality assurance', '/ˈkwɒləti əˈʃʊərəns/', 'đảm bảo chất lượng (n)', 'Quality assurance found ten bugs.', 'Đảm bảo chất lượng phát hiện mười lỗi.', 94),
  ('documentation', '/ˌdɒkjumenˈteɪʃn/', 'tài liệu hướng dẫn (n)', 'Update the documentation after changes.', 'Cập nhật tài liệu sau khi thay đổi.', 95),
  ('lead time', '/liːd taɪm/', 'thời gian chờ thực hiện (n)', 'Lead time for parts is six weeks.', 'Thời gian chờ linh kiện là sáu tuần.', 96),
  ('buffer', '/ˈbʌfə/', 'khoảng đệm (n)', 'Add a two-day buffer to the schedule.', 'Thêm hai ngày đệm vào lịch.', 97),
  ('go live', '/ɡəʊ laɪv/', 'đưa vào vận hành', 'We go live on Friday.', 'Chúng tôi vận hành chính thức thứ Sáu.', 98),
  ('close out', '/kləʊz aʊt/', 'kết thúc, đóng dự án', 'We''ll close out the project this month.', 'Chúng tôi sẽ đóng dự án tháng này.', 99),
  ('work breakdown structure', '/wɜːk ˈbreɪkdaʊn ˈstrʌktʃə/', 'cấu trúc phân rã công việc (n)', 'Build a work breakdown structure before estimating.', 'Lập cấu trúc phân rã công việc trước khi ước tính.', 100)
) as w(term, phonetic, meaning_vi, example_en, example_vi, position) on true
where d.slug = 'cong-viec-du-an'
on conflict (deck_id, term) do nothing;

-- Bán hàng & khách hàng (100 từ)
insert into public.decks (slug, name, description, level, category, position)
values ('cong-viec-khach-hang', 'Bán hàng & khách hàng', 'Chào hàng, đàm phán, chăm sóc khách', 'intermediate', 'cong-viec', 40)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, level = excluded.level,
  category = excluded.category, position = excluded.position;

insert into public.words (deck_id, term, phonetic, meaning_vi, example_en, example_vi, position)
select d.id, w.term, w.phonetic, w.meaning_vi, w.example_en, w.example_vi, w.position
from public.decks d
join (values
  ('customer', '/ˈkʌstəmə/', 'khách hàng (n)', 'The customer is always right.', 'Khách hàng luôn đúng.', 1),
  ('client', '/ˈklaɪənt/', 'khách hàng (dịch vụ) (n)', 'We have a call with the client at 3.', 'Chúng tôi có cuộc gọi với khách lúc 3 giờ.', 2),
  ('customer service', '/ˈkʌstəmə ˈsɜːvɪs/', 'dịch vụ khách hàng (n)', 'Their customer service is excellent.', 'Dịch vụ khách hàng của họ rất tốt.', 3),
  ('customer support', '/ˈkʌstəmə səˈpɔːt/', 'hỗ trợ khách hàng (n)', 'Contact customer support for help.', 'Liên hệ hỗ trợ khách hàng để được giúp.', 4),
  ('how may I help you', '/haʊ meɪ aɪ help juː/', 'tôi có thể giúp gì cho bạn', 'Good morning, how may I help you?', 'Chào buổi sáng, tôi có thể giúp gì cho bạn?', 5),
  ('account', '/əˈkaʊnt/', 'tài khoản (n)', 'Could I have your account number?', 'Cho tôi xin số tài khoản của bạn?', 6),
  ('account manager', '/əˈkaʊnt ˈmænɪdʒə/', 'quản lý khách hàng (n)', 'Your account manager will call you.', 'Quản lý khách hàng sẽ gọi cho bạn.', 7),
  ('inquiry', '/ɪnˈkwaɪəri/', 'yêu cầu thông tin (n)', 'We received your inquiry.', 'Chúng tôi đã nhận yêu cầu của bạn.', 8),
  ('complaint', '/kəmˈpleɪnt/', 'khiếu nại (n)', 'We take every complaint seriously.', 'Chúng tôi xem trọng mọi khiếu nại.', 9),
  ('I understand your frustration', '/aɪ ˌʌndəˈstænd jɔː frʌˈstreɪʃn/', 'tôi hiểu sự bực bội của bạn', 'I understand your frustration, and I''m here to help.', 'Tôi hiểu bạn bực bội, và tôi ở đây để giúp.', 10),
  ('I apologize for the inconvenience', '/aɪ əˈpɒlədʒaɪz fɔː ði ˌɪnkənˈviːniəns/', 'xin lỗi vì sự bất tiện', 'I apologize for the inconvenience caused.', 'Tôi xin lỗi vì sự bất tiện đã gây ra.', 11),
  ('resolve', '/rɪˈzɒlv/', 'giải quyết (v)', 'We''ll resolve this today.', 'Chúng tôi sẽ giải quyết hôm nay.', 12),
  ('resolution', '/ˌrezəˈluːʃn/', 'cách giải quyết (n)', 'We aim for a quick resolution.', 'Chúng tôi hướng tới giải quyết nhanh.', 13),
  ('ticket', '/ˈtɪkɪt/', 'phiếu yêu cầu hỗ trợ (n)', 'I''ve opened a ticket for your issue.', 'Tôi đã mở phiếu hỗ trợ cho vấn đề của bạn.', 14),
  ('case number', '/keɪs ˈnʌmbə/', 'mã hồ sơ (n)', 'Please quote your case number.', 'Vui lòng cung cấp mã hồ sơ.', 15),
  ('escalation', '/ˌeskəˈleɪʃn/', 'chuyển lên cấp cao hơn (n)', 'This needs escalation to a manager.', 'Việc này cần chuyển lên quản lý.', 16),
  ('refund', '/ˈriːfʌnd/', 'hoàn tiền (n, v)', 'You''ll receive a full refund.', 'Bạn sẽ được hoàn tiền toàn bộ.', 17),
  ('replacement', '/rɪˈpleɪsmənt/', 'hàng thay thế (n)', 'We''ll send a replacement tomorrow.', 'Chúng tôi sẽ gửi hàng thay thế ngày mai.', 18),
  ('exchange', '/ɪksˈtʃeɪndʒ/', 'đổi hàng (v, n)', 'Can I exchange this for a larger size?', 'Tôi đổi cái này sang cỡ lớn hơn được không?', 19),
  ('warranty', '/ˈwɒrənti/', 'bảo hành (n)', 'The laptop has a two-year warranty.', 'Máy tính có bảo hành hai năm.', 20),
  ('return policy', '/rɪˈtɜːn ˈpɒləsi/', 'chính sách đổi trả (n)', 'Our return policy is 30 days.', 'Chính sách đổi trả là 30 ngày.', 21),
  ('compensation', '/ˌkɒmpenˈseɪʃn/', 'bồi thường (n)', 'We offered a voucher as compensation.', 'Chúng tôi tặng phiếu quà làm bồi thường.', 22),
  ('goodwill gesture', '/ˌɡʊdˈwɪl ˈdʒestʃə/', 'cử chỉ thiện chí (n)', 'As a goodwill gesture, shipping is free.', 'Để thể hiện thiện chí, miễn phí vận chuyển.', 23),
  ('satisfaction', '/ˌsætɪsˈfækʃn/', 'sự hài lòng (n)', 'Customer satisfaction is our goal.', 'Sự hài lòng của khách là mục tiêu.', 24),
  ('satisfied', '/ˈsætɪsfaɪd/', 'hài lòng (adj)', 'Are you satisfied with the solution?', 'Bạn hài lòng với giải pháp chứ?', 25),
  ('loyal customer', '/ˈlɔɪəl ˈkʌstəmə/', 'khách hàng trung thành (n)', 'Loyal customers get early access.', 'Khách trung thành được ưu tiên trước.', 26),
  ('loyalty program', '/ˈlɔɪəlti ˈprəʊɡræm/', 'chương trình khách hàng thân thiết (n)', 'Join our loyalty program for points.', 'Tham gia chương trình thân thiết để tích điểm.', 27),
  ('retention', '/rɪˈtenʃn/', 'giữ chân khách (n)', 'Retention improved after the update.', 'Tỷ lệ giữ chân khách tăng sau cập nhật.', 28),
  ('churn', '/tʃɜːn/', 'tỷ lệ rời bỏ (n)', 'Churn is high among new users.', 'Tỷ lệ rời bỏ cao ở người dùng mới.', 29),
  ('feedback survey', '/ˈfiːdbæk ˈsɜːveɪ/', 'khảo sát ý kiến (n)', 'Please complete the feedback survey.', 'Vui lòng hoàn thành khảo sát ý kiến.', 30),
  ('rating', '/ˈreɪtɪŋ/', 'đánh giá sao (n)', 'We got a five-star rating.', 'Chúng tôi nhận đánh giá năm sao.', 31),
  ('testimonial', '/ˌtestɪˈməʊniəl/', 'lời chứng thực của khách (n)', 'Add a testimonial to the website.', 'Thêm lời chứng thực lên website.', 32),
  ('referral', '/rɪˈfɜːrəl/', 'sự giới thiệu khách (n)', 'Most new clients come from referrals.', 'Hầu hết khách mới đến từ giới thiệu.', 33),
  ('word of mouth', '/wɜːd əv maʊθ/', 'truyền miệng', 'We grew by word of mouth.', 'Chúng tôi phát triển nhờ truyền miệng.', 34),
  ('prospect', '/ˈprɒspekt/', 'khách hàng tiềm năng (n)', 'We have ten prospects this week.', 'Tuần này có mười khách tiềm năng.', 35),
  ('lead', '/liːd/', 'đầu mối khách hàng (n)', 'Sales followed up on every lead.', 'Kinh doanh theo sát mọi đầu mối.', 36),
  ('pitch', '/pɪtʃ/', 'bài chào hàng (n); chào hàng (v)', 'Keep your pitch under two minutes.', 'Giữ bài chào hàng dưới hai phút.', 37),
  ('demo', '/ˈdeməʊ/', 'bản trình diễn thử (n)', 'Would you like a free demo?', 'Bạn muốn xem demo miễn phí không?', 38),
  ('quote', '/kwəʊt/', 'báo giá (n, v)', 'I''ll send a quote by Friday.', 'Tôi sẽ gửi báo giá trước thứ Sáu.', 39),
  ('sales proposal', '/seɪlz prəˈpəʊzl/', 'hồ sơ chào bán (n)', 'The client accepted our sales proposal.', 'Khách đã chấp nhận hồ sơ chào bán của chúng tôi.', 40),
  ('negotiate', '/nɪˈɡəʊʃieɪt/', 'đàm phán (v)', 'We negotiated a better price.', 'Chúng tôi đàm phán được giá tốt hơn.', 41),
  ('discount', '/ˈdɪskaʊnt/', 'giảm giá (n)', 'We can offer a 10% discount.', 'Chúng tôi có thể giảm 10%.', 42),
  ('close a deal', '/kləʊz ə diːl/', 'chốt hợp đồng', 'We closed the deal yesterday.', 'Chúng tôi chốt hợp đồng hôm qua.', 43),
  ('upsell', '/ˈʌpsel/', 'bán gói cao hơn (v)', 'Try to upsell the premium plan.', 'Thử bán thêm gói cao cấp.', 44),
  ('cross-sell', '/ˈkrɒs sel/', 'bán chéo (v)', 'We cross-sell accessories at checkout.', 'Chúng tôi bán chéo phụ kiện lúc thanh toán.', 45),
  ('subscription', '/səbˈskrɪpʃn/', 'gói đăng ký (n)', 'Your subscription renews monthly.', 'Gói đăng ký gia hạn hằng tháng.', 46),
  ('renewal', '/rɪˈnjuːəl/', 'gia hạn (n)', 'The renewal is due next month.', 'Gia hạn đến hạn vào tháng sau.', 47),
  ('cancel', '/ˈkænsl/', 'huỷ (v)', 'I''d like to cancel my order.', 'Tôi muốn huỷ đơn hàng.', 48),
  ('order status', '/ˈɔːdə ˈsteɪtəs/', 'tình trạng đơn hàng (n)', 'Check your order status online.', 'Kiểm tra tình trạng đơn hàng trực tuyến.', 49),
  ('tracking number', '/ˈtrækɪŋ ˈnʌmbə/', 'mã vận đơn (n)', 'Here is your tracking number.', 'Đây là mã vận đơn của bạn.', 50),
  ('delivery', '/dɪˈlɪvəri/', 'giao hàng (n)', 'Delivery takes three days.', 'Giao hàng mất ba ngày.', 51),
  ('damaged', '/ˈdæmɪdʒd/', 'bị hư hỏng (adj)', 'The package arrived damaged.', 'Gói hàng đến nơi bị hư hỏng.', 52),
  ('defective', '/dɪˈfektɪv/', 'bị lỗi (adj)', 'The product is defective.', 'Sản phẩm bị lỗi.', 53),
  ('invoice', '/ˈɪnvɔɪs/', 'hoá đơn (n)', 'The invoice is attached.', 'Hoá đơn được đính kèm.', 54),
  ('billing', '/ˈbɪlɪŋ/', 'thanh toán, tính phí (n)', 'I have a billing question.', 'Tôi có câu hỏi về thanh toán.', 55),
  ('overcharge', '/ˌəʊvəˈtʃɑːdʒ/', 'tính phí quá cao (v)', 'I think I was overcharged.', 'Tôi nghĩ tôi bị tính phí thừa.', 56),
  ('payment method', '/ˈpeɪmənt ˈmeθəd/', 'phương thức thanh toán (n)', 'Update your payment method.', 'Cập nhật phương thức thanh toán.', 57),
  ('verify', '/ˈverɪfaɪ/', 'xác minh (v)', 'Let me verify your identity.', 'Để tôi xác minh danh tính của bạn.', 58),
  ('privacy', '/ˈprɪvəsi/', 'quyền riêng tư (n)', 'We respect your privacy.', 'Chúng tôi tôn trọng quyền riêng tư của bạn.', 59),
  ('terms and conditions', '/tɜːmz ənd kənˈdɪʃnz/', 'điều khoản và điều kiện', 'Please read the terms and conditions.', 'Vui lòng đọc điều khoản và điều kiện.', 60),
  ('FAQ', '/ˌef eɪ ˈkjuː/', 'câu hỏi thường gặp (n)', 'Check the FAQ page first.', 'Xem trang câu hỏi thường gặp trước.', 61),
  ('help desk', '/help desk/', 'bàn hỗ trợ (n)', 'The help desk is open 24/7.', 'Bàn hỗ trợ mở 24/7.', 62),
  ('live chat', '/laɪv tʃæt/', 'chat trực tuyến (n)', 'Use live chat for quick answers.', 'Dùng chat trực tuyến để được trả lời nhanh.', 63),
  ('hotline', '/ˈhɒtlaɪn/', 'đường dây nóng (n)', 'Call our hotline anytime.', 'Gọi đường dây nóng bất cứ lúc nào.', 64),
  ('on hold', '/ɒn həʊld/', 'đang chờ máy', 'I was on hold for twenty minutes.', 'Tôi chờ máy hai mươi phút.', 65),
  ('transfer', '/trænsˈfɜː/', 'chuyển máy (v)', 'I''ll transfer you to billing.', 'Tôi chuyển bạn sang bộ phận thanh toán.', 66),
  ('response time', '/rɪˈspɒns taɪm/', 'thời gian phản hồi (n)', 'Our average response time is one hour.', 'Thời gian phản hồi trung bình là một giờ.', 67),
  ('first-call resolution', '/fɜːst kɔːl ˌrezəˈluːʃn/', 'giải quyết ngay cuộc gọi đầu (n)', 'We aim for first-call resolution.', 'Chúng tôi hướng tới giải quyết ngay cuộc gọi đầu.', 68),
  ('empathy', '/ˈempəθi/', 'sự đồng cảm (n)', 'Show empathy when customers are upset.', 'Thể hiện đồng cảm khi khách bực bội.', 69),
  ('patient', '/ˈpeɪʃnt/', 'kiên nhẫn (adj)', 'Stay patient with angry callers.', 'Giữ kiên nhẫn với người gọi tức giận.', 70),
  ('polite', '/pəˈlaɪt/', 'lịch sự (adj)', 'Always be polite, even when it''s hard.', 'Luôn lịch sự, kể cả khi khó khăn.', 71),
  ('active listening', '/ˈæktɪv ˈlɪsnɪŋ/', 'lắng nghe chủ động (n)', 'Active listening builds trust.', 'Lắng nghe chủ động tạo niềm tin.', 72),
  ('reassure', '/ˌriːəˈʃʊə/', 'trấn an (v)', 'Reassure the customer that it''s being fixed.', 'Trấn an khách rằng việc đang được xử lý.', 73),
  ('rest assured', '/rest əˈʃʊəd/', 'hãy yên tâm', 'Rest assured, we''ll handle it.', 'Hãy yên tâm, chúng tôi sẽ xử lý.', 74),
  ('expectation', '/ˌekspekˈteɪʃn/', 'kỳ vọng (n)', 'Set clear expectations early.', 'Đặt kỳ vọng rõ ràng từ sớm.', 75),
  ('exceed expectations', '/ɪkˈsiːd ˌekspekˈteɪʃnz/', 'vượt kỳ vọng', 'The team exceeded expectations.', 'Nhóm đã vượt kỳ vọng.', 76),
  ('go the extra mile', '/ɡəʊ ði ˈekstrə maɪl/', 'nỗ lực hơn mức yêu cầu', 'Our staff go the extra mile.', 'Nhân viên chúng tôi luôn nỗ lực hơn mong đợi.', 77),
  ('relationship', '/rɪˈleɪʃnʃɪp/', 'mối quan hệ (n)', 'Build long-term client relationships.', 'Xây dựng quan hệ khách hàng lâu dài.', 78),
  ('rapport', '/ræˈpɔː/', 'sự thân thiết, gắn kết (n)', 'Build rapport before pitching.', 'Tạo gắn kết trước khi chào hàng.', 79),
  ('trust', '/trʌst/', 'niềm tin (n)', 'Trust takes time to earn.', 'Niềm tin cần thời gian để có được.', 80),
  ('follow-up call', '/ˈfɒləʊ ʌp kɔːl/', 'cuộc gọi theo dõi (n)', 'Schedule a follow-up call next week.', 'Lên lịch gọi theo dõi tuần sau.', 81),
  ('check in', '/tʃek ɪn/', 'hỏi thăm tình hình', 'I''m just checking in to see how things are.', 'Tôi hỏi thăm xem mọi việc thế nào.', 82),
  ('onboarding', '/ˈɒnbɔːdɪŋ/', 'hướng dẫn khách mới (n)', 'Onboarding takes about a week.', 'Hướng dẫn khách mới mất khoảng một tuần.', 83),
  ('user guide', '/ˈjuːzə ɡaɪd/', 'hướng dẫn sử dụng (n)', 'The user guide is on our website.', 'Hướng dẫn sử dụng có trên website.', 84),
  ('troubleshoot', '/ˈtrʌblʃuːt/', 'khắc phục sự cố (v)', 'Let''s troubleshoot the connection.', 'Cùng khắc phục sự cố kết nối.', 85),
  ('workaround', '/ˈwɜːkəraʊnd/', 'cách xử lý tạm (n)', 'Here''s a workaround until the fix.', 'Đây là cách xử lý tạm cho đến khi sửa xong.', 86),
  ('known issue', '/nəʊn ˈɪʃuː/', 'lỗi đã biết (n)', 'That''s a known issue; a fix is coming.', 'Đó là lỗi đã biết; bản sửa sắp có.', 87),
  ('outage', '/ˈaʊtɪdʒ/', 'sự cố ngừng dịch vụ (n)', 'We had a two-hour outage.', 'Dịch vụ bị gián đoạn hai giờ.', 88),
  ('service level agreement', '/ˈsɜːvɪs ˈlevl əˈɡriːmənt/', 'thoả thuận mức dịch vụ (SLA) (n)', 'The service level agreement guarantees 99.9% uptime.', 'SLA cam kết 99,9% thời gian hoạt động.', 89),
  ('key account', '/kiː əˈkaʊnt/', 'khách hàng trọng yếu (n)', 'This is a key account for us.', 'Đây là khách hàng trọng yếu của chúng tôi.', 90),
  ('B2B', '/ˌbiː tə ˈbiː/', 'doanh nghiệp với doanh nghiệp', 'We mainly sell B2B.', 'Chúng tôi chủ yếu bán B2B.', 91),
  ('B2C', '/ˌbiː tə ˈsiː/', 'doanh nghiệp với người tiêu dùng', 'The app targets the B2C market.', 'Ứng dụng nhắm đến thị trường B2C.', 92),
  ('target audience', '/ˈtɑːɡɪt ˈɔːdiəns/', 'đối tượng mục tiêu (n)', 'Our target audience is young professionals.', 'Đối tượng mục tiêu là người trẻ đi làm.', 93),
  ('customer journey', '/ˈkʌstəmə ˈdʒɜːni/', 'hành trình khách hàng (n)', 'Map the customer journey.', 'Vẽ sơ đồ hành trình khách hàng.', 94),
  ('touchpoint', '/ˈtʌtʃpɔɪnt/', 'điểm chạm (n)', 'Every touchpoint should feel consistent.', 'Mọi điểm chạm nên nhất quán.', 95),
  ('pain point', '/peɪn pɔɪnt/', 'nỗi đau, vấn đề của khách (n)', 'Slow checkout is a major pain point.', 'Thanh toán chậm là vấn đề lớn.', 96),
  ('value proposition', '/ˈvæljuː ˌprɒpəˈzɪʃn/', 'tuyên bố giá trị (n)', 'State your value proposition clearly.', 'Nêu rõ tuyên bố giá trị của bạn.', 97),
  ('is there anything else', '/ɪz ðeər ˈeniθɪŋ els/', 'còn gì khác nữa không', 'Is there anything else I can help with?', 'Tôi có thể giúp gì thêm không?', 98),
  ('thank you for calling', '/θæŋk juː fɔː ˈkɔːlɪŋ/', 'cảm ơn bạn đã gọi', 'Thank you for calling, have a nice day.', 'Cảm ơn bạn đã gọi, chúc một ngày tốt lành.', 99),
  ('customer retention rate', '/ˈkʌstəmə rɪˈtenʃn reɪt/', 'tỷ lệ giữ chân khách (n)', 'Our customer retention rate is 85%.', 'Tỷ lệ giữ chân khách của chúng tôi là 85%.', 100)
) as w(term, phonetic, meaning_vi, example_en, example_vi, position) on true
where d.slug = 'cong-viec-khach-hang'
on conflict (deck_id, term) do nothing;

-- Khởi nghiệp & tài chính (100 từ)
insert into public.decks (slug, name, description, level, category, position)
values ('cong-viec-khoi-nghiep', 'Khởi nghiệp & tài chính', 'Gọi vốn, doanh thu, chiến lược, thị trường', 'advanced', 'cong-viec', 50)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, level = excluded.level,
  category = excluded.category, position = excluded.position;

insert into public.words (deck_id, term, phonetic, meaning_vi, example_en, example_vi, position)
select d.id, w.term, w.phonetic, w.meaning_vi, w.example_en, w.example_vi, w.position
from public.decks d
join (values
  ('startup', '/ˈstɑːtʌp/', 'công ty khởi nghiệp (n)', 'She joined a fintech startup.', 'Cô ấy gia nhập một startup fintech.', 1),
  ('founder', '/ˈfaʊndə/', 'nhà sáng lập (n)', 'The founder started the company at 22.', 'Nhà sáng lập lập công ty năm 22 tuổi.', 2),
  ('co-founder', '/ˌkəʊ ˈfaʊndə/', 'đồng sáng lập (n)', 'My co-founder handles engineering.', 'Đồng sáng lập của tôi phụ trách kỹ thuật.', 3),
  ('entrepreneur', '/ˌɒntrəprəˈnɜː/', 'doanh nhân khởi nghiệp (n)', 'Entrepreneurs take calculated risks.', 'Doanh nhân chấp nhận rủi ro có tính toán.', 4),
  ('venture', '/ˈventʃə/', 'dự án kinh doanh mạo hiểm (n)', 'His new venture sells solar lamps.', 'Dự án mới của anh ấy bán đèn năng lượng mặt trời.', 5),
  ('business model', '/ˈbɪznəs ˈmɒdl/', 'mô hình kinh doanh (n)', 'Our business model is subscription-based.', 'Mô hình kinh doanh dựa trên đăng ký.', 6),
  ('business plan', '/ˈbɪznəs plæn/', 'kế hoạch kinh doanh (n)', 'Investors asked for a business plan.', 'Nhà đầu tư yêu cầu kế hoạch kinh doanh.', 7),
  ('idea validation', '/aɪˈdɪə ˌvælɪˈdeɪʃn/', 'kiểm chứng ý tưởng (n)', 'Idea validation comes before building.', 'Kiểm chứng ý tưởng trước khi xây dựng.', 8),
  ('market research', '/ˈmɑːkɪt rɪˈsɜːtʃ/', 'nghiên cứu thị trường (n)', 'Market research showed strong demand.', 'Nghiên cứu thị trường cho thấy nhu cầu mạnh.', 9),
  ('target market', '/ˈtɑːɡɪt ˈmɑːkɪt/', 'thị trường mục tiêu (n)', 'Our target market is small cafés.', 'Thị trường mục tiêu là quán cà phê nhỏ.', 10),
  ('niche', '/niːʃ/', 'thị trường ngách (n)', 'We found a profitable niche.', 'Chúng tôi tìm được ngách sinh lời.', 11),
  ('product-market fit', '/ˈprɒdʌkt ˈmɑːkɪt fɪt/', 'sự phù hợp sản phẩm–thị trường (n)', 'We reached product-market fit last year.', 'Chúng tôi đạt product-market fit năm ngoái.', 12),
  ('minimum viable product', '/ˈmɪnɪməm ˈvaɪəbl ˈprɒdʌkt/', 'sản phẩm khả dụng tối thiểu (MVP) (n)', 'Launch a minimum viable product first.', 'Ra mắt sản phẩm khả dụng tối thiểu trước.', 13),
  ('proof of concept', '/pruːf əv ˈkɒnsept/', 'bản chứng minh khái niệm (n)', 'We built a proof of concept in two weeks.', 'Chúng tôi làm bản chứng minh khái niệm trong hai tuần.', 14),
  ('beta', '/ˈbiːtə/', 'bản thử nghiệm (n)', 'The app is still in beta.', 'Ứng dụng vẫn đang ở bản thử nghiệm.', 15),
  ('early adopter', '/ˈɜːli əˈdɒptə/', 'người dùng tiên phong (n)', 'Early adopters gave great feedback.', 'Người dùng tiên phong góp ý rất hữu ích.', 16),
  ('traction', '/ˈtrækʃn/', 'sức hút, đà tăng trưởng (n)', 'We''re gaining traction in Asia.', 'Chúng tôi đang có đà tăng trưởng ở châu Á.', 17),
  ('growth', '/ɡrəʊθ/', 'tăng trưởng (n)', 'Monthly growth is 15%.', 'Tăng trưởng hằng tháng là 15%.', 18),
  ('scale', '/skeɪl/', 'mở rộng quy mô (v)', 'Can the business scale?', 'Doanh nghiệp có thể mở rộng quy mô không?', 19),
  ('scalable', '/ˈskeɪləbl/', 'có thể mở rộng (adj)', 'Software businesses are highly scalable.', 'Doanh nghiệp phần mềm rất dễ mở rộng.', 20),
  ('pivot', '/ˈpɪvət/', 'xoay trục, đổi hướng (v, n)', 'We pivoted from B2C to B2B.', 'Chúng tôi đổi hướng từ B2C sang B2B.', 21),
  ('bootstrap', '/ˈbuːtstræp/', 'tự lực bằng vốn riêng (v)', 'We bootstrapped for two years.', 'Chúng tôi tự lực vốn hai năm.', 22),
  ('funding', '/ˈfʌndɪŋ/', 'vốn tài trợ (n)', 'We need funding to hire.', 'Chúng tôi cần vốn để tuyển người.', 23),
  ('raise capital', '/reɪz ˈkæpɪtl/', 'gọi vốn', 'They raised capital from three funds.', 'Họ gọi vốn từ ba quỹ.', 24),
  ('investor', '/ɪnˈvestə/', 'nhà đầu tư (n)', 'An investor offered $500k.', 'Một nhà đầu tư đề nghị 500k đô.', 25),
  ('angel investor', '/ˈeɪndʒl ɪnˈvestə/', 'nhà đầu tư thiên thần (n)', 'An angel investor funded our first year.', 'Nhà đầu tư thiên thần tài trợ năm đầu.', 26),
  ('venture capital', '/ˈventʃə ˈkæpɪtl/', 'vốn đầu tư mạo hiểm (n)', 'Venture capital fuels fast growth.', 'Vốn mạo hiểm thúc đẩy tăng trưởng nhanh.', 27),
  ('seed round', '/siːd raʊnd/', 'vòng gọi vốn hạt giống (n)', 'We closed a $1M seed round.', 'Chúng tôi chốt vòng hạt giống 1 triệu đô.', 28),
  ('Series A', '/ˈsɪəriːz eɪ/', 'vòng gọi vốn Series A (n)', 'The Series A valued us at $20M.', 'Vòng Series A định giá chúng tôi 20 triệu đô.', 29),
  ('valuation', '/ˌvæljuˈeɪʃn/', 'định giá (n)', 'The valuation doubled in a year.', 'Định giá tăng gấp đôi trong một năm.', 30),
  ('equity', '/ˈekwəti/', 'cổ phần (n)', 'Early employees receive equity.', 'Nhân viên đầu tiên nhận cổ phần.', 31),
  ('stake', '/steɪk/', 'phần sở hữu (n)', 'The fund took a 10% stake.', 'Quỹ nắm 10% cổ phần.', 32),
  ('dilution', '/daɪˈluːʃn/', 'pha loãng cổ phần (n)', 'Each round causes dilution.', 'Mỗi vòng gọi vốn gây pha loãng.', 33),
  ('cap table', '/kæp ˈteɪbl/', 'bảng vốn hoá (n)', 'Keep the cap table clean.', 'Giữ bảng vốn hoá gọn gàng.', 34),
  ('term sheet', '/tɜːm ʃiːt/', 'bản điều khoản đầu tư (n)', 'We received a term sheet yesterday.', 'Chúng tôi nhận bản điều khoản hôm qua.', 35),
  ('due diligence', '/djuː ˈdɪlɪdʒəns/', 'thẩm định (n)', 'Due diligence took six weeks.', 'Thẩm định mất sáu tuần.', 36),
  ('pitch deck', '/pɪtʃ dek/', 'bộ slide gọi vốn (n)', 'Keep the pitch deck to 12 slides.', 'Giữ pitch deck trong 12 slide.', 37),
  ('elevator pitch', '/ˈelɪveɪtə pɪtʃ/', 'bài giới thiệu 30 giây (n)', 'Prepare a 30-second elevator pitch.', 'Chuẩn bị bài giới thiệu 30 giây.', 38),
  ('runway', '/ˈrʌnweɪ/', 'thời gian còn tiền hoạt động (n)', 'We have nine months of runway.', 'Chúng tôi còn chín tháng runway.', 39),
  ('burn rate', '/bɜːn reɪt/', 'tốc độ đốt tiền (n)', 'Our burn rate is $40k a month.', 'Tốc độ đốt tiền là 40k đô/tháng.', 40),
  ('cash flow', '/kæʃ fləʊ/', 'dòng tiền (n)', 'Cash flow turned positive in Q3.', 'Dòng tiền dương từ quý 3.', 41),
  ('break even', '/breɪk ˈiːvn/', 'hoà vốn', 'We expect to break even next year.', 'Dự kiến hoà vốn năm sau.', 42),
  ('profitable', '/ˈprɒfɪtəbl/', 'có lãi (adj)', 'The company is finally profitable.', 'Công ty cuối cùng đã có lãi.', 43),
  ('revenue', '/ˈrevənjuː/', 'doanh thu (n)', 'Revenue tripled this year.', 'Doanh thu tăng gấp ba năm nay.', 44),
  ('recurring revenue', '/rɪˈkɜːrɪŋ ˈrevənjuː/', 'doanh thu định kỳ (n)', 'Investors love recurring revenue.', 'Nhà đầu tư thích doanh thu định kỳ.', 45),
  ('margin', '/ˈmɑːdʒɪn/', 'biên lợi nhuận (n)', 'Software has high margins.', 'Phần mềm có biên lợi nhuận cao.', 46),
  ('unit economics', '/ˈjuːnɪt ˌiːkəˈnɒmɪks/', 'kinh tế đơn vị (n)', 'Fix the unit economics before scaling.', 'Tối ưu kinh tế đơn vị trước khi mở rộng.', 47),
  ('customer acquisition cost', '/ˈkʌstəmər ˌækwɪˈzɪʃn kɒst/', 'chi phí thu hút khách (CAC) (n)', 'Customer acquisition cost is $12.', 'Chi phí thu hút khách là 12 đô.', 48),
  ('lifetime value', '/ˈlaɪftaɪm ˈvæljuː/', 'giá trị vòng đời khách (LTV) (n)', 'Lifetime value should exceed CAC.', 'Giá trị vòng đời nên cao hơn CAC.', 49),
  ('monetize', '/ˈmʌnɪtaɪz/', 'kiếm tiền từ (v)', 'How will you monetize the app?', 'Bạn sẽ kiếm tiền từ ứng dụng thế nào?', 50),
  ('pricing', '/ˈpraɪsɪŋ/', 'định giá bán (n)', 'We tested three pricing tiers.', 'Chúng tôi thử ba mức giá.', 51),
  ('freemium', '/ˈfriːmiəm/', 'miễn phí cơ bản, trả phí nâng cao (adj)', 'We use a freemium model.', 'Chúng tôi dùng mô hình freemium.', 52),
  ('go-to-market', '/ˌɡəʊ tə ˈmɑːkɪt/', 'chiến lược đưa sản phẩm ra thị trường', 'Our go-to-market plan focuses on Vietnam.', 'Kế hoạch ra thị trường tập trung vào Việt Nam.', 53),
  ('competitor', '/kəmˈpetɪtə/', 'đối thủ cạnh tranh (n)', 'Study your competitors closely.', 'Nghiên cứu kỹ đối thủ cạnh tranh.', 54),
  ('competitive advantage', '/kəmˈpetətɪv ədˈvɑːntɪdʒ/', 'lợi thế cạnh tranh (n)', 'Speed is our competitive advantage.', 'Tốc độ là lợi thế cạnh tranh của chúng tôi.', 55),
  ('differentiate', '/ˌdɪfəˈrenʃieɪt/', 'tạo sự khác biệt (v)', 'We differentiate through design.', 'Chúng tôi khác biệt nhờ thiết kế.', 56),
  ('disrupt', '/dɪsˈrʌpt/', 'gây đột phá, phá vỡ (v)', 'The app disrupted the taxi industry.', 'Ứng dụng đã phá vỡ ngành taxi.', 57),
  ('innovation', '/ˌɪnəˈveɪʃn/', 'sự đổi mới (n)', 'Innovation keeps us ahead.', 'Đổi mới giúp chúng tôi dẫn đầu.', 58),
  ('lean', '/liːn/', 'tinh gọn (adj)', 'Stay lean until revenue grows.', 'Giữ tinh gọn cho đến khi doanh thu tăng.', 59),
  ('iterate', '/ˈɪtəreɪt/', 'lặp lại cải tiến (v)', 'Build, measure, iterate.', 'Xây dựng, đo lường, cải tiến.', 60),
  ('fail fast', '/feɪl fɑːst/', 'thất bại nhanh để học nhanh', 'Fail fast and learn quickly.', 'Thất bại nhanh và học nhanh.', 61),
  ('hypothesis', '/haɪˈpɒθəsɪs/', 'giả thuyết (n)', 'Test one hypothesis at a time.', 'Kiểm chứng từng giả thuyết một.', 62),
  ('A/B testing', '/ˌeɪ ˈbiː ˈtestɪŋ/', 'thử nghiệm A/B (n)', 'A/B testing improved sign-ups by 20%.', 'Thử nghiệm A/B tăng 20% lượt đăng ký.', 63),
  ('conversion rate', '/kənˈvɜːʃn reɪt/', 'tỷ lệ chuyển đổi (n)', 'Our conversion rate is 3%.', 'Tỷ lệ chuyển đổi là 3%.', 64),
  ('user base', '/ˈjuːzə beɪs/', 'tập người dùng (n)', 'The user base passed one million.', 'Tập người dùng vượt một triệu.', 65),
  ('active users', '/ˈæktɪv ˈjuːzəz/', 'người dùng hoạt động', 'We track daily active users.', 'Chúng tôi theo dõi người dùng hoạt động hằng ngày.', 66),
  ('engagement', '/ɪnˈɡeɪdʒmənt/', 'mức độ tương tác (n)', 'Engagement dropped after the redesign.', 'Tương tác giảm sau khi thiết kế lại.', 67),
  ('viral', '/ˈvaɪrəl/', 'lan truyền mạnh (adj)', 'The video went viral.', 'Video đã lan truyền mạnh.', 68),
  ('brand', '/brænd/', 'thương hiệu (n)', 'Build a brand people trust.', 'Xây thương hiệu được tin cậy.', 69),
  ('launch event', '/lɔːntʃ ɪˈvent/', 'sự kiện ra mắt (n)', 'The launch event drew 300 people.', 'Sự kiện ra mắt thu hút 300 người.', 70),
  ('incubator', '/ˈɪŋkjubeɪtə/', 'vườn ươm khởi nghiệp (n)', 'We joined a university incubator.', 'Chúng tôi tham gia vườn ươm của trường.', 71),
  ('accelerator', '/əkˈseləreɪtə/', 'chương trình tăng tốc (n)', 'The accelerator gave us mentors and cash.', 'Chương trình tăng tốc cho chúng tôi cố vấn và tiền.', 72),
  ('mentor', '/ˈmentɔː/', 'người cố vấn (n)', 'Find a mentor who has done it before.', 'Tìm cố vấn đã từng làm việc đó.', 73),
  ('networking', '/ˈnetwɜːkɪŋ/', 'xây dựng quan hệ (n)', 'Networking led to our first client.', 'Kết nối quan hệ mang lại khách hàng đầu tiên.', 74),
  ('co-working space', '/ˈkəʊ ˈwɜːkɪŋ speɪs/', 'không gian làm việc chung (n)', 'We rent desks in a co-working space.', 'Chúng tôi thuê bàn ở không gian làm việc chung.', 75),
  ('hire', '/ˈhaɪə/', 'tuyển dụng (v)', 'We hired our first engineer.', 'Chúng tôi tuyển kỹ sư đầu tiên.', 76),
  ('talent', '/ˈtælənt/', 'nhân tài (n)', 'Top talent is hard to attract.', 'Nhân tài giỏi khó thu hút.', 77),
  ('stock option', '/stɒk ˈɒpʃn/', 'quyền chọn cổ phiếu (n)', 'Stock options motivate early staff.', 'Quyền chọn cổ phiếu khích lệ nhân viên đầu.', 78),
  ('culture', '/ˈkʌltʃə/', 'văn hoá công ty (n)', 'Culture matters as the team grows.', 'Văn hoá quan trọng khi nhóm lớn lên.', 79),
  ('mission', '/ˈmɪʃn/', 'sứ mệnh (n)', 'Our mission is to make learning fun.', 'Sứ mệnh của chúng tôi là làm việc học vui hơn.', 80),
  ('vision', '/ˈvɪʒn/', 'tầm nhìn (n)', 'Share your vision with the team.', 'Chia sẻ tầm nhìn với đội ngũ.', 81),
  ('intellectual property', '/ˌɪntəˈlektʃuəl ˈprɒpəti/', 'sở hữu trí tuệ (n)', 'Protect your intellectual property.', 'Bảo vệ sở hữu trí tuệ của bạn.', 82),
  ('patent', '/ˈpætnt/', 'bằng sáng chế (n)', 'We filed a patent for the sensor.', 'Chúng tôi nộp bằng sáng chế cho cảm biến.', 83),
  ('trademark', '/ˈtreɪdmɑːk/', 'nhãn hiệu (n)', 'Register the name as a trademark.', 'Đăng ký tên làm nhãn hiệu.', 84),
  ('incorporate', '/ɪnˈkɔːpəreɪt/', 'thành lập công ty (v)', 'We incorporated in Singapore.', 'Chúng tôi thành lập công ty ở Singapore.', 85),
  ('license', '/ˈlaɪsns/', 'giấy phép (n)', 'You need a license to operate.', 'Bạn cần giấy phép để hoạt động.', 86),
  ('regulation', '/ˌreɡjuˈleɪʃn/', 'quy định (n)', 'Fintech faces strict regulation.', 'Fintech chịu quy định nghiêm ngặt.', 87),
  ('partnership', '/ˈpɑːtnəʃɪp/', 'quan hệ đối tác (n)', 'We signed a partnership with a bank.', 'Chúng tôi ký hợp tác với một ngân hàng.', 88),
  ('exit', '/ˈeksɪt/', 'thoái vốn (n)', 'Investors expect an exit in five years.', 'Nhà đầu tư kỳ vọng thoái vốn trong năm năm.', 89),
  ('acquisition', '/ˌækwɪˈzɪʃn/', 'thương vụ mua lại (n)', 'The acquisition was worth $50M.', 'Thương vụ mua lại trị giá 50 triệu đô.', 90),
  ('IPO', '/ˌaɪ piː ˈəʊ/', 'phát hành cổ phiếu lần đầu (n)', 'The company plans an IPO next year.', 'Công ty dự định IPO năm sau.', 91),
  ('unicorn', '/ˈjuːnɪkɔːn/', 'kỳ lân (startup tỷ đô) (n)', 'Vietnam has a few unicorns now.', 'Việt Nam giờ đã có vài kỳ lân.', 92),
  ('sustainable', '/səˈsteɪnəbl/', 'bền vững (adj)', 'Build a sustainable business, not a hype.', 'Xây doanh nghiệp bền vững, không phải trào lưu.', 93),
  ('milestone-based', '/ˈmaɪlstəʊn beɪst/', 'theo cột mốc (adj)', 'Funding is milestone-based.', 'Vốn giải ngân theo cột mốc.', 94),
  ('forecast', '/ˈfɔːkɑːst/', 'dự báo (n, v)', 'Our forecast shows profit by 2027.', 'Dự báo cho thấy có lãi vào 2027.', 95),
  ('risk-taking', '/ˈrɪsk ˌteɪkɪŋ/', 'chấp nhận rủi ro (n)', 'Smart risk-taking is essential.', 'Chấp nhận rủi ro khôn ngoan là cần thiết.', 96),
  ('resilience', '/rɪˈzɪliəns/', 'sức bền, khả năng phục hồi (n)', 'Founders need resilience.', 'Nhà sáng lập cần sức bền.', 97),
  ('side hustle', '/saɪd ˈhʌsl/', 'việc làm thêm kiếm tiền (n)', 'It started as a side hustle.', 'Nó bắt đầu như một việc làm thêm.', 98),
  ('crowdfunding', '/ˈkraʊdfʌndɪŋ/', 'gọi vốn cộng đồng (n)', 'We raised $80k through crowdfunding.', 'Chúng tôi gọi được 80k đô từ cộng đồng.', 99),
  ('grant', '/ɡrɑːnt/', 'khoản tài trợ không hoàn lại (n)', 'We won a government grant.', 'Chúng tôi nhận tài trợ của chính phủ.', 100)
) as w(term, phonetic, meaning_vi, example_en, example_vi, position) on true
where d.slug = 'cong-viec-khoi-nghiep'
on conflict (deck_id, term) do nothing;
