-- DailyEng — seed nhóm "giao-tiep". SINH TỰ ĐỘNG bởi scripts/generate-decks.mts, đừng sửa tay.
-- Chạy SAU schema-07-nhom-bo-tu.sql. Chạy lại nhiều lần được: bộ đã có thì cập nhật tên/mô tả,
-- từ đã có (deck_id, term) thì giữ nguyên để không mất tiến độ học của người dùng.

-- Chào hỏi & giới thiệu (80 từ)
insert into public.decks (slug, name, description, level, category, position)
values ('giao-tiep-chao-hoi', 'Chào hỏi & giới thiệu', 'Làm quen, giới thiệu bản thân, phép lịch sự', 'beginner', 'giao-tiep', 10)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, level = excluded.level,
  category = excluded.category, position = excluded.position;

insert into public.words (deck_id, term, phonetic, meaning_vi, example_en, example_vi, position)
select d.id, w.term, w.phonetic, w.meaning_vi, w.example_en, w.example_vi, w.position
from public.decks d
join (values
  ('hi', '/haɪ/', 'chào (thân mật)', 'Hi, I''m Minh.', 'Chào, mình là Minh.', 1),
  ('good morning', '/ɡʊd ˈmɔːnɪŋ/', 'chào buổi sáng', 'Good morning, everyone!', 'Chào buổi sáng mọi người!', 2),
  ('good afternoon', '/ɡʊd ˌɑːftəˈnuːn/', 'chào buổi chiều', 'Good afternoon, Mr. Lee.', 'Chào buổi chiều, ông Lee.', 3),
  ('good evening', '/ɡʊd ˈiːvnɪŋ/', 'chào buổi tối', 'Good evening, welcome to our restaurant.', 'Chào buổi tối, chào mừng đến nhà hàng.', 4),
  ('goodbye', '/ˌɡʊdˈbaɪ/', 'tạm biệt', 'Goodbye, see you next week.', 'Tạm biệt, hẹn gặp tuần sau.', 5),
  ('bye', '/baɪ/', 'chào tạm biệt (thân mật)', 'Bye! Take care.', 'Chào nhé! Giữ sức khoẻ.', 6),
  ('see you later', '/siː juː ˈleɪtə/', 'hẹn gặp lại', 'See you later, I''m off to work.', 'Gặp lại sau nhé, tôi đi làm đây.', 7),
  ('take care', '/teɪk keə/', 'giữ gìn sức khoẻ', 'Take care and call me when you land.', 'Giữ gìn sức khoẻ và gọi tôi khi hạ cánh.', 8),
  ('nice to meet you', '/naɪs tuː miːt juː/', 'rất vui được gặp bạn', 'Nice to meet you, Anna.', 'Rất vui được gặp bạn, Anna.', 9),
  ('how are you', '/haʊ ɑː juː/', 'bạn khoẻ không', 'Hi Tom, how are you?', 'Chào Tom, bạn khoẻ không?', 10),
  ('how''s it going', '/haʊz ɪt ˈɡəʊɪŋ/', 'dạo này thế nào (thân mật)', 'Hey, how''s it going?', 'Ê, dạo này sao rồi?', 11),
  ('I''m fine, thanks', '/aɪm faɪn θæŋks/', 'tôi khoẻ, cảm ơn', 'I''m fine, thanks. And you?', 'Tôi khoẻ, cảm ơn. Còn bạn?', 12),
  ('not bad', '/nɒt bæd/', 'cũng ổn', 'How''s work? — Not bad.', 'Công việc sao rồi? — Cũng ổn.', 13),
  ('what''s your name', '/wɒts jɔː neɪm/', 'bạn tên gì', 'Hello, what''s your name?', 'Xin chào, bạn tên gì?', 14),
  ('my name is', '/maɪ neɪm ɪz/', 'tôi tên là', 'My name is Lan Anh.', 'Tôi tên là Lan Anh.', 15),
  ('introduce', '/ˌɪntrəˈdjuːs/', 'giới thiệu (v)', 'Let me introduce myself.', 'Cho phép tôi tự giới thiệu.', 16),
  ('nickname', '/ˈnɪkneɪm/', 'biệt danh (n)', 'My nickname is Bin.', 'Biệt danh của tôi là Bin.', 17),
  ('spell', '/spel/', 'đánh vần (v)', 'How do you spell your name?', 'Tên bạn đánh vần thế nào?', 18),
  ('where are you from', '/weər ɑː juː frɒm/', 'bạn đến từ đâu', 'Where are you from? — Vietnam.', 'Bạn đến từ đâu? — Việt Nam.', 19),
  ('hometown', '/ˈhəʊmtaʊn/', 'quê nhà (n)', 'My hometown is Can Tho.', 'Quê tôi ở Cần Thơ.', 20),
  ('nationality', '/ˌnæʃəˈnæləti/', 'quốc tịch (n)', 'What is your nationality?', 'Quốc tịch của bạn là gì?', 21),
  ('Vietnamese', '/ˌvjetnəˈmiːz/', 'người/tiếng Việt (n, adj)', 'I am Vietnamese.', 'Tôi là người Việt Nam.', 22),
  ('how old are you', '/haʊ əʊld ɑː juː/', 'bạn bao nhiêu tuổi', 'How old are you? — I''m twenty.', 'Bạn bao nhiêu tuổi? — Tôi hai mươi.', 23),
  ('years old', '/jɪəz əʊld/', '... tuổi', 'My sister is 15 years old.', 'Em gái tôi 15 tuổi.', 24),
  ('what do you do', '/wɒt duː juː duː/', 'bạn làm nghề gì', 'What do you do? — I''m a nurse.', 'Bạn làm nghề gì? — Tôi là y tá.', 25),
  ('occupation', '/ˌɒkjuˈpeɪʃn/', 'nghề nghiệp (n)', 'Please write your occupation here.', 'Vui lòng ghi nghề nghiệp ở đây.', 26),
  ('student', '/ˈstjuːdnt/', 'học sinh, sinh viên (n)', 'I''m a student at Hanoi University.', 'Tôi là sinh viên Đại học Hà Nội.', 27),
  ('engineer', '/ˌendʒɪˈnɪə/', 'kỹ sư (n)', 'My dad is an engineer.', 'Bố tôi là kỹ sư.', 28),
  ('hobby', '/ˈhɒbi/', 'sở thích (n)', 'What are your hobbies?', 'Sở thích của bạn là gì?', 29),
  ('free time', '/friː taɪm/', 'thời gian rảnh (n)', 'What do you do in your free time?', 'Lúc rảnh bạn làm gì?', 30),
  ('please', '/pliːz/', 'làm ơn, xin mời', 'Could you help me, please?', 'Bạn giúp tôi được không?', 31),
  ('thank you', '/θæŋk juː/', 'cảm ơn', 'Thank you very much.', 'Cảm ơn bạn rất nhiều.', 32),
  ('thanks a lot', '/θæŋks ə lɒt/', 'cảm ơn nhiều', 'Thanks a lot for your help.', 'Cảm ơn nhiều vì đã giúp.', 33),
  ('you''re welcome', '/jɔː ˈwelkəm/', 'không có gì', 'Thanks! — You''re welcome.', 'Cảm ơn! — Không có gì.', 34),
  ('no problem', '/nəʊ ˈprɒbləm/', 'không sao, không có gì', 'Sorry I''m late. — No problem.', 'Xin lỗi tôi muộn. — Không sao.', 35),
  ('excuse me', '/ɪkˈskjuːz miː/', 'xin lỗi (gây chú ý), cho tôi hỏi', 'Excuse me, is this seat taken?', 'Xin lỗi, ghế này có ai ngồi chưa?', 36),
  ('I''m sorry', '/aɪm ˈsɒri/', 'tôi xin lỗi', 'I''m sorry, I forgot your name.', 'Xin lỗi, tôi quên tên bạn rồi.', 37),
  ('pardon', '/ˈpɑːdn/', 'xin lỗi, nói lại được không', 'Pardon? I didn''t hear you.', 'Xin lỗi? Tôi không nghe rõ.', 38),
  ('never mind', '/ˈnevə maɪnd/', 'không sao đâu, bỏ qua đi', 'Never mind, it''s not important.', 'Thôi bỏ đi, không quan trọng.', 39),
  ('of course', '/əv kɔːs/', 'tất nhiên', 'Can I sit here? — Of course.', 'Tôi ngồi đây được không? — Tất nhiên.', 40),
  ('sure', '/ʃʊə/', 'được chứ, chắc chắn', 'Can you pass the salt? — Sure.', 'Đưa lọ muối được không? — Được chứ.', 41),
  ('welcome', '/ˈwelkəm/', 'chào mừng', 'Welcome to Vietnam!', 'Chào mừng đến Việt Nam!', 42),
  ('congratulations', '/kənˌɡrætʃuˈleɪʃnz/', 'chúc mừng', 'Congratulations on your new job!', 'Chúc mừng công việc mới của bạn!', 43),
  ('happy birthday', '/ˌhæpi ˈbɜːθdeɪ/', 'chúc mừng sinh nhật', 'Happy birthday, Mai!', 'Chúc mừng sinh nhật, Mai!', 44),
  ('good luck', '/ɡʊd lʌk/', 'chúc may mắn', 'Good luck with your exam!', 'Chúc bạn thi tốt!', 45),
  ('have a nice day', '/hæv ə naɪs deɪ/', 'chúc một ngày tốt lành', 'Thanks for shopping. Have a nice day!', 'Cảm ơn đã mua hàng. Chúc một ngày tốt lành!', 46),
  ('cheers', '/tʃɪəz/', 'cạn ly; cảm ơn (Anh)', 'Cheers, everyone!', 'Cạn ly nào mọi người!', 47),
  ('long time no see', '/lɒŋ taɪm nəʊ siː/', 'lâu rồi không gặp', 'Hey! Long time no see!', 'Ê! Lâu rồi không gặp!', 48),
  ('what''s up', '/wɒts ʌp/', 'có gì mới không (thân mật)', 'What''s up? You look happy.', 'Có gì vui không? Trông bạn vui thế.', 49),
  ('same here', '/seɪm hɪə/', 'tôi cũng vậy', 'I''m tired. — Same here.', 'Tôi mệt. — Tôi cũng vậy.', 50),
  ('me too', '/miː tuː/', 'tôi cũng thế', 'I love coffee. — Me too!', 'Tôi thích cà phê. — Tôi cũng thế!', 51),
  ('really', '/ˈrɪəli/', 'thật à; thực sự', 'Really? That''s great!', 'Thật à? Tuyệt quá!', 52),
  ('I see', '/aɪ siː/', 'tôi hiểu rồi', 'I see. So you start on Monday.', 'Tôi hiểu rồi. Vậy bạn bắt đầu thứ Hai.', 53),
  ('I think so', '/aɪ θɪŋk səʊ/', 'tôi nghĩ vậy', 'Is the shop open? — I think so.', 'Cửa hàng mở chứ? — Tôi nghĩ vậy.', 54),
  ('I don''t know', '/aɪ dəʊnt nəʊ/', 'tôi không biết', 'Where is he? — I don''t know.', 'Anh ấy đâu? — Tôi không biết.', 55),
  ('maybe', '/ˈmeɪbi/', 'có lẽ', 'Maybe we can meet tomorrow.', 'Có lẽ mai mình gặp nhau.', 56),
  ('by the way', '/baɪ ðə weɪ/', 'nhân tiện', 'By the way, did you call Mom?', 'Nhân tiện, bạn gọi cho mẹ chưa?', 57),
  ('how about you', '/haʊ əˈbaʊt juː/', 'còn bạn thì sao', 'I like tea. How about you?', 'Tôi thích trà. Còn bạn?', 58),
  ('sounds good', '/saʊndz ɡʊd/', 'nghe hay đấy', 'Dinner at seven? — Sounds good.', 'Ăn tối lúc bảy giờ nhé? — Nghe hay đấy.', 59),
  ('no way', '/nəʊ weɪ/', 'không đời nào; không thể tin được', 'You won the lottery? No way!', 'Bạn trúng số à? Không thể tin được!', 60),
  ('just kidding', '/dʒʌst ˈkɪdɪŋ/', 'đùa thôi', 'I ate your cake… just kidding!', 'Tôi ăn bánh của bạn rồi… đùa thôi!', 61),
  ('hang on', '/hæŋ ɒn/', 'chờ chút', 'Hang on, I''ll get my coat.', 'Chờ chút, tôi lấy áo khoác.', 62),
  ('come on', '/kʌm ɒn/', 'thôi nào, nhanh lên', 'Come on, we''ll be late!', 'Nhanh lên, trễ mất!', 63),
  ('let''s go', '/lets ɡəʊ/', 'đi thôi', 'Everyone''s ready. Let''s go!', 'Mọi người sẵn sàng rồi. Đi thôi!', 64),
  ('polite', '/pəˈlaɪt/', 'lịch sự (adj)', 'It''s polite to say thank you.', 'Nói cảm ơn là phép lịch sự.', 65),
  ('rude', '/ruːd/', 'thô lỗ (adj)', 'Don''t be rude to the waiter.', 'Đừng thô lỗ với phục vụ.', 66),
  ('shy', '/ʃaɪ/', 'nhút nhát (adj)', 'He''s shy around new people.', 'Anh ấy nhút nhát với người lạ.', 67),
  ('greeting', '/ˈɡriːtɪŋ/', 'lời chào (n)', 'A handshake is a common greeting.', 'Bắt tay là cách chào phổ biến.', 68),
  ('handshake', '/ˈhændʃeɪk/', 'cái bắt tay (n)', 'He gave me a firm handshake.', 'Anh ấy bắt tay tôi rất chắc.', 69),
  ('wave', '/weɪv/', 'vẫy tay (v)', 'She waved goodbye from the bus.', 'Cô ấy vẫy tay chào từ xe buýt.', 70),
  ('smile', '/smaɪl/', 'mỉm cười (v, n)', 'Smile for the photo!', 'Cười lên chụp ảnh nào!', 71),
  ('get to know', '/ɡet tuː nəʊ/', 'làm quen, tìm hiểu', 'I''d like to get to know you better.', 'Tôi muốn hiểu bạn hơn.', 72),
  ('small talk', '/smɔːl tɔːk/', 'chuyện phiếm xã giao (n)', 'We made small talk about the weather.', 'Chúng tôi nói chuyện phiếm về thời tiết.', 73),
  ('keep in touch', '/kiːp ɪn tʌtʃ/', 'giữ liên lạc', 'Let''s keep in touch!', 'Giữ liên lạc nhé!', 74),
  ('phone number', '/fəʊn ˈnʌmbə/', 'số điện thoại (n)', 'Can I have your phone number?', 'Cho tôi xin số điện thoại được không?', 75),
  ('address', '/əˈdres/', 'địa chỉ (n)', 'What''s your email address?', 'Địa chỉ email của bạn là gì?', 76),
  ('married', '/ˈmærid/', 'đã kết hôn (adj)', 'Are you married?', 'Bạn kết hôn chưa?', 77),
  ('single', '/ˈsɪŋɡl/', 'độc thân (adj)', 'I''m single at the moment.', 'Hiện tại tôi độc thân.', 78),
  ('excuse', '/ɪkˈskjuːs/', 'lời xin lỗi, lý do (n)', 'That''s no excuse for being late.', 'Đó không phải lý do để đến muộn.', 79),
  ('apologize', '/əˈpɒlədʒaɪz/', 'xin lỗi (v)', 'I apologize for the mistake.', 'Tôi xin lỗi vì sai sót.', 80)
) as w(term, phonetic, meaning_vi, example_en, example_vi, position) on true
where d.slug = 'giao-tiep-chao-hoi'
on conflict (deck_id, term) do nothing;

-- Gia đình & bạn bè (81 từ)
insert into public.decks (slug, name, description, level, category, position)
values ('giao-tiep-gia-dinh', 'Gia đình & bạn bè', 'Người thân, mối quan hệ, tính cách', 'beginner', 'giao-tiep', 20)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, level = excluded.level,
  category = excluded.category, position = excluded.position;

insert into public.words (deck_id, term, phonetic, meaning_vi, example_en, example_vi, position)
select d.id, w.term, w.phonetic, w.meaning_vi, w.example_en, w.example_vi, w.position
from public.decks d
join (values
  ('grandfather', '/ˈɡrænfɑːðə/', 'ông (n)', 'My grandfather is 80 years old.', 'Ông tôi 80 tuổi.', 1),
  ('grandmother', '/ˈɡrænmʌðə/', 'bà (n)', 'My grandmother makes the best soup.', 'Bà tôi nấu súp ngon nhất.', 2),
  ('grandparents', '/ˈɡrænpeərənts/', 'ông bà (n)', 'We visit our grandparents every Sunday.', 'Chúng tôi thăm ông bà mỗi Chủ nhật.', 3),
  ('husband', '/ˈhʌzbənd/', 'chồng (n)', 'Her husband is a chef.', 'Chồng cô ấy là đầu bếp.', 4),
  ('wife', '/waɪf/', 'vợ (n)', 'My wife works at a school.', 'Vợ tôi làm ở trường học.', 5),
  ('son', '/sʌn/', 'con trai (n)', 'Their son is ten.', 'Con trai họ mười tuổi.', 6),
  ('daughter', '/ˈdɔːtə/', 'con gái (n)', 'My daughter loves drawing.', 'Con gái tôi thích vẽ.', 7),
  ('brother', '/ˈbrʌðə/', 'anh/em trai (n)', 'I have two brothers.', 'Tôi có hai anh em trai.', 8),
  ('sister', '/ˈsɪstə/', 'chị/em gái (n)', 'My sister lives in Saigon.', 'Chị tôi sống ở Sài Gòn.', 9),
  ('sibling', '/ˈsɪblɪŋ/', 'anh chị em ruột (n)', 'Do you have any siblings?', 'Bạn có anh chị em không?', 10),
  ('uncle', '/ˈʌŋkl/', 'chú, bác, cậu (n)', 'My uncle lives in Canada.', 'Chú tôi sống ở Canada.', 11),
  ('aunt', '/ɑːnt/', 'cô, dì, bác gái (n)', 'My aunt is a nurse.', 'Dì tôi là y tá.', 12),
  ('cousin', '/ˈkʌzn/', 'anh chị em họ (n)', 'I have lots of cousins.', 'Tôi có nhiều anh chị em họ.', 13),
  ('nephew', '/ˈnefjuː/', 'cháu trai (n)', 'My nephew just started school.', 'Cháu trai tôi vừa đi học.', 14),
  ('niece', '/niːs/', 'cháu gái (n)', 'My niece is very cute.', 'Cháu gái tôi rất dễ thương.', 15),
  ('relative', '/ˈrelətɪv/', 'họ hàng (n)', 'All our relatives came to the wedding.', 'Tất cả họ hàng đến dự đám cưới.', 16),
  ('twin', '/twɪn/', 'sinh đôi (n)', 'They are twins.', 'Họ là anh em sinh đôi.', 17),
  ('baby', '/ˈbeɪbi/', 'em bé (n)', 'The baby is sleeping.', 'Em bé đang ngủ.', 18),
  ('teenager', '/ˈtiːneɪdʒə/', 'thiếu niên (n)', 'Teenagers love social media.', 'Thanh thiếu niên thích mạng xã hội.', 19),
  ('only child', '/ˈəʊnli tʃaɪld/', 'con một (n)', 'I''m an only child.', 'Tôi là con một.', 20),
  ('eldest', '/ˈeldɪst/', 'lớn nhất (trong nhà) (adj)', 'She is the eldest of three.', 'Cô ấy là chị cả trong ba chị em.', 21),
  ('youngest', '/ˈjʌŋɡɪst/', 'út (adj)', 'I''m the youngest in my family.', 'Tôi là con út trong nhà.', 22),
  ('close', '/kləʊs/', 'thân thiết (adj)', 'I''m very close to my mom.', 'Tôi rất thân với mẹ.', 23),
  ('get along', '/ɡet əˈlɒŋ/', 'hoà thuận', 'I get along well with my brother.', 'Tôi hoà thuận với anh trai.', 24),
  ('look after', '/lʊk ˈɑːftə/', 'chăm sóc', 'She looks after her grandmother.', 'Cô ấy chăm sóc bà.', 25),
  ('take after', '/teɪk ˈɑːftə/', 'giống (ai trong nhà)', 'He takes after his father.', 'Cậu ấy giống bố.', 26),
  ('grow up', '/ɡrəʊ ʌp/', 'lớn lên', 'I grew up in a small village.', 'Tôi lớn lên ở một ngôi làng nhỏ.', 27),
  ('bring up', '/brɪŋ ʌp/', 'nuôi dạy', 'She brought up three children alone.', 'Cô ấy một mình nuôi ba đứa con.', 28),
  ('best friend', '/best frend/', 'bạn thân nhất (n)', 'Hoa is my best friend.', 'Hoa là bạn thân nhất của tôi.', 29),
  ('classmate', '/ˈklɑːsmeɪt/', 'bạn cùng lớp (n)', 'We were classmates in high school.', 'Chúng tôi học cùng lớp thời cấp ba.', 30),
  ('roommate', '/ˈruːmmeɪt/', 'bạn cùng phòng (n)', 'My roommate is from Japan.', 'Bạn cùng phòng của tôi là người Nhật.', 31),
  ('colleague', '/ˈkɒliːɡ/', 'đồng nghiệp (n)', 'I had lunch with a colleague.', 'Tôi ăn trưa với đồng nghiệp.', 32),
  ('boyfriend', '/ˈbɔɪfrend/', 'bạn trai (n)', 'Her boyfriend is a musician.', 'Bạn trai cô ấy là nhạc sĩ.', 33),
  ('girlfriend', '/ˈɡɜːlfrend/', 'bạn gái (n)', 'He bought flowers for his girlfriend.', 'Anh ấy mua hoa cho bạn gái.', 34),
  ('partner', '/ˈpɑːtnə/', 'bạn đời, đối tác (n)', 'Bring your partner to the party.', 'Đưa bạn đời đến dự tiệc nhé.', 35),
  ('couple', '/ˈkʌpl/', 'cặp đôi (n)', 'They are a lovely couple.', 'Họ là một cặp đôi đáng yêu.', 36),
  ('date', '/deɪt/', 'buổi hẹn hò (n); hẹn hò (v)', 'We went on our first date last week.', 'Chúng tôi hẹn hò lần đầu tuần trước.', 37),
  ('fall in love', '/fɔːl ɪn lʌv/', 'yêu', 'They fell in love at university.', 'Họ yêu nhau thời đại học.', 38),
  ('engaged', '/ɪnˈɡeɪdʒd/', 'đã đính hôn (adj)', 'We got engaged in June.', 'Chúng tôi đính hôn vào tháng Sáu.', 39),
  ('wedding', '/ˈwedɪŋ/', 'đám cưới (n)', 'The wedding is next month.', 'Đám cưới vào tháng sau.', 40),
  ('anniversary', '/ˌænɪˈvɜːsəri/', 'ngày kỷ niệm (n)', 'Today is our tenth anniversary.', 'Hôm nay là kỷ niệm mười năm của chúng tôi.', 41),
  ('divorced', '/dɪˈvɔːst/', 'đã ly hôn (adj)', 'Her parents are divorced.', 'Bố mẹ cô ấy đã ly hôn.', 42),
  ('pregnant', '/ˈpreɡnənt/', 'mang thai (adj)', 'My sister is pregnant.', 'Chị tôi đang mang thai.', 43),
  ('born', '/bɔːn/', 'được sinh ra (adj)', 'I was born in 1998.', 'Tôi sinh năm 1998.', 44),
  ('funeral', '/ˈfjuːnərəl/', 'đám tang (n)', 'The funeral is on Friday.', 'Đám tang vào thứ Sáu.', 45),
  ('move house', '/muːv haʊs/', 'chuyển nhà', 'We''re moving house next week.', 'Tuần sau chúng tôi chuyển nhà.', 46),
  ('household', '/ˈhaʊshəʊld/', 'hộ gia đình (n)', 'There are five people in our household.', 'Nhà tôi có năm người.', 47),
  ('reunion', '/ˌriːˈjuːniən/', 'buổi đoàn tụ, họp mặt (n)', 'We have a family reunion every year.', 'Gia đình tôi họp mặt hằng năm.', 48),
  ('generation', '/ˌdʒenəˈreɪʃn/', 'thế hệ (n)', 'Three generations live in our house.', 'Nhà tôi có ba thế hệ cùng sống.', 49),
  ('kind', '/kaɪnd/', 'tốt bụng (adj)', 'My grandma is very kind.', 'Bà tôi rất tốt bụng.', 50),
  ('generous', '/ˈdʒenərəs/', 'hào phóng (adj)', 'He''s generous with his time.', 'Anh ấy hào phóng về thời gian.', 51),
  ('honest', '/ˈɒnɪst/', 'trung thực (adj)', 'Be honest with your friends.', 'Hãy trung thực với bạn bè.', 52),
  ('patient', '/ˈpeɪʃnt/', 'kiên nhẫn (adj)', 'Teachers must be patient.', 'Giáo viên phải kiên nhẫn.', 53),
  ('lazy', '/ˈleɪzi/', 'lười (adj)', 'My cat is so lazy.', 'Con mèo của tôi lười lắm.', 54),
  ('hard-working', '/ˌhɑːd ˈwɜːkɪŋ/', 'chăm chỉ (adj)', 'She is a hard-working student.', 'Cô ấy là học sinh chăm chỉ.', 55),
  ('funny', '/ˈfʌni/', 'hài hước (adj)', 'My uncle is really funny.', 'Chú tôi rất hài hước.', 56),
  ('serious', '/ˈsɪəriəs/', 'nghiêm túc (adj)', 'My dad is quite serious.', 'Bố tôi khá nghiêm túc.', 57),
  ('talkative', '/ˈtɔːkətɪv/', 'nói nhiều (adj)', 'My little sister is very talkative.', 'Em gái tôi nói rất nhiều.', 58),
  ('outgoing', '/ˈaʊtɡəʊɪŋ/', 'hướng ngoại (adj)', 'He''s outgoing and makes friends easily.', 'Anh ấy hướng ngoại và dễ kết bạn.', 59),
  ('confident', '/ˈkɒnfɪdənt/', 'tự tin (adj)', 'She''s confident on stage.', 'Cô ấy tự tin trên sân khấu.', 60),
  ('caring', '/ˈkeərɪŋ/', 'quan tâm, chu đáo (adj)', 'Nurses are caring people.', 'Y tá là những người chu đáo.', 61),
  ('stubborn', '/ˈstʌbən/', 'bướng bỉnh (adj)', 'My brother is stubborn.', 'Em trai tôi bướng lắm.', 62),
  ('selfish', '/ˈselfɪʃ/', 'ích kỷ (adj)', 'Don''t be selfish; share your toys.', 'Đừng ích kỷ, chia sẻ đồ chơi đi.', 63),
  ('cheerful', '/ˈtʃɪəfl/', 'vui vẻ (adj)', 'She is always cheerful in the morning.', 'Cô ấy luôn vui vẻ vào buổi sáng.', 64),
  ('sensitive', '/ˈsensətɪv/', 'nhạy cảm (adj)', 'He is sensitive to criticism.', 'Anh ấy nhạy cảm với lời phê bình.', 65),
  ('reliable', '/rɪˈlaɪəbl/', 'đáng tin cậy (adj)', 'A good friend is reliable.', 'Bạn tốt là người đáng tin cậy.', 66),
  ('personality', '/ˌpɜːsəˈnæləti/', 'tính cách (n)', 'She has a warm personality.', 'Cô ấy có tính cách ấm áp.', 67),
  ('look like', '/lʊk laɪk/', 'trông giống', 'You look like your mother.', 'Bạn trông giống mẹ.', 68),
  ('tall', '/tɔːl/', 'cao (adj)', 'My dad is tall and thin.', 'Bố tôi cao và gầy.', 69),
  ('short hair', '/ʃɔːt heə/', 'tóc ngắn (n)', 'She has short black hair.', 'Cô ấy tóc đen ngắn.', 70),
  ('curly', '/ˈkɜːli/', 'xoăn (adj)', 'My daughter has curly hair.', 'Con gái tôi tóc xoăn.', 71),
  ('glasses', '/ˈɡlɑːsɪz/', 'kính mắt (n)', 'My brother wears glasses.', 'Anh tôi đeo kính.', 72),
  ('beard', '/bɪəd/', 'râu (n)', 'My uncle has a grey beard.', 'Chú tôi có râu bạc.', 73),
  ('handsome', '/ˈhænsəm/', 'đẹp trai (adj)', 'Her husband is very handsome.', 'Chồng cô ấy rất đẹp trai.', 74),
  ('pretty', '/ˈprɪti/', 'xinh (adj)', 'Your sister is pretty.', 'Chị bạn xinh quá.', 75),
  ('housework', '/ˈhaʊswɜːk/', 'việc nhà (n)', 'We share the housework.', 'Chúng tôi chia nhau làm việc nhà.', 76),
  ('argue', '/ˈɑːɡjuː/', 'cãi nhau (v)', 'My parents rarely argue.', 'Bố mẹ tôi hiếm khi cãi nhau.', 77),
  ('hug', '/hʌɡ/', 'ôm (v, n)', 'Give your mom a hug.', 'Ôm mẹ một cái đi.', 78),
  ('miss', '/mɪs/', 'nhớ (v)', 'I miss my hometown.', 'Tôi nhớ quê.', 79),
  ('support', '/səˈpɔːt/', 'ủng hộ (v, n)', 'My family supports my dream.', 'Gia đình ủng hộ ước mơ của tôi.', 80),
  ('trust', '/trʌst/', 'tin tưởng (v, n)', 'I trust my best friend completely.', 'Tôi hoàn toàn tin tưởng bạn thân.', 81)
) as w(term, phonetic, meaning_vi, example_en, example_vi, position) on true
where d.slug = 'giao-tiep-gia-dinh'
on conflict (deck_id, term) do nothing;

-- Mua sắm & ăn uống (80 từ)
insert into public.decks (slug, name, description, level, category, position)
values ('giao-tiep-mua-sam', 'Mua sắm & ăn uống', 'Siêu thị, quán ăn, giá cả, gọi món', 'beginner', 'giao-tiep', 30)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, level = excluded.level,
  category = excluded.category, position = excluded.position;

insert into public.words (deck_id, term, phonetic, meaning_vi, example_en, example_vi, position)
select d.id, w.term, w.phonetic, w.meaning_vi, w.example_en, w.example_vi, w.position
from public.decks d
join (values
  ('supermarket', '/ˈsuːpəmɑːkɪt/', 'siêu thị (n)', 'I''m going to the supermarket.', 'Tôi đi siêu thị đây.', 1),
  ('grocery store', '/ˈɡrəʊsəri stɔː/', 'cửa hàng tạp hoá (n)', 'There''s a grocery store on the corner.', 'Có cửa hàng tạp hoá ở góc phố.', 2),
  ('shopping mall', '/ˈʃɒpɪŋ mɔːl/', 'trung tâm thương mại (n)', 'Let''s meet at the shopping mall.', 'Gặp nhau ở trung tâm thương mại nhé.', 3),
  ('convenience store', '/kənˈviːniəns stɔː/', 'cửa hàng tiện lợi (n)', 'The convenience store is open 24 hours.', 'Cửa hàng tiện lợi mở 24 giờ.', 4),
  ('bakery', '/ˈbeɪkəri/', 'tiệm bánh (n)', 'The bakery sells fresh croissants.', 'Tiệm bánh bán bánh sừng bò tươi.', 5),
  ('shopping list', '/ˈʃɒpɪŋ lɪst/', 'danh sách mua sắm (n)', 'Did you bring the shopping list?', 'Bạn mang danh sách mua sắm chưa?', 6),
  ('cart', '/kɑːt/', 'xe đẩy hàng (n)', 'Grab a cart at the entrance.', 'Lấy xe đẩy ở lối vào.', 7),
  ('basket', '/ˈbɑːskɪt/', 'giỏ (n)', 'I only need a basket today.', 'Hôm nay tôi chỉ cần cái giỏ.', 8),
  ('aisle', '/aɪl/', 'lối đi giữa các kệ (n)', 'Rice is in aisle three.', 'Gạo ở lối đi số ba.', 9),
  ('cashier', '/kæˈʃɪə/', 'thu ngân (n)', 'Pay the cashier at the front.', 'Trả tiền cho thu ngân ở phía trước.', 10),
  ('checkout', '/ˈtʃekaʊt/', 'quầy thanh toán (n)', 'There''s a long line at the checkout.', 'Quầy thanh toán đang xếp hàng dài.', 11),
  ('receipt', '/rɪˈsiːt/', 'biên lai (n)', 'Would you like a receipt?', 'Bạn có muốn lấy biên lai không?', 12),
  ('cash', '/kæʃ/', 'tiền mặt (n)', 'Do you pay by cash or card?', 'Bạn trả tiền mặt hay thẻ?', 13),
  ('credit card', '/ˈkredɪt kɑːd/', 'thẻ tín dụng (n)', 'I paid with my credit card.', 'Tôi trả bằng thẻ tín dụng.', 14),
  ('change', '/tʃeɪndʒ/', 'tiền thừa (n)', 'Here''s your change.', 'Đây là tiền thừa của bạn.', 15),
  ('how much', '/haʊ mʌtʃ/', 'bao nhiêu tiền', 'How much is this shirt?', 'Cái áo này bao nhiêu tiền?', 16),
  ('expensive', '/ɪkˈspensɪv/', 'đắt (adj)', 'That bag is too expensive.', 'Cái túi đó đắt quá.', 17),
  ('cheap', '/tʃiːp/', 'rẻ (adj)', 'The market is cheaper than the mall.', 'Chợ rẻ hơn trung tâm thương mại.', 18),
  ('on sale', '/ɒn seɪl/', 'đang giảm giá', 'These shoes are on sale.', 'Đôi giày này đang giảm giá.', 19),
  ('discount', '/ˈdɪskaʊnt/', 'giảm giá (n)', 'Can I get a discount?', 'Giảm giá cho tôi được không?', 20),
  ('bargain', '/ˈbɑːɡən/', 'mặc cả (v); món hời (n)', 'You can bargain at the market.', 'Bạn có thể mặc cả ở chợ.', 21),
  ('try on', '/traɪ ɒn/', 'mặc thử', 'Can I try this on?', 'Tôi mặc thử cái này được không?', 22),
  ('fitting room', '/ˈfɪtɪŋ ruːm/', 'phòng thử đồ (n)', 'The fitting rooms are at the back.', 'Phòng thử đồ ở phía sau.', 23),
  ('size', '/saɪz/', 'cỡ (n)', 'What size are you?', 'Bạn mặc cỡ nào?', 24),
  ('fit', '/fɪt/', 'vừa (v)', 'This jacket fits perfectly.', 'Áo khoác này vừa khít.', 25),
  ('refund', '/ˈriːfʌnd/', 'hoàn tiền (n)', 'Can I get a refund?', 'Tôi được hoàn tiền không?', 26),
  ('exchange', '/ɪksˈtʃeɪndʒ/', 'đổi hàng (v)', 'I''d like to exchange this for a smaller one.', 'Tôi muốn đổi cái này lấy cỡ nhỏ hơn.', 27),
  ('brand', '/brænd/', 'nhãn hiệu (n)', 'What brand is your phone?', 'Điện thoại bạn hiệu gì?', 28),
  ('vegetable', '/ˈvedʒtəbl/', 'rau (n)', 'Eat more vegetables.', 'Ăn nhiều rau hơn.', 29),
  ('fruit', '/fruːt/', 'trái cây (n)', 'I eat fruit every day.', 'Tôi ăn trái cây mỗi ngày.', 30),
  ('meat', '/miːt/', 'thịt (n)', 'I don''t eat much meat.', 'Tôi không ăn nhiều thịt.', 31),
  ('chicken', '/ˈtʃɪkɪn/', 'gà, thịt gà (n)', 'I''ll have the chicken, please.', 'Cho tôi món gà.', 32),
  ('beef', '/biːf/', 'thịt bò (n)', 'Pho with beef is my favorite.', 'Phở bò là món tôi thích nhất.', 33),
  ('pork', '/pɔːk/', 'thịt lợn (n)', 'This dish is made with pork.', 'Món này làm từ thịt lợn.', 34),
  ('seafood', '/ˈsiːfuːd/', 'hải sản (n)', 'Nha Trang is famous for seafood.', 'Nha Trang nổi tiếng về hải sản.', 35),
  ('egg', '/eɡ/', 'trứng (n)', 'I had two eggs for breakfast.', 'Tôi ăn hai quả trứng bữa sáng.', 36),
  ('rice', '/raɪs/', 'cơm, gạo (n)', 'We eat rice every day.', 'Chúng tôi ăn cơm mỗi ngày.', 37),
  ('noodles', '/ˈnuːdlz/', 'mì, bún, phở (n)', 'I love noodles for breakfast.', 'Tôi thích ăn bún phở bữa sáng.', 38),
  ('bread', '/bred/', 'bánh mì (n)', 'A loaf of bread, please.', 'Cho tôi một ổ bánh mì.', 39),
  ('milk', '/mɪlk/', 'sữa (n)', 'We''re out of milk.', 'Nhà hết sữa rồi.', 40),
  ('cheese', '/tʃiːz/', 'phô mai (n)', 'Extra cheese on my pizza, please.', 'Cho thêm phô mai vào pizza của tôi.', 41),
  ('sugar', '/ˈʃʊɡə/', 'đường (n)', 'No sugar in my coffee, thanks.', 'Cà phê của tôi không đường nhé.', 42),
  ('salt', '/sɔːlt/', 'muối (n)', 'Pass the salt, please.', 'Đưa tôi lọ muối với.', 43),
  ('snack', '/snæk/', 'đồ ăn vặt (n)', 'I need a snack before dinner.', 'Tôi cần ăn vặt trước bữa tối.', 44),
  ('dessert', '/dɪˈzɜːt/', 'món tráng miệng (n)', 'What''s for dessert?', 'Tráng miệng có gì?', 45),
  ('drink', '/drɪŋk/', 'đồ uống (n)', 'What would you like to drink?', 'Bạn muốn uống gì?', 46),
  ('juice', '/dʒuːs/', 'nước ép (n)', 'A glass of orange juice, please.', 'Cho tôi một ly nước cam.', 47),
  ('iced coffee', '/aɪst ˈkɒfi/', 'cà phê đá (n)', 'Vietnamese iced coffee is very strong.', 'Cà phê đá Việt Nam rất đậm.', 48),
  ('bottle of water', '/ˈbɒtl əv ˈwɔːtə/', 'chai nước', 'Can I have a bottle of water?', 'Cho tôi một chai nước.', 49),
  ('restaurant', '/ˈrestrɒnt/', 'nhà hàng (n)', 'Let''s try the new restaurant.', 'Thử nhà hàng mới đi.', 50),
  ('café', '/ˈkæfeɪ/', 'quán cà phê (n)', 'There''s a nice café near here.', 'Có quán cà phê đẹp gần đây.', 51),
  ('street food', '/striːt fuːd/', 'đồ ăn đường phố (n)', 'Hanoi street food is amazing.', 'Đồ ăn đường phố Hà Nội tuyệt vời.', 52),
  ('menu', '/ˈmenjuː/', 'thực đơn (n)', 'Can I see the menu?', 'Cho tôi xem thực đơn.', 53),
  ('order', '/ˈɔːdə/', 'gọi món (v)', 'I''d like to order now.', 'Tôi muốn gọi món bây giờ.', 54),
  ('I''d like', '/aɪd laɪk/', 'tôi muốn (lịch sự)', 'I''d like a bowl of pho, please.', 'Cho tôi một tô phở.', 55),
  ('waiter', '/ˈweɪtə/', 'nhân viên phục vụ (n)', 'Ask the waiter for the bill.', 'Hỏi phục vụ tính tiền.', 56),
  ('bill', '/bɪl/', 'hoá đơn (n)', 'The bill, please.', 'Cho tôi tính tiền.', 57),
  ('tip', '/tɪp/', 'tiền boa (n)', 'Should we leave a tip?', 'Mình có nên để lại tiền boa không?', 58),
  ('delicious', '/dɪˈlɪʃəs/', 'ngon (adj)', 'This soup is delicious!', 'Món súp này ngon quá!', 59),
  ('tasty', '/ˈteɪsti/', 'ngon miệng (adj)', 'The noodles were really tasty.', 'Mì rất ngon.', 60),
  ('spicy', '/ˈspaɪsi/', 'cay (adj)', 'Is this dish spicy?', 'Món này có cay không?', 61),
  ('sweet', '/swiːt/', 'ngọt (adj)', 'The tea is too sweet for me.', 'Trà này ngọt quá với tôi.', 62),
  ('sour', '/ˈsaʊə/', 'chua (adj)', 'Lemons are sour.', 'Chanh chua.', 63),
  ('salty', '/ˈsɔːlti/', 'mặn (adj)', 'The fish is a bit salty.', 'Cá hơi mặn.', 64),
  ('bitter', '/ˈbɪtə/', 'đắng (adj)', 'Black coffee is bitter.', 'Cà phê đen thì đắng.', 65),
  ('fresh', '/freʃ/', 'tươi (adj)', 'The vegetables are very fresh.', 'Rau rất tươi.', 66),
  ('hungry', '/ˈhʌŋɡri/', 'đói (adj)', 'I''m so hungry!', 'Tôi đói quá!', 67),
  ('thirsty', '/ˈθɜːsti/', 'khát (adj)', 'I''m thirsty; let''s get a drink.', 'Tôi khát; đi uống gì đi.', 68),
  ('full', '/fʊl/', 'no (adj)', 'No more, thanks. I''m full.', 'Thôi đủ rồi, cảm ơn. Tôi no rồi.', 69),
  ('breakfast', '/ˈbrekfəst/', 'bữa sáng (n)', 'What do you have for breakfast?', 'Bữa sáng bạn ăn gì?', 70),
  ('lunch', '/lʌntʃ/', 'bữa trưa (n)', 'Let''s have lunch together.', 'Ăn trưa cùng nhau nhé.', 71),
  ('dinner', '/ˈdɪnə/', 'bữa tối (n)', 'Dinner is at seven.', 'Bữa tối lúc bảy giờ.', 72),
  ('cook', '/kʊk/', 'nấu (v)', 'I''ll cook tonight.', 'Tối nay tôi nấu.', 73),
  ('recipe', '/ˈresəpi/', 'công thức nấu ăn (n)', 'Can I have the recipe?', 'Cho tôi xin công thức được không?', 74),
  ('boil', '/bɔɪl/', 'luộc, đun sôi (v)', 'Boil the eggs for seven minutes.', 'Luộc trứng bảy phút.', 75),
  ('fry', '/fraɪ/', 'chiên, rán (v)', 'Fry the onions until golden.', 'Phi hành đến khi vàng.', 76),
  ('grill', '/ɡrɪl/', 'nướng (v)', 'Let''s grill some fish.', 'Nướng ít cá đi.', 77),
  ('chopsticks', '/ˈtʃɒpstɪks/', 'đũa (n)', 'Can you eat with chopsticks?', 'Bạn ăn bằng đũa được không?', 78),
  ('spoon', '/spuːn/', 'cái thìa (n)', 'Could I have a spoon?', 'Cho tôi cái thìa được không?', 79),
  ('takeaway', '/ˈteɪkəweɪ/', 'đồ ăn mang về (n)', 'Let''s get a takeaway tonight.', 'Tối nay mua đồ ăn mang về đi.', 80)
) as w(term, phonetic, meaning_vi, example_en, example_vi, position) on true
where d.slug = 'giao-tiep-mua-sam'
on conflict (deck_id, term) do nothing;
