-- DailyEng — seed nhóm "giao-tiep". SINH TỰ ĐỘNG bởi scripts/generate-decks.mts, đừng sửa tay.
-- Chạy SAU schema-07-nhom-bo-tu.sql. Chạy lại nhiều lần được: bộ đã có thì cập nhật tên/mô tả,
-- từ đã có (deck_id, term) thì giữ nguyên để không mất tiến độ học của người dùng.

-- Chào hỏi & giới thiệu (80 từ)
insert into public.decks (slug, name, description, level, category, position)
values ('giao-tiep-chao-hoi', 'Chào hỏi & giới thiệu', 'Làm quen, giới thiệu bản thân, phép lịch sự', 'beginner', 'giao-tiep', 10)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, level = excluded.level,
  category = excluded.category, position = excluded.position;

insert into public.words (deck_id, term, phonetic, meaning_vi, example_en, example_vi, position)
select d.id, w.term, w.phonetic, w.meaning_vi, w.example_en, w.example_vi, w.position
from public.decks d
join (values
  ('hi', '/haɪ/', 'chào (thân mật)', 'Hi, I''m Minh.', 'Chào, mình là Minh.', 1),
  ('good morning', '/ɡʊd ˈmɔːnɪŋ/', 'chào buổi sáng', 'Good morning, everyone!', 'Chào buổi sáng mọi người!', 2),
  ('good afternoon', '/ɡʊd ˌɑːftəˈnuːn/', 'chào buổi chiều', 'Good afternoon, Mr. Lee.', 'Chào buổi chiều, ông Lee.', 3),
  ('good evening', '/ɡʊd ˈiːvnɪŋ/', 'chào buổi tối', 'Good evening, welcome to our restaurant.', 'Chào buổi tối, chào mừng đến nhà hàng.', 4),
  ('goodbye', '/ˌɡʊdˈbaɪ/', 'tạm biệt', 'Goodbye, see you next week.', 'Tạm biệt, hẹn gặp tuần sau.', 5),
  ('bye', '/baɪ/', 'chào tạm biệt (thân mật)', 'Bye! Take care.', 'Chào nhé! Giữ sức khoẻ.', 6),
  ('see you later', '/siː juː ˈleɪtə/', 'hẹn gặp lại', 'See you later, I''m off to work.', 'Gặp lại sau nhé, tôi đi làm đây.', 7),
  ('take care', '/teɪk keə/', 'giữ gìn sức khoẻ', 'Take care and call me when you land.', 'Giữ gìn sức khoẻ và gọi tôi khi hạ cánh.', 8),
  ('nice to meet you', '/naɪs tuː miːt juː/', 'rất vui được gặp bạn', 'Nice to meet you, Anna.', 'Rất vui được gặp bạn, Anna.', 9),
  ('how are you', '/haʊ ɑː juː/', 'bạn khoẻ không', 'Hi Tom, how are you?', 'Chào Tom, bạn khoẻ không?', 10),
  ('how''s it going', '/haʊz ɪt ˈɡəʊɪŋ/', 'dạo này thế nào (thân mật)', 'Hey, how''s it going?', 'Ê, dạo này sao rồi?', 11),
  ('I''m fine, thanks', '/aɪm faɪn θæŋks/', 'tôi khoẻ, cảm ơn', 'I''m fine, thanks. And you?', 'Tôi khoẻ, cảm ơn. Còn bạn?', 12),
  ('not bad', '/nɒt bæd/', 'cũng ổn', 'How''s work? — Not bad.', 'Công việc sao rồi? — Cũng ổn.', 13),
  ('what''s your name', '/wɒts jɔː neɪm/', 'bạn tên gì', 'Hello, what''s your name?', 'Xin chào, bạn tên gì?', 14),
  ('my name is', '/maɪ neɪm ɪz/', 'tôi tên là', 'My name is Lan Anh.', 'Tôi tên là Lan Anh.', 15),
  ('introduce', '/ˌɪntrəˈdjuːs/', 'giới thiệu (v)', 'Let me introduce myself.', 'Cho phép tôi tự giới thiệu.', 16),
  ('nickname', '/ˈnɪkneɪm/', 'biệt danh (n)', 'My nickname is Bin.', 'Biệt danh của tôi là Bin.', 17),
  ('spell', '/spel/', 'đánh vần (v)', 'How do you spell your name?', 'Tên bạn đánh vần thế nào?', 18),
  ('where are you from', '/weər ɑː juː frɒm/', 'bạn đến từ đâu', 'Where are you from? — Vietnam.', 'Bạn đến từ đâu? — Việt Nam.', 19),
  ('hometown', '/ˈhəʊmtaʊn/', 'quê nhà (n)', 'My hometown is Can Tho.', 'Quê tôi ở Cần Thơ.', 20),
  ('nationality', '/ˌnæʃəˈnæləti/', 'quốc tịch (n)', 'What is your nationality?', 'Quốc tịch của bạn là gì?', 21),
  ('Vietnamese', '/ˌvjetnəˈmiːz/', 'người/tiếng Việt (n, adj)', 'I am Vietnamese.', 'Tôi là người Việt Nam.', 22),
  ('how old are you', '/haʊ əʊld ɑː juː/', 'bạn bao nhiêu tuổi', 'How old are you? — I''m twenty.', 'Bạn bao nhiêu tuổi? — Tôi hai mươi.', 23),
  ('years old', '/jɪəz əʊld/', '... tuổi', 'My sister is 15 years old.', 'Em gái tôi 15 tuổi.', 24),
  ('what do you do', '/wɒt duː juː duː/', 'bạn làm nghề gì', 'What do you do? — I''m a nurse.', 'Bạn làm nghề gì? — Tôi là y tá.', 25),
  ('occupation', '/ˌɒkjuˈpeɪʃn/', 'nghề nghiệp (n)', 'Please write your occupation here.', 'Vui lòng ghi nghề nghiệp ở đây.', 26),
  ('student', '/ˈstjuːdnt/', 'học sinh, sinh viên (n)', 'I''m a student at Hanoi University.', 'Tôi là sinh viên Đại học Hà Nội.', 27),
  ('engineer', '/ˌendʒɪˈnɪə/', 'kỹ sư (n)', 'My dad is an engineer.', 'Bố tôi là kỹ sư.', 28),
  ('hobby', '/ˈhɒbi/', 'sở thích (n)', 'What are your hobbies?', 'Sở thích của bạn là gì?', 29),
  ('free time', '/friː taɪm/', 'thời gian rảnh (n)', 'What do you do in your free time?', 'Lúc rảnh bạn làm gì?', 30),
  ('please', '/pliːz/', 'làm ơn, xin mời', 'Could you help me, please?', 'Bạn giúp tôi được không?', 31),
  ('thank you', '/θæŋk juː/', 'cảm ơn', 'Thank you very much.', 'Cảm ơn bạn rất nhiều.', 32),
  ('thanks a lot', '/θæŋks ə lɒt/', 'cảm ơn nhiều', 'Thanks a lot for your help.', 'Cảm ơn nhiều vì đã giúp.', 33),
  ('you''re welcome', '/jɔː ˈwelkəm/', 'không có gì', 'Thanks! — You''re welcome.', 'Cảm ơn! — Không có gì.', 34),
  ('no problem', '/nəʊ ˈprɒbləm/', 'không sao, không có gì', 'Sorry I''m late. — No problem.', 'Xin lỗi tôi muộn. — Không sao.', 35),
  ('excuse me', '/ɪkˈskjuːz miː/', 'xin lỗi (gây chú ý), cho tôi hỏi', 'Excuse me, is this seat taken?', 'Xin lỗi, ghế này có ai ngồi chưa?', 36),
  ('I''m sorry', '/aɪm ˈsɒri/', 'tôi xin lỗi', 'I''m sorry, I forgot your name.', 'Xin lỗi, tôi quên tên bạn rồi.', 37),
  ('pardon', '/ˈpɑːdn/', 'xin lỗi, nói lại được không', 'Pardon? I didn''t hear you.', 'Xin lỗi? Tôi không nghe rõ.', 38),
  ('never mind', '/ˈnevə maɪnd/', 'không sao đâu, bỏ qua đi', 'Never mind, it''s not important.', 'Thôi bỏ đi, không quan trọng.', 39),
  ('of course', '/əv kɔːs/', 'tất nhiên', 'Can I sit here? — Of course.', 'Tôi ngồi đây được không? — Tất nhiên.', 40),
  ('sure', '/ʃʊə/', 'được chứ, chắc chắn', 'Can you pass the salt? — Sure.', 'Đưa lọ muối được không? — Được chứ.', 41),
  ('welcome', '/ˈwelkəm/', 'chào mừng', 'Welcome to Vietnam!', 'Chào mừng đến Việt Nam!', 42),
  ('congratulations', '/kənˌɡrætʃuˈleɪʃnz/', 'chúc mừng', 'Congratulations on your new job!', 'Chúc mừng công việc mới của bạn!', 43),
  ('happy birthday', '/ˌhæpi ˈbɜːθdeɪ/', 'chúc mừng sinh nhật', 'Happy birthday, Mai!', 'Chúc mừng sinh nhật, Mai!', 44),
  ('good luck', '/ɡʊd lʌk/', 'chúc may mắn', 'Good luck with your exam!', 'Chúc bạn thi tốt!', 45),
  ('have a nice day', '/hæv ə naɪs deɪ/', 'chúc một ngày tốt lành', 'Thanks for shopping. Have a nice day!', 'Cảm ơn đã mua hàng. Chúc một ngày tốt lành!', 46),
  ('cheers', '/tʃɪəz/', 'cạn ly; cảm ơn (Anh)', 'Cheers, everyone!', 'Cạn ly nào mọi người!', 47),
  ('long time no see', '/lɒŋ taɪm nəʊ siː/', 'lâu rồi không gặp', 'Hey! Long time no see!', 'Ê! Lâu rồi không gặp!', 48),
  ('what''s up', '/wɒts ʌp/', 'có gì mới không (thân mật)', 'What''s up? You look happy.', 'Có gì vui không? Trông bạn vui thế.', 49),
  ('same here', '/seɪm hɪə/', 'tôi cũng vậy', 'I''m tired. — Same here.', 'Tôi mệt. — Tôi cũng vậy.', 50),
  ('me too', '/miː tuː/', 'tôi cũng thế', 'I love coffee. — Me too!', 'Tôi thích cà phê. — Tôi cũng thế!', 51),
  ('really', '/ˈrɪəli/', 'thật à; thực sự', 'Really? That''s great!', 'Thật à? Tuyệt quá!', 52),
  ('I see', '/aɪ siː/', 'tôi hiểu rồi', 'I see. So you start on Monday.', 'Tôi hiểu rồi. Vậy bạn bắt đầu thứ Hai.', 53),
  ('I think so', '/aɪ θɪŋk səʊ/', 'tôi nghĩ vậy', 'Is the shop open? — I think so.', 'Cửa hàng mở chứ? — Tôi nghĩ vậy.', 54),
  ('I don''t know', '/aɪ dəʊnt nəʊ/', 'tôi không biết', 'Where is he? — I don''t know.', 'Anh ấy đâu? — Tôi không biết.', 55),
  ('maybe', '/ˈmeɪbi/', 'có lẽ', 'Maybe we can meet tomorrow.', 'Có lẽ mai mình gặp nhau.', 56),
  ('by the way', '/baɪ ðə weɪ/', 'nhân tiện', 'By the way, did you call Mom?', 'Nhân tiện, bạn gọi cho mẹ chưa?', 57),
  ('how about you', '/haʊ əˈbaʊt juː/', 'còn bạn thì sao', 'I like tea. How about you?', 'Tôi thích trà. Còn bạn?', 58),
  ('sounds good', '/saʊndz ɡʊd/', 'nghe hay đấy', 'Dinner at seven? — Sounds good.', 'Ăn tối lúc bảy giờ nhé? — Nghe hay đấy.', 59),
  ('no way', '/nəʊ weɪ/', 'không đời nào; không thể tin được', 'You won the lottery? No way!', 'Bạn trúng số à? Không thể tin được!', 60),
  ('just kidding', '/dʒʌst ˈkɪdɪŋ/', 'đùa thôi', 'I ate your cake… just kidding!', 'Tôi ăn bánh của bạn rồi… đùa thôi!', 61),
  ('hang on', '/hæŋ ɒn/', 'chờ chút', 'Hang on, I''ll get my coat.', 'Chờ chút, tôi lấy áo khoác.', 62),
  ('come on', '/kʌm ɒn/', 'thôi nào, nhanh lên', 'Come on, we''ll be late!', 'Nhanh lên, trễ mất!', 63),
  ('let''s go', '/lets ɡəʊ/', 'đi thôi', 'Everyone''s ready. Let''s go!', 'Mọi người sẵn sàng rồi. Đi thôi!', 64),
  ('polite', '/pəˈlaɪt/', 'lịch sự (adj)', 'It''s polite to say thank you.', 'Nói cảm ơn là phép lịch sự.', 65),
  ('rude', '/ruːd/', 'thô lỗ (adj)', 'Don''t be rude to the waiter.', 'Đừng thô lỗ với phục vụ.', 66),
  ('shy', '/ʃaɪ/', 'nhút nhát (adj)', 'He''s shy around new people.', 'Anh ấy nhút nhát với người lạ.', 67),
  ('greeting', '/ˈɡriːtɪŋ/', 'lời chào (n)', 'A handshake is a common greeting.', 'Bắt tay là cách chào phổ biến.', 68),
  ('handshake', '/ˈhændʃeɪk/', 'cái bắt tay (n)', 'He gave me a firm handshake.', 'Anh ấy bắt tay tôi rất chắc.', 69),
  ('wave', '/weɪv/', 'vẫy tay (v)', 'She waved goodbye from the bus.', 'Cô ấy vẫy tay chào từ xe buýt.', 70),
  ('smile', '/smaɪl/', 'mỉm cười (v, n)', 'Smile for the photo!', 'Cười lên chụp ảnh nào!', 71),
  ('get to know', '/ɡet tuː nəʊ/', 'làm quen, tìm hiểu', 'I''d like to get to know you better.', 'Tôi muốn hiểu bạn hơn.', 72),
  ('small talk', '/smɔːl tɔːk/', 'chuyện phiếm xã giao (n)', 'We made small talk about the weather.', 'Chúng tôi nói chuyện phiếm về thời tiết.', 73),
  ('keep in touch', '/kiːp ɪn tʌtʃ/', 'giữ liên lạc', 'Let''s keep in touch!', 'Giữ liên lạc nhé!', 74),
  ('phone number', '/fəʊn ˈnʌmbə/', 'số điện thoại (n)', 'Can I have your phone number?', 'Cho tôi xin số điện thoại được không?', 75),
  ('address', '/əˈdres/', 'địa chỉ (n)', 'What''s your email address?', 'Địa chỉ email của bạn là gì?', 76),
  ('married', '/ˈmærid/', 'đã kết hôn (adj)', 'Are you married?', 'Bạn kết hôn chưa?', 77),
  ('single', '/ˈsɪŋɡl/', 'độc thân (adj)', 'I''m single at the moment.', 'Hiện tại tôi độc thân.', 78),
  ('excuse', '/ɪkˈskjuːs/', 'lời xin lỗi, lý do (n)', 'That''s no excuse for being late.', 'Đó không phải lý do để đến muộn.', 79),
  ('apologize', '/əˈpɒlədʒaɪz/', 'xin lỗi (v)', 'I apologize for the mistake.', 'Tôi xin lỗi vì sai sót.', 80)
) as w(term, phonetic, meaning_vi, example_en, example_vi, position) on true
where d.slug = 'giao-tiep-chao-hoi'
on conflict (deck_id, term) do nothing;

-- Gia đình & bạn bè (81 từ)
insert into public.decks (slug, name, description, level, category, position)
values ('giao-tiep-gia-dinh', 'Gia đình & bạn bè', 'Người thân, mối quan hệ, tính cách', 'beginner', 'giao-tiep', 20)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, level = excluded.level,
  category = excluded.category, position = excluded.position;

insert into public.words (deck_id, term, phonetic, meaning_vi, example_en, example_vi, position)
select d.id, w.term, w.phonetic, w.meaning_vi, w.example_en, w.example_vi, w.position
from public.decks d
join (values
  ('grandfather', '/ˈɡrænfɑːðə/', 'ông (n)', 'My grandfather is 80 years old.', 'Ông tôi 80 tuổi.', 1),
  ('grandmother', '/ˈɡrænmʌðə/', 'bà (n)', 'My grandmother makes the best soup.', 'Bà tôi nấu súp ngon nhất.', 2),
  ('grandparents', '/ˈɡrænpeərənts/', 'ông bà (n)', 'We visit our grandparents every Sunday.', 'Chúng tôi thăm ông bà mỗi Chủ nhật.', 3),
  ('husband', '/ˈhʌzbənd/', 'chồng (n)', 'Her husband is a chef.', 'Chồng cô ấy là đầu bếp.', 4),
  ('wife', '/waɪf/', 'vợ (n)', 'My wife works at a school.', 'Vợ tôi làm ở trường học.', 5),
  ('son', '/sʌn/', 'con trai (n)', 'Their son is ten.', 'Con trai họ mười tuổi.', 6),
  ('daughter', '/ˈdɔːtə/', 'con gái (n)', 'My daughter loves drawing.', 'Con gái tôi thích vẽ.', 7),
  ('brother', '/ˈbrʌðə/', 'anh/em trai (n)', 'I have two brothers.', 'Tôi có hai anh em trai.', 8),
  ('sister', '/ˈsɪstə/', 'chị/em gái (n)', 'My sister lives in Saigon.', 'Chị tôi sống ở Sài Gòn.', 9),
  ('sibling', '/ˈsɪblɪŋ/', 'anh chị em ruột (n)', 'Do you have any siblings?', 'Bạn có anh chị em không?', 10),
  ('uncle', '/ˈʌŋkl/', 'chú, bác, cậu (n)', 'My uncle lives in Canada.', 'Chú tôi sống ở Canada.', 11),
  ('aunt', '/ɑːnt/', 'cô, dì, bác gái (n)', 'My aunt is a nurse.', 'Dì tôi là y tá.', 12),
  ('cousin', '/ˈkʌzn/', 'anh chị em họ (n)', 'I have lots of cousins.', 'Tôi có nhiều anh chị em họ.', 13),
  ('nephew', '/ˈnefjuː/', 'cháu trai (n)', 'My nephew just started school.', 'Cháu trai tôi vừa đi học.', 14),
  ('niece', '/niːs/', 'cháu gái (n)', 'My niece is very cute.', 'Cháu gái tôi rất dễ thương.', 15),
  ('relative', '/ˈrelətɪv/', 'họ hàng (n)', 'All our relatives came to the wedding.', 'Tất cả họ hàng đến dự đám cưới.', 16),
  ('twin', '/twɪn/', 'sinh đôi (n)', 'They are twins.', 'Họ là anh em sinh đôi.', 17),
  ('baby', '/ˈbeɪbi/', 'em bé (n)', 'The baby is sleeping.', 'Em bé đang ngủ.', 18),
  ('teenager', '/ˈtiːneɪdʒə/', 'thiếu niên (n)', 'Teenagers love social media.', 'Thanh thiếu niên thích mạng xã hội.', 19),
  ('only child', '/ˈəʊnli tʃaɪld/', 'con một (n)', 'I''m an only child.', 'Tôi là con một.', 20),
  ('eldest', '/ˈeldɪst/', 'lớn nhất (trong nhà) (adj)', 'She is the eldest of three.', 'Cô ấy là chị cả trong ba chị em.', 21),
  ('youngest', '/ˈjʌŋɡɪst/', 'út (adj)', 'I''m the youngest in my family.', 'Tôi là con út trong nhà.', 22),
  ('close', '/kləʊs/', 'thân thiết (adj)', 'I''m very close to my mom.', 'Tôi rất thân với mẹ.', 23),
  ('get along', '/ɡet əˈlɒŋ/', 'hoà thuận', 'I get along well with my brother.', 'Tôi hoà thuận với anh trai.', 24),
  ('look after', '/lʊk ˈɑːftə/', 'chăm sóc', 'She looks after her grandmother.', 'Cô ấy chăm sóc bà.', 25),
  ('take after', '/teɪk ˈɑːftə/', 'giống (ai trong nhà)', 'He takes after his father.', 'Cậu ấy giống bố.', 26),
  ('grow up', '/ɡrəʊ ʌp/', 'lớn lên', 'I grew up in a small village.', 'Tôi lớn lên ở một ngôi làng nhỏ.', 27),
  ('bring up', '/brɪŋ ʌp/', 'nuôi dạy', 'She brought up three children alone.', 'Cô ấy một mình nuôi ba đứa con.', 28),
  ('best friend', '/best frend/', 'bạn thân nhất (n)', 'Hoa is my best friend.', 'Hoa là bạn thân nhất của tôi.', 29),
  ('classmate', '/ˈklɑːsmeɪt/', 'bạn cùng lớp (n)', 'We were classmates in high school.', 'Chúng tôi học cùng lớp thời cấp ba.', 30),
  ('roommate', '/ˈruːmmeɪt/', 'bạn cùng phòng (n)', 'My roommate is from Japan.', 'Bạn cùng phòng của tôi là người Nhật.', 31),
  ('colleague', '/ˈkɒliːɡ/', 'đồng nghiệp (n)', 'I had lunch with a colleague.', 'Tôi ăn trưa với đồng nghiệp.', 32),
  ('boyfriend', '/ˈbɔɪfrend/', 'bạn trai (n)', 'Her boyfriend is a musician.', 'Bạn trai cô ấy là nhạc sĩ.', 33),
  ('girlfriend', '/ˈɡɜːlfrend/', 'bạn gái (n)', 'He bought flowers for his girlfriend.', 'Anh ấy mua hoa cho bạn gái.', 34),
  ('partner', '/ˈpɑːtnə/', 'bạn đời, đối tác (n)', 'Bring your partner to the party.', 'Đưa bạn đời đến dự tiệc nhé.', 35),
  ('couple', '/ˈkʌpl/', 'cặp đôi (n)', 'They are a lovely couple.', 'Họ là một cặp đôi đáng yêu.', 36),
  ('date', '/deɪt/', 'buổi hẹn hò (n); hẹn hò (v)', 'We went on our first date last week.', 'Chúng tôi hẹn hò lần đầu tuần trước.', 37),
  ('fall in love', '/fɔːl ɪn lʌv/', 'yêu', 'They fell in love at university.', 'Họ yêu nhau thời đại học.', 38),
  ('engaged', '/ɪnˈɡeɪdʒd/', 'đã đính hôn (adj)', 'We got engaged in June.', 'Chúng tôi đính hôn vào tháng Sáu.', 39),
  ('wedding', '/ˈwedɪŋ/', 'đám cưới (n)', 'The wedding is next month.', 'Đám cưới vào tháng sau.', 40),
  ('anniversary', '/ˌænɪˈvɜːsəri/', 'ngày kỷ niệm (n)', 'Today is our tenth anniversary.', 'Hôm nay là kỷ niệm mười năm của chúng tôi.', 41),
  ('divorced', '/dɪˈvɔːst/', 'đã ly hôn (adj)', 'Her parents are divorced.', 'Bố mẹ cô ấy đã ly hôn.', 42),
  ('pregnant', '/ˈpreɡnənt/', 'mang thai (adj)', 'My sister is pregnant.', 'Chị tôi đang mang thai.', 43),
  ('born', '/bɔːn/', 'được sinh ra (adj)', 'I was born in 1998.', 'Tôi sinh năm 1998.', 44),
  ('funeral', '/ˈfjuːnərəl/', 'đám tang (n)', 'The funeral is on Friday.', 'Đám tang vào thứ Sáu.', 45),
  ('move house', '/muːv haʊs/', 'chuyển nhà', 'We''re moving house next week.', 'Tuần sau chúng tôi chuyển nhà.', 46),
  ('household', '/ˈhaʊshəʊld/', 'hộ gia đình (n)', 'There are five people in our household.', 'Nhà tôi có năm người.', 47),
  ('reunion', '/ˌriːˈjuːniən/', 'buổi đoàn tụ, họp mặt (n)', 'We have a family reunion every year.', 'Gia đình tôi họp mặt hằng năm.', 48),
  ('generation', '/ˌdʒenəˈreɪʃn/', 'thế hệ (n)', 'Three generations live in our house.', 'Nhà tôi có ba thế hệ cùng sống.', 49),
  ('kind', '/kaɪnd/', 'tốt bụng (adj)', 'My grandma is very kind.', 'Bà tôi rất tốt bụng.', 50),
  ('generous', '/ˈdʒenərəs/', 'hào phóng (adj)', 'He''s generous with his time.', 'Anh ấy hào phóng về thời gian.', 51),
  ('honest', '/ˈɒnɪst/', 'trung thực (adj)', 'Be honest with your friends.', 'Hãy trung thực với bạn bè.', 52),
  ('patient', '/ˈpeɪʃnt/', 'kiên nhẫn (adj)', 'Teachers must be patient.', 'Giáo viên phải kiên nhẫn.', 53),
  ('lazy', '/ˈleɪzi/', 'lười (adj)', 'My cat is so lazy.', 'Con mèo của tôi lười lắm.', 54),
  ('hard-working', '/ˌhɑːd ˈwɜːkɪŋ/', 'chăm chỉ (adj)', 'She is a hard-working student.', 'Cô ấy là học sinh chăm chỉ.', 55),
  ('funny', '/ˈfʌni/', 'hài hước (adj)', 'My uncle is really funny.', 'Chú tôi rất hài hước.', 56),
  ('serious', '/ˈsɪəriəs/', 'nghiêm túc (adj)', 'My dad is quite serious.', 'Bố tôi khá nghiêm túc.', 57),
  ('talkative', '/ˈtɔːkətɪv/', 'nói nhiều (adj)', 'My little sister is very talkative.', 'Em gái tôi nói rất nhiều.', 58),
  ('outgoing', '/ˈaʊtɡəʊɪŋ/', 'hướng ngoại (adj)', 'He''s outgoing and makes friends easily.', 'Anh ấy hướng ngoại và dễ kết bạn.', 59),
  ('confident', '/ˈkɒnfɪdənt/', 'tự tin (adj)', 'She''s confident on stage.', 'Cô ấy tự tin trên sân khấu.', 60),
  ('caring', '/ˈkeərɪŋ/', 'quan tâm, chu đáo (adj)', 'Nurses are caring people.', 'Y tá là những người chu đáo.', 61),
  ('stubborn', '/ˈstʌbən/', 'bướng bỉnh (adj)', 'My brother is stubborn.', 'Em trai tôi bướng lắm.', 62),
  ('selfish', '/ˈselfɪʃ/', 'ích kỷ (adj)', 'Don''t be selfish; share your toys.', 'Đừng ích kỷ, chia sẻ đồ chơi đi.', 63),
  ('cheerful', '/ˈtʃɪəfl/', 'vui vẻ (adj)', 'She is always cheerful in the morning.', 'Cô ấy luôn vui vẻ vào buổi sáng.', 64),
  ('sensitive', '/ˈsensətɪv/', 'nhạy cảm (adj)', 'He is sensitive to criticism.', 'Anh ấy nhạy cảm với lời phê bình.', 65),
  ('reliable', '/rɪˈlaɪəbl/', 'đáng tin cậy (adj)', 'A good friend is reliable.', 'Bạn tốt là người đáng tin cậy.', 66),
  ('personality', '/ˌpɜːsəˈnæləti/', 'tính cách (n)', 'She has a warm personality.', 'Cô ấy có tính cách ấm áp.', 67),
  ('look like', '/lʊk laɪk/', 'trông giống', 'You look like your mother.', 'Bạn trông giống mẹ.', 68),
  ('tall', '/tɔːl/', 'cao (adj)', 'My dad is tall and thin.', 'Bố tôi cao và gầy.', 69),
  ('short hair', '/ʃɔːt heə/', 'tóc ngắn (n)', 'She has short black hair.', 'Cô ấy tóc đen ngắn.', 70),
  ('curly', '/ˈkɜːli/', 'xoăn (adj)', 'My daughter has curly hair.', 'Con gái tôi tóc xoăn.', 71),
  ('glasses', '/ˈɡlɑːsɪz/', 'kính mắt (n)', 'My brother wears glasses.', 'Anh tôi đeo kính.', 72),
  ('beard', '/bɪəd/', 'râu (n)', 'My uncle has a grey beard.', 'Chú tôi có râu bạc.', 73),
  ('handsome', '/ˈhænsəm/', 'đẹp trai (adj)', 'Her husband is very handsome.', 'Chồng cô ấy rất đẹp trai.', 74),
  ('pretty', '/ˈprɪti/', 'xinh (adj)', 'Your sister is pretty.', 'Chị bạn xinh quá.', 75),
  ('housework', '/ˈhaʊswɜːk/', 'việc nhà (n)', 'We share the housework.', 'Chúng tôi chia nhau làm việc nhà.', 76),
  ('argue', '/ˈɑːɡjuː/', 'cãi nhau (v)', 'My parents rarely argue.', 'Bố mẹ tôi hiếm khi cãi nhau.', 77),
  ('hug', '/hʌɡ/', 'ôm (v, n)', 'Give your mom a hug.', 'Ôm mẹ một cái đi.', 78),
  ('miss', '/mɪs/', 'nhớ (v)', 'I miss my hometown.', 'Tôi nhớ quê.', 79),
  ('support', '/səˈpɔːt/', 'ủng hộ (v, n)', 'My family supports my dream.', 'Gia đình ủng hộ ước mơ của tôi.', 80),
  ('trust', '/trʌst/', 'tin tưởng (v, n)', 'I trust my best friend completely.', 'Tôi hoàn toàn tin tưởng bạn thân.', 81)
) as w(term, phonetic, meaning_vi, example_en, example_vi, position) on true
where d.slug = 'giao-tiep-gia-dinh'
on conflict (deck_id, term) do nothing;

-- Mua sắm & ăn uống (80 từ)
insert into public.decks (slug, name, description, level, category, position)
values ('giao-tiep-mua-sam', 'Mua sắm & ăn uống', 'Siêu thị, quán ăn, giá cả, gọi món', 'beginner', 'giao-tiep', 30)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, level = excluded.level,
  category = excluded.category, position = excluded.position;

insert into public.words (deck_id, term, phonetic, meaning_vi, example_en, example_vi, position)
select d.id, w.term, w.phonetic, w.meaning_vi, w.example_en, w.example_vi, w.position
from public.decks d
join (values
  ('supermarket', '/ˈsuːpəmɑːkɪt/', 'siêu thị (n)', 'I''m going to the supermarket.', 'Tôi đi siêu thị đây.', 1),
  ('grocery store', '/ˈɡrəʊsəri stɔː/', 'cửa hàng tạp hoá (n)', 'There''s a grocery store on the corner.', 'Có cửa hàng tạp hoá ở góc phố.', 2),
  ('shopping mall', '/ˈʃɒpɪŋ mɔːl/', 'trung tâm thương mại (n)', 'Let''s meet at the shopping mall.', 'Gặp nhau ở trung tâm thương mại nhé.', 3),
  ('convenience store', '/kənˈviːniəns stɔː/', 'cửa hàng tiện lợi (n)', 'The convenience store is open 24 hours.', 'Cửa hàng tiện lợi mở 24 giờ.', 4),
  ('bakery', '/ˈbeɪkəri/', 'tiệm bánh (n)', 'The bakery sells fresh croissants.', 'Tiệm bánh bán bánh sừng bò tươi.', 5),
  ('shopping list', '/ˈʃɒpɪŋ lɪst/', 'danh sách mua sắm (n)', 'Did you bring the shopping list?', 'Bạn mang danh sách mua sắm chưa?', 6),
  ('cart', '/kɑːt/', 'xe đẩy hàng (n)', 'Grab a cart at the entrance.', 'Lấy xe đẩy ở lối vào.', 7),
  ('basket', '/ˈbɑːskɪt/', 'giỏ (n)', 'I only need a basket today.', 'Hôm nay tôi chỉ cần cái giỏ.', 8),
  ('aisle', '/aɪl/', 'lối đi giữa các kệ (n)', 'Rice is in aisle three.', 'Gạo ở lối đi số ba.', 9),
  ('cashier', '/kæˈʃɪə/', 'thu ngân (n)', 'Pay the cashier at the front.', 'Trả tiền cho thu ngân ở phía trước.', 10),
  ('checkout', '/ˈtʃekaʊt/', 'quầy thanh toán (n)', 'There''s a long line at the checkout.', 'Quầy thanh toán đang xếp hàng dài.', 11),
  ('receipt', '/rɪˈsiːt/', 'biên lai (n)', 'Would you like a receipt?', 'Bạn có muốn lấy biên lai không?', 12),
  ('cash', '/kæʃ/', 'tiền mặt (n)', 'Do you pay by cash or card?', 'Bạn trả tiền mặt hay thẻ?', 13),
  ('credit card', '/ˈkredɪt kɑːd/', 'thẻ tín dụng (n)', 'I paid with my credit card.', 'Tôi trả bằng thẻ tín dụng.', 14),
  ('change', '/tʃeɪndʒ/', 'tiền thừa (n)', 'Here''s your change.', 'Đây là tiền thừa của bạn.', 15),
  ('how much', '/haʊ mʌtʃ/', 'bao nhiêu tiền', 'How much is this shirt?', 'Cái áo này bao nhiêu tiền?', 16),
  ('expensive', '/ɪkˈspensɪv/', 'đắt (adj)', 'That bag is too expensive.', 'Cái túi đó đắt quá.', 17),
  ('cheap', '/tʃiːp/', 'rẻ (adj)', 'The market is cheaper than the mall.', 'Chợ rẻ hơn trung tâm thương mại.', 18),
  ('on sale', '/ɒn seɪl/', 'đang giảm giá', 'These shoes are on sale.', 'Đôi giày này đang giảm giá.', 19),
  ('discount', '/ˈdɪskaʊnt/', 'giảm giá (n)', 'Can I get a discount?', 'Giảm giá cho tôi được không?', 20),
  ('bargain', '/ˈbɑːɡən/', 'mặc cả (v); món hời (n)', 'You can bargain at the market.', 'Bạn có thể mặc cả ở chợ.', 21),
  ('try on', '/traɪ ɒn/', 'mặc thử', 'Can I try this on?', 'Tôi mặc thử cái này được không?', 22),
  ('fitting room', '/ˈfɪtɪŋ ruːm/', 'phòng thử đồ (n)', 'The fitting rooms are at the back.', 'Phòng thử đồ ở phía sau.', 23),
  ('size', '/saɪz/', 'cỡ (n)', 'What size are you?', 'Bạn mặc cỡ nào?', 24),
  ('fit', '/fɪt/', 'vừa (v)', 'This jacket fits perfectly.', 'Áo khoác này vừa khít.', 25),
  ('refund', '/ˈriːfʌnd/', 'hoàn tiền (n)', 'Can I get a refund?', 'Tôi được hoàn tiền không?', 26),
  ('exchange', '/ɪksˈtʃeɪndʒ/', 'đổi hàng (v)', 'I''d like to exchange this for a smaller one.', 'Tôi muốn đổi cái này lấy cỡ nhỏ hơn.', 27),
  ('brand', '/brænd/', 'nhãn hiệu (n)', 'What brand is your phone?', 'Điện thoại bạn hiệu gì?', 28),
  ('vegetable', '/ˈvedʒtəbl/', 'rau (n)', 'Eat more vegetables.', 'Ăn nhiều rau hơn.', 29),
  ('fruit', '/fruːt/', 'trái cây (n)', 'I eat fruit every day.', 'Tôi ăn trái cây mỗi ngày.', 30),
  ('meat', '/miːt/', 'thịt (n)', 'I don''t eat much meat.', 'Tôi không ăn nhiều thịt.', 31),
  ('chicken', '/ˈtʃɪkɪn/', 'gà, thịt gà (n)', 'I''ll have the chicken, please.', 'Cho tôi món gà.', 32),
  ('beef', '/biːf/', 'thịt bò (n)', 'Pho with beef is my favorite.', 'Phở bò là món tôi thích nhất.', 33),
  ('pork', '/pɔːk/', 'thịt lợn (n)', 'This dish is made with pork.', 'Món này làm từ thịt lợn.', 34),
  ('seafood', '/ˈsiːfuːd/', 'hải sản (n)', 'Nha Trang is famous for seafood.', 'Nha Trang nổi tiếng về hải sản.', 35),
  ('egg', '/eɡ/', 'trứng (n)', 'I had two eggs for breakfast.', 'Tôi ăn hai quả trứng bữa sáng.', 36),
  ('rice', '/raɪs/', 'cơm, gạo (n)', 'We eat rice every day.', 'Chúng tôi ăn cơm mỗi ngày.', 37),
  ('noodles', '/ˈnuːdlz/', 'mì, bún, phở (n)', 'I love noodles for breakfast.', 'Tôi thích ăn bún phở bữa sáng.', 38),
  ('bread', '/bred/', 'bánh mì (n)', 'A loaf of bread, please.', 'Cho tôi một ổ bánh mì.', 39),
  ('milk', '/mɪlk/', 'sữa (n)', 'We''re out of milk.', 'Nhà hết sữa rồi.', 40),
  ('cheese', '/tʃiːz/', 'phô mai (n)', 'Extra cheese on my pizza, please.', 'Cho thêm phô mai vào pizza của tôi.', 41),
  ('sugar', '/ˈʃʊɡə/', 'đường (n)', 'No sugar in my coffee, thanks.', 'Cà phê của tôi không đường nhé.', 42),
  ('salt', '/sɔːlt/', 'muối (n)', 'Pass the salt, please.', 'Đưa tôi lọ muối với.', 43),
  ('snack', '/snæk/', 'đồ ăn vặt (n)', 'I need a snack before dinner.', 'Tôi cần ăn vặt trước bữa tối.', 44),
  ('dessert', '/dɪˈzɜːt/', 'món tráng miệng (n)', 'What''s for dessert?', 'Tráng miệng có gì?', 45),
  ('drink', '/drɪŋk/', 'đồ uống (n)', 'What would you like to drink?', 'Bạn muốn uống gì?', 46),
  ('juice', '/dʒuːs/', 'nước ép (n)', 'A glass of orange juice, please.', 'Cho tôi một ly nước cam.', 47),
  ('iced coffee', '/aɪst ˈkɒfi/', 'cà phê đá (n)', 'Vietnamese iced coffee is very strong.', 'Cà phê đá Việt Nam rất đậm.', 48),
  ('bottle of water', '/ˈbɒtl əv ˈwɔːtə/', 'chai nước', 'Can I have a bottle of water?', 'Cho tôi một chai nước.', 49),
  ('restaurant', '/ˈrestrɒnt/', 'nhà hàng (n)', 'Let''s try the new restaurant.', 'Thử nhà hàng mới đi.', 50),
  ('café', '/ˈkæfeɪ/', 'quán cà phê (n)', 'There''s a nice café near here.', 'Có quán cà phê đẹp gần đây.', 51),
  ('street food', '/striːt fuːd/', 'đồ ăn đường phố (n)', 'Hanoi street food is amazing.', 'Đồ ăn đường phố Hà Nội tuyệt vời.', 52),
  ('menu', '/ˈmenjuː/', 'thực đơn (n)', 'Can I see the menu?', 'Cho tôi xem thực đơn.', 53),
  ('order', '/ˈɔːdə/', 'gọi món (v)', 'I''d like to order now.', 'Tôi muốn gọi món bây giờ.', 54),
  ('I''d like', '/aɪd laɪk/', 'tôi muốn (lịch sự)', 'I''d like a bowl of pho, please.', 'Cho tôi một tô phở.', 55),
  ('waiter', '/ˈweɪtə/', 'nhân viên phục vụ (n)', 'Ask the waiter for the bill.', 'Hỏi phục vụ tính tiền.', 56),
  ('bill', '/bɪl/', 'hoá đơn (n)', 'The bill, please.', 'Cho tôi tính tiền.', 57),
  ('tip', '/tɪp/', 'tiền boa (n)', 'Should we leave a tip?', 'Mình có nên để lại tiền boa không?', 58),
  ('delicious', '/dɪˈlɪʃəs/', 'ngon (adj)', 'This soup is delicious!', 'Món súp này ngon quá!', 59),
  ('tasty', '/ˈteɪsti/', 'ngon miệng (adj)', 'The noodles were really tasty.', 'Mì rất ngon.', 60),
  ('spicy', '/ˈspaɪsi/', 'cay (adj)', 'Is this dish spicy?', 'Món này có cay không?', 61),
  ('sweet', '/swiːt/', 'ngọt (adj)', 'The tea is too sweet for me.', 'Trà này ngọt quá với tôi.', 62),
  ('sour', '/ˈsaʊə/', 'chua (adj)', 'Lemons are sour.', 'Chanh chua.', 63),
  ('salty', '/ˈsɔːlti/', 'mặn (adj)', 'The fish is a bit salty.', 'Cá hơi mặn.', 64),
  ('bitter', '/ˈbɪtə/', 'đắng (adj)', 'Black coffee is bitter.', 'Cà phê đen thì đắng.', 65),
  ('fresh', '/freʃ/', 'tươi (adj)', 'The vegetables are very fresh.', 'Rau rất tươi.', 66),
  ('hungry', '/ˈhʌŋɡri/', 'đói (adj)', 'I''m so hungry!', 'Tôi đói quá!', 67),
  ('thirsty', '/ˈθɜːsti/', 'khát (adj)', 'I''m thirsty; let''s get a drink.', 'Tôi khát; đi uống gì đi.', 68),
  ('full', '/fʊl/', 'no (adj)', 'No more, thanks. I''m full.', 'Thôi đủ rồi, cảm ơn. Tôi no rồi.', 69),
  ('breakfast', '/ˈbrekfəst/', 'bữa sáng (n)', 'What do you have for breakfast?', 'Bữa sáng bạn ăn gì?', 70),
  ('lunch', '/lʌntʃ/', 'bữa trưa (n)', 'Let''s have lunch together.', 'Ăn trưa cùng nhau nhé.', 71),
  ('dinner', '/ˈdɪnə/', 'bữa tối (n)', 'Dinner is at seven.', 'Bữa tối lúc bảy giờ.', 72),
  ('cook', '/kʊk/', 'nấu (v)', 'I''ll cook tonight.', 'Tối nay tôi nấu.', 73),
  ('recipe', '/ˈresəpi/', 'công thức nấu ăn (n)', 'Can I have the recipe?', 'Cho tôi xin công thức được không?', 74),
  ('boil', '/bɔɪl/', 'luộc, đun sôi (v)', 'Boil the eggs for seven minutes.', 'Luộc trứng bảy phút.', 75),
  ('fry', '/fraɪ/', 'chiên, rán (v)', 'Fry the onions until golden.', 'Phi hành đến khi vàng.', 76),
  ('grill', '/ɡrɪl/', 'nướng (v)', 'Let''s grill some fish.', 'Nướng ít cá đi.', 77),
  ('chopsticks', '/ˈtʃɒpstɪks/', 'đũa (n)', 'Can you eat with chopsticks?', 'Bạn ăn bằng đũa được không?', 78),
  ('spoon', '/spuːn/', 'cái thìa (n)', 'Could I have a spoon?', 'Cho tôi cái thìa được không?', 79),
  ('takeaway', '/ˈteɪkəweɪ/', 'đồ ăn mang về (n)', 'Let''s get a takeaway tonight.', 'Tối nay mua đồ ăn mang về đi.', 80)
) as w(term, phonetic, meaning_vi, example_en, example_vi, position) on true
where d.slug = 'giao-tiep-mua-sam'
on conflict (deck_id, term) do nothing;

-- Đi lại & hỏi đường (80 từ)
insert into public.decks (slug, name, description, level, category, position)
values ('giao-tiep-di-lai', 'Đi lại & hỏi đường', 'Phương tiện, chỉ đường, địa điểm trong thành phố', 'beginner', 'giao-tiep', 40)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, level = excluded.level,
  category = excluded.category, position = excluded.position;

insert into public.words (deck_id, term, phonetic, meaning_vi, example_en, example_vi, position)
select d.id, w.term, w.phonetic, w.meaning_vi, w.example_en, w.example_vi, w.position
from public.decks d
join (values
  ('motorbike', '/ˈməʊtəbaɪk/', 'xe máy (n)', 'I go to work by motorbike.', 'Tôi đi làm bằng xe máy.', 1),
  ('bicycle', '/ˈbaɪsɪkl/', 'xe đạp (n)', 'She rides a bicycle to school.', 'Cô ấy đạp xe đến trường.', 2),
  ('taxi', '/ˈtæksi/', 'taxi (n)', 'Let''s take a taxi; it''s raining.', 'Đi taxi đi, trời đang mưa.', 3),
  ('ride-hailing app', '/raɪd ˈheɪlɪŋ æp/', 'ứng dụng gọi xe (n)', 'I booked a car with a ride-hailing app.', 'Tôi đặt xe qua ứng dụng gọi xe.', 4),
  ('bus stop', '/bʌs stɒp/', 'trạm xe buýt (n)', 'The bus stop is across the road.', 'Trạm xe buýt ở bên kia đường.', 5),
  ('bus route', '/bʌs ruːt/', 'tuyến xe buýt (n)', 'Which bus route goes to the airport?', 'Tuyến xe buýt nào ra sân bay?', 6),
  ('metro', '/ˈmetrəʊ/', 'tàu điện (n)', 'The metro is faster than the bus.', 'Tàu điện nhanh hơn xe buýt.', 7),
  ('ticket office', '/ˈtɪkɪt ˈɒfɪs/', 'quầy vé (n)', 'Buy your ticket at the ticket office.', 'Mua vé ở quầy vé.', 8),
  ('single ticket', '/ˈsɪŋɡl ˈtɪkɪt/', 'vé một chiều (n)', 'A single ticket to the center, please.', 'Cho tôi một vé một chiều vào trung tâm.', 9),
  ('return ticket', '/rɪˈtɜːn ˈtɪkɪt/', 'vé khứ hồi (n)', 'Is a return ticket cheaper?', 'Vé khứ hồi có rẻ hơn không?', 10),
  ('get on', '/ɡet ɒn/', 'lên xe', 'Get on the bus at the front.', 'Lên xe buýt ở cửa trước.', 11),
  ('get off', '/ɡet ɒf/', 'xuống xe', 'Get off at the next stop.', 'Xuống ở trạm tiếp theo.', 12),
  ('stop', '/stɒp/', 'trạm, điểm dừng (n)', 'Which stop is the museum?', 'Bảo tàng ở trạm nào?', 13),
  ('traffic', '/ˈtræfɪk/', 'giao thông (n)', 'Traffic is terrible at 5 p.m.', 'Giao thông lúc 5 giờ chiều rất tệ.', 14),
  ('rush hour', '/rʌʃ ˈaʊə/', 'giờ cao điểm (n)', 'Avoid the roads during rush hour.', 'Tránh ra đường vào giờ cao điểm.', 15),
  ('traffic light', '/ˈtræfɪk laɪt/', 'đèn giao thông (n)', 'Turn right at the traffic lights.', 'Rẽ phải ở đèn giao thông.', 16),
  ('crossroads', '/ˈkrɒsrəʊdz/', 'ngã tư (n)', 'Go straight past the crossroads.', 'Đi thẳng qua ngã tư.', 17),
  ('roundabout', '/ˈraʊndəbaʊt/', 'vòng xuyến (n)', 'Take the second exit at the roundabout.', 'Rẽ ở lối ra thứ hai của vòng xuyến.', 18),
  ('bridge', '/brɪdʒ/', 'cây cầu (n)', 'Cross the bridge and turn left.', 'Qua cầu rồi rẽ trái.', 19),
  ('corner', '/ˈkɔːnə/', 'góc phố (n)', 'The pharmacy is on the corner.', 'Hiệu thuốc ở góc phố.', 20),
  ('block', '/blɒk/', 'dãy nhà, đoạn phố (n)', 'The bank is two blocks away.', 'Ngân hàng cách đây hai dãy nhà.', 21),
  ('sidewalk', '/ˈsaɪdwɔːk/', 'vỉa hè (n)', 'Motorbikes are parked on the sidewalk.', 'Xe máy đỗ trên vỉa hè.', 22),
  ('turn left', '/tɜːn left/', 'rẽ trái', 'Turn left at the bank.', 'Rẽ trái ở ngân hàng.', 23),
  ('turn right', '/tɜːn raɪt/', 'rẽ phải', 'Turn right after the school.', 'Rẽ phải sau trường học.', 24),
  ('go straight', '/ɡəʊ streɪt/', 'đi thẳng', 'Go straight for 200 meters.', 'Đi thẳng 200 mét.', 25),
  ('opposite', '/ˈɒpəzɪt/', 'đối diện (prep)', 'The café is opposite the post office.', 'Quán cà phê đối diện bưu điện.', 26),
  ('next to', '/nekst tuː/', 'bên cạnh', 'The hotel is next to the station.', 'Khách sạn ở cạnh nhà ga.', 27),
  ('in front of', '/ɪn frʌnt əv/', 'phía trước', 'Wait in front of the cinema.', 'Chờ ở phía trước rạp phim.', 28),
  ('on the left', '/ɒn ðə left/', 'bên trái', 'The exit is on the left.', 'Lối ra ở bên trái.', 29),
  ('on the right', '/ɒn ðə raɪt/', 'bên phải', 'You''ll see the park on the right.', 'Bạn sẽ thấy công viên bên phải.', 30),
  ('how do I get to', '/haʊ duː aɪ ɡet tuː/', 'làm sao để đến', 'How do I get to the train station?', 'Làm sao để đến ga tàu?', 31),
  ('is it far', '/ɪz ɪt fɑː/', 'có xa không', 'Is it far from here?', 'Từ đây có xa không?', 32),
  ('walking distance', '/ˈwɔːkɪŋ ˈdɪstəns/', 'khoảng cách đi bộ được', 'The beach is within walking distance.', 'Bãi biển đi bộ tới được.', 33),
  ('lost', '/lɒst/', 'lạc đường (adj)', 'I think we''re lost.', 'Tôi nghĩ chúng ta lạc đường rồi.', 34),
  ('landmark', '/ˈlændmɑːk/', 'địa danh dễ nhận biết (n)', 'Use the tower as a landmark.', 'Lấy toà tháp làm mốc.', 35),
  ('post office', '/pəʊst ˈɒfɪs/', 'bưu điện (n)', 'Is there a post office nearby?', 'Gần đây có bưu điện không?', 36),
  ('bank', '/bæŋk/', 'ngân hàng (n)', 'The bank closes at four.', 'Ngân hàng đóng cửa lúc bốn giờ.', 37),
  ('pharmacy', '/ˈfɑːməsi/', 'hiệu thuốc (n)', 'Where is the nearest pharmacy?', 'Hiệu thuốc gần nhất ở đâu?', 38),
  ('police station', '/pəˈliːs ˈsteɪʃn/', 'đồn công an (n)', 'Report it at the police station.', 'Báo ở đồn công an.', 39),
  ('library', '/ˈlaɪbrəri/', 'thư viện (n)', 'I study at the library.', 'Tôi học ở thư viện.', 40),
  ('museum', '/mjuˈziːəm/', 'bảo tàng (n)', 'The museum is closed on Mondays.', 'Bảo tàng đóng cửa thứ Hai.', 41),
  ('park', '/pɑːk/', 'công viên (n); đỗ xe (v)', 'Let''s walk in the park.', 'Đi dạo công viên nhé.', 42),
  ('cinema', '/ˈsɪnəmə/', 'rạp chiếu phim (n)', 'The cinema is on the top floor.', 'Rạp phim ở tầng trên cùng.', 43),
  ('stadium', '/ˈsteɪdiəm/', 'sân vận động (n)', 'The stadium holds 40,000 people.', 'Sân vận động chứa 40.000 người.', 44),
  ('temple', '/ˈtempl/', 'đền, chùa (n)', 'Take off your shoes at the temple.', 'Cởi giày khi vào chùa.', 45),
  ('gas station', '/ɡæs ˈsteɪʃn/', 'trạm xăng (n)', 'Stop at the gas station first.', 'Ghé trạm xăng trước đã.', 46),
  ('parking', '/ˈpɑːkɪŋ/', 'chỗ đỗ xe (n)', 'Is there parking near the restaurant?', 'Gần nhà hàng có chỗ đỗ xe không?', 47),
  ('helmet', '/ˈhelmɪt/', 'mũ bảo hiểm (n)', 'Always wear a helmet.', 'Luôn đội mũ bảo hiểm.', 48),
  ('driver', '/ˈdraɪvə/', 'tài xế (n)', 'The taxi driver was very friendly.', 'Tài xế taxi rất thân thiện.', 49),
  ('passenger', '/ˈpæsɪndʒə/', 'hành khách (n)', 'The bus was full of passengers.', 'Xe buýt đầy hành khách.', 50),
  ('seat', '/siːt/', 'chỗ ngồi (n)', 'Is this seat free?', 'Ghế này còn trống không?', 51),
  ('fare', '/feə/', 'tiền vé, cước (n)', 'The bus fare is 7,000 dong.', 'Vé xe buýt là 7.000 đồng.', 52),
  ('meter', '/ˈmiːtə/', 'đồng hồ tính cước (n)', 'Please turn on the meter.', 'Vui lòng bật đồng hồ tính cước.', 53),
  ('drop off', '/drɒp ɒf/', 'thả (ai) xuống', 'Can you drop me off at the market?', 'Bạn thả tôi ở chợ được không?', 54),
  ('pick up', '/pɪk ʌp/', 'đón', 'I''ll pick you up at eight.', 'Tôi sẽ đón bạn lúc tám giờ.', 55),
  ('on foot', '/ɒn fʊt/', 'đi bộ', 'It''s only ten minutes on foot.', 'Đi bộ chỉ mười phút thôi.', 56),
  ('hurry', '/ˈhʌri/', 'vội (v, n)', 'Hurry, the train is leaving!', 'Nhanh lên, tàu sắp chạy!', 57),
  ('late', '/leɪt/', 'trễ (adj)', 'Sorry, the bus was late.', 'Xin lỗi, xe buýt bị trễ.', 58),
  ('on time', '/ɒn taɪm/', 'đúng giờ', 'The train arrived on time.', 'Tàu đến đúng giờ.', 59),
  ('timetable', '/ˈtaɪmteɪbl/', 'bảng giờ (n)', 'Check the bus timetable online.', 'Xem bảng giờ xe buýt trên mạng.', 60),
  ('map', '/mæp/', 'bản đồ (n)', 'Open the map on your phone.', 'Mở bản đồ trên điện thoại.', 61),
  ('GPS', '/ˌdʒiː piː ˈes/', 'định vị GPS (n)', 'The GPS says turn left here.', 'GPS bảo rẽ trái ở đây.', 62),
  ('distance', '/ˈdɪstəns/', 'khoảng cách (n)', 'What''s the distance to Hue?', 'Từ đây tới Huế bao xa?', 63),
  ('kilometer', '/kɪˈlɒmɪtə/', 'ki-lô-mét (n)', 'The airport is 30 kilometers away.', 'Sân bay cách 30 ki-lô-mét.', 64),
  ('speed limit', '/spiːd ˈlɪmɪt/', 'giới hạn tốc độ (n)', 'The speed limit here is 50.', 'Giới hạn tốc độ ở đây là 50.', 65),
  ('fine', '/faɪn/', 'tiền phạt (n)', 'He got a fine for speeding.', 'Anh ấy bị phạt vì chạy quá tốc độ.', 66),
  ('accident', '/ˈæksɪdənt/', 'tai nạn (n)', 'There was an accident on the highway.', 'Có tai nạn trên cao tốc.', 67),
  ('flat tire', '/flæt ˈtaɪə/', 'xịt lốp (n)', 'I''m late because I had a flat tire.', 'Tôi muộn vì bị xịt lốp.', 68),
  ('petrol', '/ˈpetrəl/', 'xăng (n)', 'We need to buy petrol.', 'Chúng ta cần đổ xăng.', 69),
  ('trip', '/trɪp/', 'chuyến đi (n)', 'Have a safe trip!', 'Chúc chuyến đi an toàn!', 70),
  ('journey', '/ˈdʒɜːni/', 'hành trình (n)', 'The journey takes five hours.', 'Hành trình mất năm tiếng.', 71),
  ('luggage', '/ˈlʌɡɪdʒ/', 'hành lý (n)', 'Put your luggage in the back.', 'Để hành lý ở phía sau.', 72),
  ('backpack', '/ˈbækpæk/', 'ba lô (n)', 'I travel with just a backpack.', 'Tôi đi chỉ với một ba lô.', 73),
  ('tourist', '/ˈtʊərɪst/', 'khách du lịch (n)', 'The old town is full of tourists.', 'Phố cổ đầy khách du lịch.', 74),
  ('sightseeing', '/ˈsaɪtsiːɪŋ/', 'tham quan (n)', 'We went sightseeing in the afternoon.', 'Chiều chúng tôi đi tham quan.', 75),
  ('hotel', '/həʊˈtel/', 'khách sạn (n)', 'Our hotel is near the beach.', 'Khách sạn của chúng tôi gần biển.', 76),
  ('book a room', '/bʊk ə ruːm/', 'đặt phòng', 'I booked a room for two nights.', 'Tôi đặt phòng hai đêm.', 77),
  ('countryside', '/ˈkʌntrisaɪd/', 'vùng quê (n)', 'We drove through the countryside.', 'Chúng tôi lái xe qua vùng quê.', 78),
  ('beach', '/biːtʃ/', 'bãi biển (n)', 'Let''s go to the beach this weekend.', 'Cuối tuần đi biển nhé.', 79),
  ('mountain', '/ˈmaʊntən/', 'núi (n)', 'Sapa is in the mountains.', 'Sa Pa ở vùng núi.', 80)
) as w(term, phonetic, meaning_vi, example_en, example_vi, position) on true
where d.slug = 'giao-tiep-di-lai'
on conflict (deck_id, term) do nothing;

-- Sở thích & giải trí (80 từ)
insert into public.decks (slug, name, description, level, category, position)
values ('giao-tiep-so-thich', 'Sở thích & giải trí', 'Thể thao, phim, nhạc, cuối tuần', 'beginner', 'giao-tiep', 50)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, level = excluded.level,
  category = excluded.category, position = excluded.position;

insert into public.words (deck_id, term, phonetic, meaning_vi, example_en, example_vi, position)
select d.id, w.term, w.phonetic, w.meaning_vi, w.example_en, w.example_vi, w.position
from public.decks d
join (values
  ('football', '/ˈfʊtbɔːl/', 'bóng đá (n)', 'We play football every Saturday.', 'Chúng tôi đá bóng mỗi thứ Bảy.', 1),
  ('badminton', '/ˈbædmɪntən/', 'cầu lông (n)', 'Badminton is popular in Vietnam.', 'Cầu lông phổ biến ở Việt Nam.', 2),
  ('swimming', '/ˈswɪmɪŋ/', 'bơi lội (n)', 'I go swimming twice a week.', 'Tôi đi bơi hai lần một tuần.', 3),
  ('running', '/ˈrʌnɪŋ/', 'chạy bộ (n)', 'Running keeps me fit.', 'Chạy bộ giúp tôi khoẻ.', 4),
  ('gym', '/dʒɪm/', 'phòng tập (n)', 'I go to the gym after work.', 'Tôi đi tập gym sau giờ làm.', 5),
  ('yoga', '/ˈjəʊɡə/', 'yoga (n)', 'Yoga helps me relax.', 'Yoga giúp tôi thư giãn.', 6),
  ('cycling', '/ˈsaɪklɪŋ/', 'đạp xe (n)', 'Cycling by the lake is fun.', 'Đạp xe quanh hồ rất vui.', 7),
  ('hiking', '/ˈhaɪkɪŋ/', 'đi bộ đường dài (n)', 'We went hiking in Sapa.', 'Chúng tôi đi trekking ở Sa Pa.', 8),
  ('team', '/tiːm/', 'đội (n)', 'Which team do you support?', 'Bạn ủng hộ đội nào?', 9),
  ('match', '/mætʃ/', 'trận đấu (n)', 'The match starts at eight.', 'Trận đấu bắt đầu lúc tám giờ.', 10),
  ('score', '/skɔː/', 'tỉ số (n); ghi bàn (v)', 'What''s the score?', 'Tỉ số bao nhiêu rồi?', 11),
  ('fan', '/fæn/', 'người hâm mộ (n)', 'I''m a big fan of that singer.', 'Tôi là fan lớn của ca sĩ đó.', 12),
  ('music', '/ˈmjuːzɪk/', 'âm nhạc (n)', 'What music do you like?', 'Bạn thích nhạc gì?', 13),
  ('song', '/sɒŋ/', 'bài hát (n)', 'I love this song!', 'Tôi thích bài này!', 14),
  ('singer', '/ˈsɪŋə/', 'ca sĩ (n)', 'Who is your favorite singer?', 'Ca sĩ yêu thích của bạn là ai?', 15),
  ('band', '/bænd/', 'ban nhạc (n)', 'My brother plays in a band.', 'Anh tôi chơi trong một ban nhạc.', 16),
  ('concert', '/ˈkɒnsət/', 'buổi hoà nhạc (n)', 'We''re going to a concert tonight.', 'Tối nay chúng tôi đi xem hoà nhạc.', 17),
  ('guitar', '/ɡɪˈtɑː/', 'đàn ghi-ta (n)', 'I''m learning to play the guitar.', 'Tôi đang học chơi ghi-ta.', 18),
  ('piano', '/piˈænəʊ/', 'đàn piano (n)', 'She plays the piano beautifully.', 'Cô ấy chơi piano rất hay.', 19),
  ('karaoke', '/ˌkæriˈəʊki/', 'karaoke (n)', 'Let''s go to karaoke after dinner.', 'Ăn tối xong đi hát karaoke nhé.', 20),
  ('movie', '/ˈmuːvi/', 'phim (n)', 'What kind of movies do you like?', 'Bạn thích thể loại phim nào?', 21),
  ('comedy', '/ˈkɒmədi/', 'phim hài (n)', 'I prefer comedies to horror films.', 'Tôi thích phim hài hơn phim kinh dị.', 22),
  ('action film', '/ˈækʃn fɪlm/', 'phim hành động (n)', 'My dad loves action films.', 'Bố tôi mê phim hành động.', 23),
  ('cartoon', '/kɑːˈtuːn/', 'phim hoạt hình (n)', 'The kids are watching cartoons.', 'Bọn trẻ đang xem hoạt hình.', 24),
  ('series', '/ˈsɪəriːz/', 'phim bộ (n)', 'I''m watching a Korean series.', 'Tôi đang xem phim bộ Hàn Quốc.', 25),
  ('episode', '/ˈepɪsəʊd/', 'tập phim (n)', 'Did you see the last episode?', 'Bạn xem tập cuối chưa?', 26),
  ('actor', '/ˈæktə/', 'diễn viên (n)', 'He''s a famous actor.', 'Anh ấy là diễn viên nổi tiếng.', 27),
  ('book', '/bʊk/', 'sách (n)', 'I''m reading a great book.', 'Tôi đang đọc một cuốn sách hay.', 28),
  ('novel', '/ˈnɒvl/', 'tiểu thuyết (n)', 'This novel is very long.', 'Cuốn tiểu thuyết này rất dài.', 29),
  ('comic', '/ˈkɒmɪk/', 'truyện tranh (n)', 'I collected comics as a kid.', 'Hồi nhỏ tôi sưu tầm truyện tranh.', 30),
  ('magazine', '/ˌmæɡəˈziːn/', 'tạp chí (n)', 'She reads fashion magazines.', 'Cô ấy đọc tạp chí thời trang.', 31),
  ('video game', '/ˈvɪdiəʊ ɡeɪm/', 'trò chơi điện tử (n)', 'He plays video games all weekend.', 'Anh ấy chơi game cả cuối tuần.', 32),
  ('board game', '/bɔːd ɡeɪm/', 'trò chơi bàn cờ (n)', 'Let''s play a board game.', 'Chơi board game nào.', 33),
  ('chess', '/tʃes/', 'cờ vua (n)', 'My grandpa taught me chess.', 'Ông dạy tôi chơi cờ vua.', 34),
  ('photography', '/fəˈtɒɡrəfi/', 'nhiếp ảnh (n)', 'Photography is my hobby.', 'Nhiếp ảnh là sở thích của tôi.', 35),
  ('painting', '/ˈpeɪntɪŋ/', 'hội hoạ, bức tranh (n)', 'I do painting on weekends.', 'Cuối tuần tôi vẽ tranh.', 36),
  ('drawing', '/ˈdrɔːɪŋ/', 'vẽ (n)', 'She''s good at drawing.', 'Cô ấy vẽ giỏi.', 37),
  ('cooking', '/ˈkʊkɪŋ/', 'nấu ăn (n)', 'I enjoy cooking for friends.', 'Tôi thích nấu ăn cho bạn bè.', 38),
  ('gardening', '/ˈɡɑːdnɪŋ/', 'làm vườn (n)', 'My mom loves gardening.', 'Mẹ tôi thích làm vườn.', 39),
  ('fishing', '/ˈfɪʃɪŋ/', 'câu cá (n)', 'We go fishing at the lake.', 'Chúng tôi đi câu ở hồ.', 40),
  ('camping', '/ˈkæmpɪŋ/', 'cắm trại (n)', 'Let''s go camping this summer.', 'Hè này đi cắm trại nhé.', 41),
  ('travel', '/ˈtrævl/', 'du lịch (v, n)', 'I want to travel to Japan.', 'Tôi muốn đi Nhật.', 42),
  ('shopping', '/ˈʃɒpɪŋ/', 'mua sắm (n)', 'She loves shopping.', 'Cô ấy mê mua sắm.', 43),
  ('dancing', '/ˈdɑːnsɪŋ/', 'khiêu vũ, nhảy (n)', 'Dancing is great exercise.', 'Nhảy là bài tập tuyệt vời.', 44),
  ('social media', '/ˈsəʊʃl ˈmiːdiə/', 'mạng xã hội (n)', 'I spend too much time on social media.', 'Tôi tốn quá nhiều thời gian cho mạng xã hội.', 45),
  ('hang out', '/hæŋ aʊt/', 'đi chơi, tụ tập', 'Let''s hang out this weekend.', 'Cuối tuần đi chơi nhé.', 46),
  ('weekend', '/ˌwiːkˈend/', 'cuối tuần (n)', 'What are you doing this weekend?', 'Cuối tuần này bạn làm gì?', 47),
  ('party', '/ˈpɑːti/', 'bữa tiệc (n)', 'Are you coming to the party?', 'Bạn có đến bữa tiệc không?', 48),
  ('invite', '/ɪnˈvaɪt/', 'mời (v)', 'I''d like to invite you to dinner.', 'Tôi muốn mời bạn ăn tối.', 49),
  ('would you like to', '/wʊd juː laɪk tuː/', 'bạn có muốn... không', 'Would you like to see a movie?', 'Bạn có muốn đi xem phim không?', 50),
  ('I''d love to', '/aɪd lʌv tuː/', 'tôi rất thích', 'Come for coffee? — I''d love to!', 'Đi cà phê không? — Thích quá!', 51),
  ('sorry, I can''t', '/ˈsɒri aɪ kɑːnt/', 'xin lỗi, tôi không thể', 'Sorry, I can''t. I''m busy tonight.', 'Xin lỗi, tôi không đi được. Tối nay tôi bận.', 52),
  ('maybe next time', '/ˈmeɪbi nekst taɪm/', 'để lần sau nhé', 'I''m tired today. Maybe next time.', 'Hôm nay tôi mệt. Để lần sau nhé.', 53),
  ('free', '/friː/', 'rảnh (adj)', 'Are you free on Sunday?', 'Chủ nhật bạn rảnh không?', 54),
  ('busy', '/ˈbɪzi/', 'bận (adj)', 'I''m busy all week.', 'Cả tuần tôi bận.', 55),
  ('plan', '/plæn/', 'kế hoạch (n)', 'Do you have any plans tonight?', 'Tối nay bạn có kế hoạch gì không?', 56),
  ('interested in', '/ˈɪntrəstɪd ɪn/', 'quan tâm, hứng thú với', 'I''m interested in history.', 'Tôi hứng thú với lịch sử.', 57),
  ('keen on', '/kiːn ɒn/', 'thích, mê', 'He''s keen on football.', 'Anh ấy mê bóng đá.', 58),
  ('crazy about', '/ˈkreɪzi əˈbaʊt/', 'phát cuồng vì', 'She''s crazy about K-pop.', 'Cô ấy phát cuồng vì K-pop.', 59),
  ('can''t stand', '/kɑːnt stænd/', 'không chịu nổi', 'I can''t stand horror movies.', 'Tôi không chịu nổi phim kinh dị.', 60),
  ('favorite', '/ˈfeɪvərɪt/', 'yêu thích nhất (adj)', 'What''s your favorite sport?', 'Môn thể thao bạn thích nhất là gì?', 61),
  ('boring', '/ˈbɔːrɪŋ/', 'chán (adj)', 'The film was really boring.', 'Bộ phim chán thật.', 62),
  ('exciting', '/ɪkˈsaɪtɪŋ/', 'hào hứng, thú vị (adj)', 'The match was so exciting!', 'Trận đấu hấp dẫn quá!', 63),
  ('relaxing', '/rɪˈlæksɪŋ/', 'thư giãn (adj)', 'Reading is relaxing.', 'Đọc sách rất thư giãn.', 64),
  ('fun', '/fʌn/', 'vui (adj, n)', 'The party was fun.', 'Bữa tiệc rất vui.', 65),
  ('pastime', '/ˈpɑːstaɪm/', 'thú tiêu khiển (n)', 'Fishing is a popular pastime here.', 'Câu cá là thú tiêu khiển phổ biến ở đây.', 66),
  ('collect', '/kəˈlekt/', 'sưu tầm (v)', 'I collect old coins.', 'Tôi sưu tầm tiền xu cổ.', 67),
  ('practice', '/ˈpræktɪs/', 'luyện tập (v)', 'I practice guitar every evening.', 'Tôi tập ghi-ta mỗi tối.', 68),
  ('join a club', '/dʒɔɪn ə klʌb/', 'tham gia câu lạc bộ', 'I joined a chess club.', 'Tôi tham gia câu lạc bộ cờ vua.', 69),
  ('member', '/ˈmembə/', 'thành viên (n)', 'I''m a member of the gym.', 'Tôi là hội viên phòng gym.', 70),
  ('ticket', '/ˈtɪkɪt/', 'vé (n)', 'I got two tickets for the show.', 'Tôi có hai vé xem buổi diễn.', 71),
  ('festival', '/ˈfestɪvl/', 'lễ hội (n)', 'There''s a music festival in July.', 'Có lễ hội âm nhạc vào tháng Bảy.', 72),
  ('picnic', '/ˈpɪknɪk/', 'dã ngoại (n)', 'Let''s have a picnic in the park.', 'Đi dã ngoại ở công viên nhé.', 73),
  ('photo', '/ˈfəʊtəʊ/', 'ảnh (n)', 'Let''s take a photo together.', 'Chụp ảnh chung nào.', 74),
  ('selfie', '/ˈselfi/', 'ảnh tự chụp (n)', 'She takes selfies everywhere.', 'Cô ấy chụp selfie khắp nơi.', 75),
  ('podcast', '/ˈpɒdkɑːst/', 'podcast (n)', 'I listen to podcasts on the bus.', 'Tôi nghe podcast trên xe buýt.', 76),
  ('headphones', '/ˈhedfəʊnz/', 'tai nghe (n)', 'I forgot my headphones.', 'Tôi quên tai nghe rồi.', 77),
  ('stay up late', '/steɪ ʌp leɪt/', 'thức khuya', 'I stayed up late watching a series.', 'Tôi thức khuya xem phim bộ.', 78),
  ('have a good time', '/hæv ə ɡʊd taɪm/', 'vui vẻ, tận hưởng', 'Have a good time at the concert!', 'Chúc bạn xem hoà nhạc vui vẻ!', 79),
  ('can''t wait', '/kɑːnt weɪt/', 'nóng lòng mong đợi', 'I can''t wait for the weekend!', 'Tôi nóng lòng chờ cuối tuần!', 80)
) as w(term, phonetic, meaning_vi, example_en, example_vi, position) on true
where d.slug = 'giao-tiep-so-thich'
on conflict (deck_id, term) do nothing;

-- Sức khoẻ & cảm xúc (80 từ)
insert into public.decks (slug, name, description, level, category, position)
values ('giao-tiep-suc-khoe', 'Sức khoẻ & cảm xúc', 'Cơ thể, ốm đau, cảm giác, thói quen', 'beginner', 'giao-tiep', 60)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, level = excluded.level,
  category = excluded.category, position = excluded.position;

insert into public.words (deck_id, term, phonetic, meaning_vi, example_en, example_vi, position)
select d.id, w.term, w.phonetic, w.meaning_vi, w.example_en, w.example_vi, w.position
from public.decks d
join (values
  ('head', '/hed/', 'đầu (n)', 'My head hurts.', 'Đầu tôi đau.', 1),
  ('stomach', '/ˈstʌmək/', 'bụng, dạ dày (n)', 'I have a stomach ache.', 'Tôi bị đau bụng.', 2),
  ('throat', '/θrəʊt/', 'cổ họng (n)', 'I have a sore throat.', 'Tôi bị đau họng.', 3),
  ('back', '/bæk/', 'lưng (n)', 'My back aches from sitting all day.', 'Lưng tôi đau vì ngồi cả ngày.', 4),
  ('arm', '/ɑːm/', 'cánh tay (n)', 'He broke his arm playing football.', 'Anh ấy gãy tay khi đá bóng.', 5),
  ('leg', '/leɡ/', 'chân (n)', 'My legs are tired after the hike.', 'Chân tôi mỏi sau chuyến đi bộ.', 6),
  ('knee', '/niː/', 'đầu gối (n)', 'I hurt my knee.', 'Tôi bị đau đầu gối.', 7),
  ('tooth', '/tuːθ/', 'răng (n)', 'I have a bad tooth.', 'Tôi có một cái răng hỏng.', 8),
  ('skin', '/skɪn/', 'da (n)', 'My skin is dry.', 'Da tôi khô.', 9),
  ('sick', '/sɪk/', 'ốm (adj)', 'I feel sick today.', 'Hôm nay tôi thấy không khoẻ.', 10),
  ('fever', '/ˈfiːvə/', 'sốt (n)', 'She has a high fever.', 'Cô ấy sốt cao.', 11),
  ('cold', '/kəʊld/', 'cảm lạnh (n)', 'I''ve caught a cold.', 'Tôi bị cảm lạnh.', 12),
  ('flu', '/fluː/', 'cúm (n)', 'Half the class has the flu.', 'Nửa lớp bị cúm.', 13),
  ('cough', '/kɒf/', 'ho (n, v)', 'I''ve had a cough for a week.', 'Tôi ho cả tuần rồi.', 14),
  ('headache', '/ˈhedeɪk/', 'đau đầu (n)', 'I have a terrible headache.', 'Tôi đau đầu kinh khủng.', 15),
  ('runny nose', '/ˈrʌni nəʊz/', 'sổ mũi (n)', 'I have a runny nose and a cough.', 'Tôi bị sổ mũi và ho.', 16),
  ('sore', '/sɔː/', 'đau, nhức (adj)', 'My eyes are sore.', 'Mắt tôi nhức.', 17),
  ('pain', '/peɪn/', 'cơn đau (n)', 'I have a pain in my chest.', 'Tôi bị đau ngực.', 18),
  ('dizzy', '/ˈdɪzi/', 'chóng mặt (adj)', 'I feel dizzy when I stand up.', 'Tôi chóng mặt khi đứng dậy.', 19),
  ('tired', '/ˈtaɪəd/', 'mệt (adj)', 'I''m tired all the time.', 'Lúc nào tôi cũng thấy mệt.', 20),
  ('allergy', '/ˈælədʒi/', 'dị ứng (n)', 'I have a seafood allergy.', 'Tôi dị ứng hải sản.', 21),
  ('injury', '/ˈɪndʒəri/', 'chấn thương (n)', 'It''s a minor injury.', 'Đó là chấn thương nhẹ.', 22),
  ('doctor', '/ˈdɒktə/', 'bác sĩ (n)', 'I need to see a doctor.', 'Tôi cần đi khám bác sĩ.', 23),
  ('dentist', '/ˈdentɪst/', 'nha sĩ (n)', 'I have a dentist appointment tomorrow.', 'Mai tôi có hẹn nha sĩ.', 24),
  ('nurse', '/nɜːs/', 'y tá (n)', 'The nurse took my temperature.', 'Y tá đo nhiệt độ cho tôi.', 25),
  ('hospital', '/ˈhɒspɪtl/', 'bệnh viện (n)', 'He''s in hospital.', 'Anh ấy đang nằm viện.', 26),
  ('medicine', '/ˈmedsn/', 'thuốc (n)', 'Take this medicine after meals.', 'Uống thuốc này sau bữa ăn.', 27),
  ('pill', '/pɪl/', 'viên thuốc (n)', 'Take two pills a day.', 'Uống hai viên mỗi ngày.', 28),
  ('painkiller', '/ˈpeɪnkɪlə/', 'thuốc giảm đau (n)', 'Do you have any painkillers?', 'Bạn có thuốc giảm đau không?', 29),
  ('prescription', '/prɪˈskrɪpʃn/', 'đơn thuốc (n)', 'The doctor gave me a prescription.', 'Bác sĩ kê đơn cho tôi.', 30),
  ('check-up', '/ˈtʃek ʌp/', 'khám sức khoẻ (n)', 'I have a check-up every year.', 'Tôi khám sức khoẻ hằng năm.', 31),
  ('temperature', '/ˈtemprətʃə/', 'nhiệt độ (cơ thể) (n)', 'Let me take your temperature.', 'Để tôi đo nhiệt độ cho bạn.', 32),
  ('blood pressure', '/blʌd ˈpreʃə/', 'huyết áp (n)', 'My blood pressure is a bit high.', 'Huyết áp tôi hơi cao.', 33),
  ('rest', '/rest/', 'nghỉ ngơi (v, n)', 'You need to rest for a few days.', 'Bạn cần nghỉ vài ngày.', 34),
  ('get better', '/ɡet ˈbetə/', 'khoẻ lại', 'I hope you get better soon.', 'Mong bạn sớm khoẻ lại.', 35),
  ('recover', '/rɪˈkʌvə/', 'hồi phục (v)', 'He recovered quickly.', 'Anh ấy hồi phục nhanh.', 36),
  ('healthy', '/ˈhelθi/', 'khoẻ mạnh (adj)', 'Stay healthy!', 'Giữ gìn sức khoẻ nhé!', 37),
  ('unhealthy', '/ʌnˈhelθi/', 'không lành mạnh (adj)', 'Fast food is unhealthy.', 'Đồ ăn nhanh không lành mạnh.', 38),
  ('diet', '/ˈdaɪət/', 'chế độ ăn; ăn kiêng (n)', 'I''m on a diet.', 'Tôi đang ăn kiêng.', 39),
  ('exercise', '/ˈeksəsaɪz/', 'tập thể dục (v, n)', 'I exercise every morning.', 'Tôi tập thể dục mỗi sáng.', 40),
  ('lose weight', '/luːz weɪt/', 'giảm cân', 'I want to lose weight.', 'Tôi muốn giảm cân.', 41),
  ('gain weight', '/ɡeɪn weɪt/', 'tăng cân', 'I gained weight over Tet.', 'Tôi tăng cân sau Tết.', 42),
  ('sleep', '/sliːp/', 'ngủ (v, n)', 'Did you sleep well?', 'Bạn ngủ ngon không?', 43),
  ('wake up', '/weɪk ʌp/', 'thức dậy', 'I wake up at six.', 'Tôi thức dậy lúc sáu giờ.', 44),
  ('get up', '/ɡet ʌp/', 'ra khỏi giường, dậy', 'I get up late on Sundays.', 'Chủ nhật tôi dậy muộn.', 45),
  ('brush your teeth', '/brʌʃ jɔː tiːθ/', 'đánh răng', 'Brush your teeth twice a day.', 'Đánh răng hai lần mỗi ngày.', 46),
  ('take a shower', '/teɪk ə ˈʃaʊə/', 'tắm', 'I take a shower before bed.', 'Tôi tắm trước khi ngủ.', 47),
  ('routine', '/ruːˈtiːn/', 'thói quen hằng ngày (n)', 'What''s your morning routine?', 'Buổi sáng bạn thường làm gì?', 48),
  ('stress', '/stres/', 'căng thẳng (n)', 'I''m under a lot of stress.', 'Tôi đang rất căng thẳng.', 49),
  ('stressed', '/strest/', 'bị căng thẳng (adj)', 'I feel stressed about exams.', 'Tôi căng thẳng vì thi cử.', 50),
  ('relax', '/rɪˈlæks/', 'thư giãn (v)', 'Relax and take a deep breath.', 'Thư giãn và hít thở sâu.', 51),
  ('happy', '/ˈhæpi/', 'vui, hạnh phúc (adj)', 'I''m so happy for you!', 'Tôi mừng cho bạn quá!', 52),
  ('sad', '/sæd/', 'buồn (adj)', 'Why do you look so sad?', 'Sao bạn trông buồn thế?', 53),
  ('angry', '/ˈæŋɡri/', 'tức giận (adj)', 'Don''t be angry with me.', 'Đừng giận tôi.', 54),
  ('upset', '/ʌpˈset/', 'buồn bực (adj)', 'She''s upset about the news.', 'Cô ấy buồn vì tin đó.', 55),
  ('worried', '/ˈwʌrid/', 'lo lắng (adj)', 'I''m worried about my exam.', 'Tôi lo về kỳ thi.', 56),
  ('scared', '/skeəd/', 'sợ (adj)', 'I''m scared of dogs.', 'Tôi sợ chó.', 57),
  ('nervous', '/ˈnɜːvəs/', 'hồi hộp (adj)', 'I''m nervous before the interview.', 'Tôi hồi hộp trước buổi phỏng vấn.', 58),
  ('excited', '/ɪkˈsaɪtɪd/', 'háo hức (adj)', 'I''m excited about the trip.', 'Tôi háo hức về chuyến đi.', 59),
  ('bored', '/bɔːd/', 'chán (adj)', 'I''m bored. Let''s do something.', 'Tôi chán quá. Làm gì đó đi.', 60),
  ('surprised', '/səˈpraɪzd/', 'ngạc nhiên (adj)', 'I was surprised to see you here.', 'Tôi ngạc nhiên khi gặp bạn ở đây.', 61),
  ('proud', '/praʊd/', 'tự hào (adj)', 'My parents are proud of me.', 'Bố mẹ tự hào về tôi.', 62),
  ('lonely', '/ˈləʊnli/', 'cô đơn (adj)', 'I felt lonely in the new city.', 'Tôi thấy cô đơn ở thành phố mới.', 63),
  ('calm', '/kɑːm/', 'bình tĩnh (adj)', 'Stay calm and think.', 'Bình tĩnh và suy nghĩ.', 64),
  ('comfortable', '/ˈkʌmftəbl/', 'thoải mái (adj)', 'This chair is comfortable.', 'Ghế này thoải mái.', 65),
  ('appetite', '/ˈæpɪtaɪt/', 'cảm giác thèm ăn (n)', 'I''ve lost my appetite.', 'Tôi chẳng thấy thèm ăn.', 66),
  ('sleepy', '/ˈsliːpi/', 'buồn ngủ (adj)', 'I''m sleepy after lunch.', 'Ăn trưa xong tôi buồn ngủ.', 67),
  ('feel', '/fiːl/', 'cảm thấy (v)', 'How do you feel today?', 'Hôm nay bạn thấy thế nào?', 68),
  ('mood', '/muːd/', 'tâm trạng (n)', 'I''m in a good mood today.', 'Hôm nay tâm trạng tôi tốt.', 69),
  ('cheer up', '/tʃɪər ʌp/', 'vui lên', 'Cheer up! It''s not so bad.', 'Vui lên! Không tệ đến thế đâu.', 70),
  ('calm down', '/kɑːm daʊn/', 'bình tĩnh lại', 'Calm down and tell me what happened.', 'Bình tĩnh và kể tôi nghe chuyện gì.', 71),
  ('take it easy', '/teɪk ɪt ˈiːzi/', 'cứ từ từ, thư thả', 'Take it easy this weekend.', 'Cuối tuần này thư thả nhé.', 72),
  ('get well soon', '/ɡet wel suːn/', 'chóng khoẻ nhé', 'Get well soon, Mai!', 'Chóng khoẻ nhé, Mai!', 73),
  ('what''s wrong', '/wɒts rɒŋ/', 'có chuyện gì vậy', 'What''s wrong? You look pale.', 'Có chuyện gì thế? Trông bạn nhợt nhạt.', 74),
  ('I don''t feel well', '/aɪ dəʊnt fiːl wel/', 'tôi thấy không khoẻ', 'I don''t feel well; I''m going home.', 'Tôi thấy không khoẻ, tôi về nhà đây.', 75),
  ('mask', '/mɑːsk/', 'khẩu trang (n)', 'Wear a mask on the bus.', 'Đeo khẩu trang trên xe buýt.', 76),
  ('wash your hands', '/wɒʃ jɔː hændz/', 'rửa tay', 'Wash your hands before eating.', 'Rửa tay trước khi ăn.', 77),
  ('vitamin', '/ˈvɪtəmɪn/', 'vitamin (n)', 'Oranges are full of vitamin C.', 'Cam chứa nhiều vitamin C.', 78),
  ('water', '/ˈwɔːtə/', 'nước (n)', 'Drink two liters of water a day.', 'Uống hai lít nước mỗi ngày.', 79),
  ('in shape', '/ɪn ʃeɪp/', 'có thể lực tốt', 'I want to get in shape before summer.', 'Tôi muốn lấy lại vóc dáng trước mùa hè.', 80)
) as w(term, phonetic, meaning_vi, example_en, example_vi, position) on true
where d.slug = 'giao-tiep-suc-khoe'
on conflict (deck_id, term) do nothing;
