-- DailyEng — seed nhóm "hoc-thuat". SINH TỰ ĐỘNG bởi scripts/generate-decks.mts, đừng sửa tay.
-- Chạy SAU schema-07-nhom-bo-tu.sql. Chạy lại nhiều lần được: bộ đã có thì cập nhật tên/mô tả,
-- từ đã có (deck_id, term) thì giữ nguyên để không mất tiến độ học của người dùng.

-- Nghiên cứu & phương pháp (100 từ)
insert into public.decks (slug, name, description, level, category, position)
values ('hoc-thuat-nghien-cuu', 'Nghiên cứu & phương pháp', 'Giả thuyết, dữ liệu, phân tích, kết luận', 'advanced', 'hoc-thuat', 10)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, level = excluded.level,
  category = excluded.category, position = excluded.position;

insert into public.words (deck_id, term, phonetic, meaning_vi, example_en, example_vi, position)
select d.id, w.term, w.phonetic, w.meaning_vi, w.example_en, w.example_vi, w.position
from public.decks d
join (values
  ('research', '/rɪˈsɜːtʃ/', 'nghiên cứu (n, v)', 'Her research focuses on renewable energy.', 'Nghiên cứu của cô ấy tập trung vào năng lượng tái tạo.', 1),
  ('hypothesis', '/haɪˈpɒθəsɪs/', 'giả thuyết (n)', 'The data did not support the hypothesis.', 'Dữ liệu không ủng hộ giả thuyết.', 2),
  ('methodology', '/ˌmeθəˈdɒlədʒi/', 'phương pháp luận (n)', 'The methodology is described in chapter three.', 'Phương pháp luận được mô tả ở chương ba.', 3),
  ('method', '/ˈmeθəd/', 'phương pháp (n)', 'We used a mixed-methods approach.', 'Chúng tôi dùng cách tiếp cận hỗn hợp phương pháp.', 4),
  ('approach', '/əˈprəʊtʃ/', 'cách tiếp cận (n)', 'A qualitative approach was adopted.', 'Cách tiếp cận định tính đã được áp dụng.', 5),
  ('data', '/ˈdeɪtə/', 'dữ liệu (n)', 'The data were collected over six months.', 'Dữ liệu được thu thập trong sáu tháng.', 6),
  ('collect', '/kəˈlekt/', 'thu thập (v)', 'We collected responses from 300 students.', 'Chúng tôi thu thập phản hồi từ 300 sinh viên.', 7),
  ('sample', '/ˈsɑːmpl/', 'mẫu (n)', 'The sample consisted of 120 participants.', 'Mẫu gồm 120 người tham gia.', 8),
  ('participant', '/pɑːˈtɪsɪpənt/', 'người tham gia (n)', 'Each participant completed a survey.', 'Mỗi người tham gia hoàn thành một khảo sát.', 9),
  ('survey', '/ˈsɜːveɪ/', 'khảo sát (n, v)', 'The survey was conducted online.', 'Khảo sát được thực hiện trực tuyến.', 10),
  ('questionnaire', '/ˌkwestʃəˈneə/', 'bảng câu hỏi (n)', 'The questionnaire had 25 items.', 'Bảng câu hỏi có 25 mục.', 11),
  ('interview', '/ˈɪntəvjuː/', 'phỏng vấn (n, v)', 'We interviewed ten teachers.', 'Chúng tôi phỏng vấn mười giáo viên.', 12),
  ('experiment', '/ɪkˈsperɪmənt/', 'thí nghiệm (n)', 'The experiment was repeated three times.', 'Thí nghiệm được lặp lại ba lần.', 13),
  ('observation', '/ˌɒbzəˈveɪʃn/', 'quan sát (n)', 'Classroom observations lasted two weeks.', 'Quan sát lớp học kéo dài hai tuần.', 14),
  ('variable', '/ˈveəriəbl/', 'biến số (n)', 'Age was treated as a control variable.', 'Tuổi được xem là biến kiểm soát.', 15),
  ('independent variable', '/ˌɪndɪˈpendənt ˈveəriəbl/', 'biến độc lập (n)', 'The independent variable was study time.', 'Biến độc lập là thời gian học.', 16),
  ('dependent variable', '/dɪˈpendənt ˈveəriəbl/', 'biến phụ thuộc (n)', 'Test scores were the dependent variable.', 'Điểm bài kiểm tra là biến phụ thuộc.', 17),
  ('control group', '/kənˈtrəʊl ɡruːp/', 'nhóm đối chứng (n)', 'The control group received no training.', 'Nhóm đối chứng không được huấn luyện.', 18),
  ('analysis', '/əˈnæləsɪs/', 'phân tích (n)', 'Statistical analysis revealed a strong link.', 'Phân tích thống kê cho thấy mối liên hệ mạnh.', 19),
  ('analyse', '/ˈænəlaɪz/', 'phân tích (v)', 'We analysed the results using software.', 'Chúng tôi phân tích kết quả bằng phần mềm.', 20),
  ('evidence', '/ˈevɪdəns/', 'bằng chứng (n)', 'There is little evidence for this claim.', 'Có rất ít bằng chứng cho khẳng định này.', 21),
  ('finding', '/ˈfaɪndɪŋ/', 'phát hiện, kết quả nghiên cứu (n)', 'The findings suggest a need for change.', 'Các phát hiện cho thấy cần thay đổi.', 22),
  ('result', '/rɪˈzʌlt/', 'kết quả (n)', 'The results are shown in Table 2.', 'Kết quả được trình bày ở Bảng 2.', 23),
  ('conclusion', '/kənˈkluːʒn/', 'kết luận (n)', 'The conclusion summarises the key points.', 'Kết luận tóm tắt các điểm chính.', 24),
  ('conclude', '/kənˈkluːd/', 'kết luận (v)', 'We conclude that the method is effective.', 'Chúng tôi kết luận phương pháp này hiệu quả.', 25),
  ('literature review', '/ˈlɪtrətʃə rɪˈvjuː/', 'tổng quan tài liệu (n)', 'The literature review covers 50 studies.', 'Tổng quan tài liệu bao quát 50 nghiên cứu.', 26),
  ('citation', '/saɪˈteɪʃn/', 'trích dẫn (n)', 'Every claim needs a citation.', 'Mọi khẳng định đều cần trích dẫn.', 27),
  ('cite', '/saɪt/', 'trích dẫn (v)', 'Cite your sources correctly.', 'Trích dẫn nguồn cho đúng.', 28),
  ('reference', '/ˈrefrəns/', 'tài liệu tham khảo (n)', 'The reference list is in APA style.', 'Danh mục tham khảo theo chuẩn APA.', 29),
  ('source', '/sɔːs/', 'nguồn (n)', 'Use reliable sources only.', 'Chỉ dùng nguồn đáng tin cậy.', 30),
  ('abstract', '/ˈæbstrækt/', 'tóm tắt bài báo (n)', 'The abstract is limited to 250 words.', 'Phần tóm tắt giới hạn 250 từ.', 31),
  ('journal', '/ˈdʒɜːnl/', 'tạp chí khoa học (n)', 'The paper appeared in a peer-reviewed journal.', 'Bài báo đăng trên tạp chí có bình duyệt.', 32),
  ('peer review', '/pɪə rɪˈvjuː/', 'bình duyệt (n)', 'Peer review improves the quality of research.', 'Bình duyệt nâng chất lượng nghiên cứu.', 33),
  ('publish', '/ˈpʌblɪʃ/', 'xuất bản, công bố (v)', 'The study was published in 2023.', 'Nghiên cứu được công bố năm 2023.', 34),
  ('author', '/ˈɔːθə/', 'tác giả (n)', 'The authors thank the funding agency.', 'Các tác giả cảm ơn cơ quan tài trợ.', 35),
  ('theory', '/ˈθɪəri/', 'lý thuyết (n)', 'The study is based on social learning theory.', 'Nghiên cứu dựa trên lý thuyết học tập xã hội.', 36),
  ('framework', '/ˈfreɪmwɜːk/', 'khung lý thuyết (n)', 'We propose a new conceptual framework.', 'Chúng tôi đề xuất một khung khái niệm mới.', 37),
  ('concept', '/ˈkɒnsept/', 'khái niệm (n)', 'The concept of motivation is central here.', 'Khái niệm động lực là trọng tâm ở đây.', 38),
  ('define', '/dɪˈfaɪn/', 'định nghĩa (v)', 'First, we define the key terms.', 'Trước hết, chúng tôi định nghĩa các thuật ngữ chính.', 39),
  ('definition', '/ˌdefɪˈnɪʃn/', 'định nghĩa (n)', 'There is no single definition of success.', 'Không có một định nghĩa duy nhất về thành công.', 40),
  ('objective', '/əbˈdʒektɪv/', 'mục tiêu nghiên cứu (n); khách quan (adj)', 'The main objective is to measure impact.', 'Mục tiêu chính là đo lường tác động.', 41),
  ('scope', '/skəʊp/', 'phạm vi (n)', 'This topic is beyond the scope of the paper.', 'Chủ đề này nằm ngoài phạm vi bài báo.', 42),
  ('limitation', '/ˌlɪmɪˈteɪʃn/', 'hạn chế (n)', 'A limitation is the small sample size.', 'Một hạn chế là cỡ mẫu nhỏ.', 43),
  ('significant', '/sɪɡˈnɪfɪkənt/', 'có ý nghĩa (thống kê), đáng kể (adj)', 'The difference was statistically significant.', 'Sự khác biệt có ý nghĩa thống kê.', 44),
  ('correlation', '/ˌkɒrəˈleɪʃn/', 'tương quan (n)', 'There is a positive correlation between the two.', 'Có tương quan dương giữa hai yếu tố.', 45),
  ('causation', '/kɔːˈzeɪʃn/', 'quan hệ nhân quả (n)', 'Correlation does not imply causation.', 'Tương quan không có nghĩa là nhân quả.', 46),
  ('factor', '/ˈfæktə/', 'yếu tố (n)', 'Several factors affect performance.', 'Nhiều yếu tố ảnh hưởng đến kết quả.', 47),
  ('impact', '/ˈɪmpækt/', 'tác động (n)', 'We examined the impact of sleep on memory.', 'Chúng tôi xem xét tác động của giấc ngủ lên trí nhớ.', 48),
  ('influence', '/ˈɪnfluəns/', 'ảnh hưởng (n, v)', 'Culture influences learning styles.', 'Văn hoá ảnh hưởng đến phong cách học.', 49),
  ('measure', '/ˈmeʒə/', 'đo lường (v); thước đo (n)', 'How do you measure motivation?', 'Bạn đo lường động lực thế nào?', 50),
  ('assess', '/əˈses/', 'đánh giá (v)', 'The test assesses reading ability.', 'Bài kiểm tra đánh giá khả năng đọc.', 51),
  ('evaluate', '/ɪˈvæljueɪt/', 'đánh giá, thẩm định (v)', 'We evaluated three teaching methods.', 'Chúng tôi đánh giá ba phương pháp giảng dạy.', 52),
  ('investigate', '/ɪnˈvestɪɡeɪt/', 'điều tra, khảo cứu (v)', 'This study investigates online learning.', 'Nghiên cứu này khảo cứu việc học trực tuyến.', 53),
  ('examine', '/ɪɡˈzæmɪn/', 'xem xét, khảo sát (v)', 'The paper examines recent trends.', 'Bài báo xem xét các xu hướng gần đây.', 54),
  ('explore', '/ɪkˈsplɔː/', 'khám phá, tìm hiểu (v)', 'We explore how students use apps.', 'Chúng tôi tìm hiểu cách sinh viên dùng ứng dụng.', 55),
  ('identify', '/aɪˈdentɪfaɪ/', 'xác định (v)', 'We identified four main themes.', 'Chúng tôi xác định bốn chủ đề chính.', 56),
  ('indicate', '/ˈɪndɪkeɪt/', 'chỉ ra (v)', 'The results indicate a clear pattern.', 'Kết quả chỉ ra một xu hướng rõ ràng.', 57),
  ('demonstrate', '/ˈdemənstreɪt/', 'chứng minh (v)', 'The experiment demonstrates the effect.', 'Thí nghiệm chứng minh hiệu ứng đó.', 58),
  ('reveal', '/rɪˈviːl/', 'tiết lộ, cho thấy (v)', 'The interviews revealed hidden concerns.', 'Các cuộc phỏng vấn cho thấy những lo ngại tiềm ẩn.', 59),
  ('suggest', '/səˈdʒest/', 'gợi ý, cho thấy (v)', 'The data suggest a link with diet.', 'Dữ liệu cho thấy có liên hệ với chế độ ăn.', 60),
  ('confirm', '/kənˈfɜːm/', 'xác nhận (v)', 'Later studies confirmed these results.', 'Các nghiên cứu sau xác nhận kết quả này.', 61),
  ('reliable', '/rɪˈlaɪəbl/', 'đáng tin cậy (adj)', 'The instrument proved reliable.', 'Công cụ đo tỏ ra đáng tin cậy.', 62),
  ('valid', '/ˈvælɪd/', 'có giá trị, hợp lệ (adj)', 'Is the test a valid measure of skill?', 'Bài kiểm tra có phải thước đo hợp lệ cho kỹ năng không?', 63),
  ('bias', '/ˈbaɪəs/', 'thiên lệch (n)', 'Self-reporting may introduce bias.', 'Tự báo cáo có thể gây thiên lệch.', 64),
  ('objectivity', '/ˌɒbdʒekˈtɪvəti/', 'tính khách quan (n)', 'Objectivity is essential in research.', 'Tính khách quan là thiết yếu trong nghiên cứu.', 65),
  ('qualitative', '/ˈkwɒlɪtətɪv/', 'định tính (adj)', 'Qualitative data came from interviews.', 'Dữ liệu định tính đến từ phỏng vấn.', 66),
  ('quantitative', '/ˈkwɒntɪtətɪv/', 'định lượng (adj)', 'A quantitative survey was used.', 'Một khảo sát định lượng đã được dùng.', 67),
  ('empirical', '/ɪmˈpɪrɪkl/', 'thực nghiệm (adj)', 'There is strong empirical support.', 'Có sự ủng hộ thực nghiệm mạnh mẽ.', 68),
  ('theoretical', '/ˌθɪəˈretɪkl/', 'mang tính lý thuyết (adj)', 'The paper makes a theoretical contribution.', 'Bài báo có đóng góp về mặt lý thuyết.', 69),
  ('case study', '/keɪs ˈstʌdi/', 'nghiên cứu tình huống (n)', 'The case study focuses on one school.', 'Nghiên cứu tình huống tập trung vào một trường.', 70),
  ('pilot study', '/ˈpaɪlət ˈstʌdi/', 'nghiên cứu thử nghiệm (n)', 'A pilot study tested the questionnaire.', 'Nghiên cứu thử nghiệm kiểm tra bảng hỏi.', 71),
  ('procedure', '/prəˈsiːdʒə/', 'quy trình (n)', 'The procedure took about an hour.', 'Quy trình mất khoảng một giờ.', 72),
  ('criteria', '/kraɪˈtɪəriə/', 'tiêu chí (n, số nhiều)', 'Participants met strict criteria.', 'Người tham gia đáp ứng các tiêu chí nghiêm ngặt.', 73),
  ('phenomenon', '/fəˈnɒmɪnən/', 'hiện tượng (n)', 'Burnout is a widespread phenomenon.', 'Kiệt sức là một hiện tượng phổ biến.', 74),
  ('context', '/ˈkɒntekst/', 'bối cảnh (n)', 'Results must be read in context.', 'Kết quả phải được đọc trong bối cảnh.', 75),
  ('implication', '/ˌɪmplɪˈkeɪʃn/', 'hàm ý, ý nghĩa thực tiễn (n)', 'The findings have implications for policy.', 'Các phát hiện có hàm ý cho chính sách.', 76),
  ('contribution', '/ˌkɒntrɪˈbjuːʃn/', 'đóng góp (n)', 'The main contribution is a new model.', 'Đóng góp chính là một mô hình mới.', 77),
  ('gap', '/ɡæp/', 'khoảng trống (nghiên cứu) (n)', 'This study fills a gap in the literature.', 'Nghiên cứu này lấp khoảng trống trong tài liệu.', 78),
  ('previous', '/ˈpriːviəs/', 'trước đó (adj)', 'Previous studies reported similar results.', 'Các nghiên cứu trước báo cáo kết quả tương tự.', 79),
  ('further research', '/ˈfɜːðə rɪˈsɜːtʃ/', 'nghiên cứu thêm', 'Further research is needed.', 'Cần nghiên cứu thêm.', 80),
  ('replicate', '/ˈreplɪkeɪt/', 'lặp lại (nghiên cứu) (v)', 'The study should be replicated.', 'Nghiên cứu nên được lặp lại.', 81),
  ('generalise', '/ˈdʒenrəlaɪz/', 'khái quát hoá (v)', 'We cannot generalise from one case.', 'Không thể khái quát từ một trường hợp.', 82),
  ('statistics', '/stəˈtɪstɪks/', 'thống kê (n)', 'Descriptive statistics are reported first.', 'Thống kê mô tả được báo cáo trước.', 83),
  ('average', '/ˈævərɪdʒ/', 'trung bình (n, adj)', 'The average score was 72.', 'Điểm trung bình là 72.', 84),
  ('percentage', '/pəˈsentɪdʒ/', 'tỉ lệ phần trăm (n)', 'A high percentage agreed.', 'Tỉ lệ phần trăm đồng ý cao.', 85),
  ('table', '/ˈteɪbl/', 'bảng (n)', 'See Table 1 for details.', 'Xem Bảng 1 để biết chi tiết.', 86),
  ('figure', '/ˈfɪɡə/', 'hình, biểu đồ; con số (n)', 'Figure 3 shows the trend.', 'Hình 3 thể hiện xu hướng.', 87),
  ('appendix', '/əˈpendɪks/', 'phụ lục (n)', 'The full survey is in the appendix.', 'Bản khảo sát đầy đủ nằm ở phụ lục.', 88),
  ('thesis', '/ˈθiːsɪs/', 'luận văn, luận án (n)', 'She is writing her master''s thesis.', 'Cô ấy đang viết luận văn thạc sĩ.', 89),
  ('dissertation', '/ˌdɪsəˈteɪʃn/', 'luận án (n)', 'His dissertation won an award.', 'Luận án của anh ấy đoạt giải.', 90),
  ('supervisor', '/ˈsuːpəvaɪzə/', 'người hướng dẫn (n)', 'My supervisor reviewed the draft.', 'Người hướng dẫn đã xem bản nháp.', 91),
  ('ethics', '/ˈeθɪks/', 'đạo đức nghiên cứu (n)', 'The study received ethics approval.', 'Nghiên cứu được duyệt về đạo đức.', 92),
  ('consent', '/kənˈsent/', 'sự đồng ý (n)', 'All participants gave written consent.', 'Mọi người tham gia đều ký đồng ý.', 93),
  ('anonymous', '/əˈnɒnɪməs/', 'ẩn danh (adj)', 'Responses were anonymous.', 'Các phản hồi được ẩn danh.', 94),
  ('plagiarism', '/ˈpleɪdʒərɪzəm/', 'đạo văn (n)', 'Plagiarism leads to serious penalties.', 'Đạo văn dẫn đến hình phạt nghiêm trọng.', 95),
  ('paraphrase', '/ˈpærəfreɪz/', 'diễn đạt lại (v)', 'Paraphrase instead of copying.', 'Hãy diễn đạt lại thay vì chép nguyên.', 96),
  ('summarise', '/ˈsʌməraɪz/', 'tóm tắt (v)', 'Summarise the main argument.', 'Tóm tắt luận điểm chính.', 97),
  ('draft', '/drɑːft/', 'bản nháp (n)', 'The first draft needs revision.', 'Bản nháp đầu cần chỉnh sửa.', 98),
  ('revise', '/rɪˈvaɪz/', 'chỉnh sửa (v)', 'Revise the paper before submission.', 'Chỉnh sửa bài trước khi nộp.', 99),
  ('submit', '/səbˈmɪt/', 'nộp (v)', 'Submit the manuscript by June.', 'Nộp bản thảo trước tháng Sáu.', 100)
) as w(term, phonetic, meaning_vi, example_en, example_vi, position) on true
where d.slug = 'hoc-thuat-nghien-cuu'
on conflict (deck_id, term) do nothing;

-- Lập luận & phản biện (100 từ)
insert into public.decks (slug, name, description, level, category, position)
values ('hoc-thuat-lap-luan', 'Lập luận & phản biện', 'Từ nối, quan điểm, đánh giá, IELTS Writing', 'advanced', 'hoc-thuat', 20)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, level = excluded.level,
  category = excluded.category, position = excluded.position;

insert into public.words (deck_id, term, phonetic, meaning_vi, example_en, example_vi, position)
select d.id, w.term, w.phonetic, w.meaning_vi, w.example_en, w.example_vi, w.position
from public.decks d
join (values
  ('argument', '/ˈɑːɡjumənt/', 'luận điểm, lập luận (n)', 'The essay presents a clear argument.', 'Bài luận trình bày một lập luận rõ ràng.', 1),
  ('argue', '/ˈɑːɡjuː/', 'lập luận, cho rằng (v)', 'Some argue that tests are unfair.', 'Một số người cho rằng các kỳ thi không công bằng.', 2),
  ('claim', '/kleɪm/', 'khẳng định (n, v)', 'This claim is not supported by facts.', 'Khẳng định này không có dữ kiện ủng hộ.', 3),
  ('opinion', '/əˈpɪnjən/', 'ý kiến (n)', 'In my opinion, the policy works.', 'Theo ý tôi, chính sách này hiệu quả.', 4),
  ('viewpoint', '/ˈvjuːpɔɪnt/', 'quan điểm (n)', 'Both viewpoints deserve attention.', 'Cả hai quan điểm đều đáng chú ý.', 5),
  ('perspective', '/pəˈspektɪv/', 'góc nhìn (n)', 'From an economic perspective, it makes sense.', 'Từ góc nhìn kinh tế, điều đó hợp lý.', 6),
  ('thesis statement', '/ˈθiːsɪs ˈsteɪtmənt/', 'câu luận đề (n)', 'Put the thesis statement at the end of the introduction.', 'Đặt câu luận đề ở cuối mở bài.', 7),
  ('introduction', '/ˌɪntrəˈdʌkʃn/', 'mở bài (n)', 'The introduction outlines the topic.', 'Mở bài phác thảo chủ đề.', 8),
  ('body paragraph', '/ˈbɒdi ˈpærəɡrɑːf/', 'đoạn thân bài (n)', 'Each body paragraph has one main idea.', 'Mỗi đoạn thân bài có một ý chính.', 9),
  ('topic sentence', '/ˈtɒpɪk ˈsentəns/', 'câu chủ đề (n)', 'Start with a strong topic sentence.', 'Bắt đầu bằng một câu chủ đề mạnh.', 10),
  ('supporting detail', '/səˈpɔːtɪŋ ˈdiːteɪl/', 'chi tiết hỗ trợ (n)', 'Add supporting details and examples.', 'Thêm chi tiết hỗ trợ và ví dụ.', 11),
  ('firstly', '/ˈfɜːstli/', 'thứ nhất (adv)', 'Firstly, cost is a major concern.', 'Thứ nhất, chi phí là mối lo lớn.', 12),
  ('secondly', '/ˈsekəndli/', 'thứ hai (adv)', 'Secondly, time is limited.', 'Thứ hai, thời gian có hạn.', 13),
  ('finally', '/ˈfaɪnəli/', 'cuối cùng (adv)', 'Finally, safety must be considered.', 'Cuối cùng, phải cân nhắc sự an toàn.', 14),
  ('furthermore', '/ˌfɜːðəˈmɔː/', 'hơn nữa (adv)', 'Furthermore, the plan is affordable.', 'Hơn nữa, kế hoạch này vừa túi tiền.', 15),
  ('moreover', '/mɔːrˈəʊvə/', 'hơn thế nữa (adv)', 'Moreover, it saves energy.', 'Hơn thế nữa, nó tiết kiệm năng lượng.', 16),
  ('in addition', '/ɪn əˈdɪʃn/', 'ngoài ra', 'In addition, staff need training.', 'Ngoài ra, nhân viên cần được đào tạo.', 17),
  ('however', '/haʊˈevə/', 'tuy nhiên (adv)', 'However, there are drawbacks.', 'Tuy nhiên, có những nhược điểm.', 18),
  ('nevertheless', '/ˌnevəðəˈles/', 'dù vậy (adv)', 'Nevertheless, the idea has merit.', 'Dù vậy, ý tưởng này có giá trị.', 19),
  ('on the other hand', '/ɒn ði ˈʌðə hænd/', 'mặt khác', 'On the other hand, costs may rise.', 'Mặt khác, chi phí có thể tăng.', 20),
  ('whereas', '/weərˈæz/', 'trong khi (đối lập) (conj)', 'Cities grow, whereas villages shrink.', 'Thành phố lớn lên, trong khi làng quê thu hẹp.', 21),
  ('although', '/ɔːlˈðəʊ/', 'mặc dù (conj)', 'Although expensive, it is worth it.', 'Mặc dù đắt, nó xứng đáng.', 22),
  ('despite', '/dɪˈspaɪt/', 'bất chấp (prep)', 'Despite the risks, many agree.', 'Bất chấp rủi ro, nhiều người đồng ý.', 23),
  ('in contrast', '/ɪn ˈkɒntrɑːst/', 'ngược lại', 'In contrast, rural areas lack services.', 'Ngược lại, nông thôn thiếu dịch vụ.', 24),
  ('similarly', '/ˈsɪmələli/', 'tương tự (adv)', 'Similarly, Japan faces an ageing population.', 'Tương tự, Nhật Bản đối mặt với dân số già.', 25),
  ('likewise', '/ˈlaɪkwaɪz/', 'cũng vậy (adv)', 'Likewise, teachers need support.', 'Giáo viên cũng vậy, cần được hỗ trợ.', 26),
  ('therefore', '/ˈðeəfɔː/', 'do đó (adv)', 'Therefore, action is needed now.', 'Do đó, cần hành động ngay.', 27),
  ('consequently', '/ˈkɒnsɪkwəntli/', 'hệ quả là (adv)', 'Consequently, prices fell.', 'Hệ quả là giá giảm.', 28),
  ('as a result', '/əz ə rɪˈzʌlt/', 'kết quả là', 'As a result, fewer people drive.', 'Kết quả là ít người lái xe hơn.', 29),
  ('thus', '/ðʌs/', 'vì vậy (adv)', 'Thus, the theory holds.', 'Vì vậy, lý thuyết đứng vững.', 30),
  ('hence', '/hens/', 'do vậy (adv)', 'Hence, demand rose sharply.', 'Do vậy, nhu cầu tăng mạnh.', 31),
  ('due to', '/djuː tuː/', 'do, bởi vì', 'Sales fell due to the recession.', 'Doanh số giảm do suy thoái.', 32),
  ('owing to', '/ˈəʊɪŋ tuː/', 'vì (trang trọng)', 'Owing to rain, the event was cancelled.', 'Vì mưa, sự kiện bị huỷ.', 33),
  ('lead to', '/liːd tuː/', 'dẫn đến', 'Stress can lead to illness.', 'Căng thẳng có thể dẫn đến bệnh tật.', 34),
  ('result in', '/rɪˈzʌlt ɪn/', 'gây ra, dẫn đến', 'Poor planning results in delays.', 'Lập kế hoạch kém gây ra chậm trễ.', 35),
  ('stem from', '/stem frɒm/', 'bắt nguồn từ', 'Many problems stem from poverty.', 'Nhiều vấn đề bắt nguồn từ nghèo đói.', 36),
  ('give rise to', '/ɡɪv raɪz tuː/', 'làm nảy sinh', 'Automation gives rise to new jobs.', 'Tự động hoá làm nảy sinh việc làm mới.', 37),
  ('cause', '/kɔːz/', 'nguyên nhân (n); gây ra (v)', 'The main cause is traffic.', 'Nguyên nhân chính là giao thông.', 38),
  ('effect', '/ɪˈfekt/', 'hiệu quả, tác động (n)', 'The effect on health is clear.', 'Tác động lên sức khoẻ là rõ ràng.', 39),
  ('consequence', '/ˈkɒnsɪkwəns/', 'hậu quả (n)', 'One consequence is higher rent.', 'Một hậu quả là tiền thuê nhà cao hơn.', 40),
  ('for example', '/fɔːr ɪɡˈzɑːmpl/', 'ví dụ', 'For example, Norway taxes cars heavily.', 'Ví dụ, Na Uy đánh thuế ô tô rất nặng.', 41),
  ('for instance', '/fɔːr ˈɪnstəns/', 'chẳng hạn', 'For instance, many cities ban plastic bags.', 'Chẳng hạn, nhiều thành phố cấm túi nhựa.', 42),
  ('such as', '/sʌtʃ æz/', 'như là', 'Skills such as coding are in demand.', 'Các kỹ năng như lập trình đang được cần.', 43),
  ('namely', '/ˈneɪmli/', 'cụ thể là (adv)', 'Two issues remain, namely cost and time.', 'Còn hai vấn đề, cụ thể là chi phí và thời gian.', 44),
  ('in other words', '/ɪn ˈʌðə wɜːdz/', 'nói cách khác', 'In other words, the plan failed.', 'Nói cách khác, kế hoạch đã thất bại.', 45),
  ('that is to say', '/ðæt ɪz tuː seɪ/', 'tức là', 'It is cheap, that is to say, under $10.', 'Nó rẻ, tức là dưới 10 đô.', 46),
  ('in conclusion', '/ɪn kənˈkluːʒn/', 'tóm lại, kết luận', 'In conclusion, both sides have a point.', 'Kết luận, cả hai bên đều có lý.', 47),
  ('to sum up', '/tuː sʌm ʌp/', 'tóm lại', 'To sum up, education is the key.', 'Tóm lại, giáo dục là chìa khoá.', 48),
  ('overall', '/ˌəʊvərˈɔːl/', 'nhìn chung (adv)', 'Overall, the benefits outweigh the costs.', 'Nhìn chung, lợi ích vượt trội chi phí.', 49),
  ('outweigh', '/ˌaʊtˈweɪ/', 'vượt trội hơn (v)', 'The advantages outweigh the disadvantages.', 'Ưu điểm vượt trội nhược điểm.', 50),
  ('advantage', '/ədˈvɑːntɪdʒ/', 'ưu điểm (n)', 'A key advantage is speed.', 'Một ưu điểm then chốt là tốc độ.', 51),
  ('disadvantage', '/ˌdɪsədˈvɑːntɪdʒ/', 'nhược điểm (n)', 'The main disadvantage is cost.', 'Nhược điểm chính là chi phí.', 52),
  ('benefit', '/ˈbenɪfɪt/', 'lợi ích (n)', 'The benefits are widely known.', 'Lợi ích đã được biết rộng rãi.', 53),
  ('drawback', '/ˈdrɔːbæk/', 'mặt hạn chế (n)', 'One drawback is the noise.', 'Một hạn chế là tiếng ồn.', 54),
  ('agree', '/əˈɡriː/', 'đồng ý (v)', 'I strongly agree with this view.', 'Tôi hoàn toàn đồng ý với quan điểm này.', 55),
  ('disagree', '/ˌdɪsəˈɡriː/', 'không đồng ý (v)', 'I disagree for two reasons.', 'Tôi không đồng ý vì hai lý do.', 56),
  ('to some extent', '/tuː sʌm ɪkˈstent/', 'ở mức độ nào đó', 'To some extent, this is true.', 'Ở mức độ nào đó, điều này đúng.', 57),
  ('partly', '/ˈpɑːtli/', 'một phần (adv)', 'I partly agree with the statement.', 'Tôi đồng ý một phần với nhận định.', 58),
  ('convincing', '/kənˈvɪnsɪŋ/', 'thuyết phục (adj)', 'The evidence is convincing.', 'Bằng chứng rất thuyết phục.', 59),
  ('persuasive', '/pəˈsweɪsɪv/', 'có sức thuyết phục (adj)', 'She made a persuasive case.', 'Cô ấy đưa ra lập luận có sức thuyết phục.', 60),
  ('justify', '/ˈdʒʌstɪfaɪ/', 'biện minh, chứng minh hợp lý (v)', 'Can higher taxes be justified?', 'Thuế cao hơn có biện minh được không?', 61),
  ('support', '/səˈpɔːt/', 'ủng hộ, làm cơ sở (v)', 'Statistics support this argument.', 'Số liệu thống kê ủng hộ lập luận này.', 62),
  ('refute', '/rɪˈfjuːt/', 'bác bỏ (v)', 'New data refute the old theory.', 'Dữ liệu mới bác bỏ lý thuyết cũ.', 63),
  ('counterargument', '/ˈkaʊntərɑːɡjumənt/', 'phản biện (n)', 'Address the main counterargument.', 'Hãy xử lý phản biện chính.', 64),
  ('critics', '/ˈkrɪtɪks/', 'những người chỉ trích (n)', 'Critics say the plan is unrealistic.', 'Những người chỉ trích nói kế hoạch phi thực tế.', 65),
  ('proponent', '/prəˈpəʊnənt/', 'người ủng hộ (n)', 'Proponents highlight the savings.', 'Người ủng hộ nhấn mạnh khoản tiết kiệm.', 66),
  ('opponent', '/əˈpəʊnənt/', 'người phản đối (n)', 'Opponents fear job losses.', 'Người phản đối lo mất việc làm.', 67),
  ('controversial', '/ˌkɒntrəˈvɜːʃl/', 'gây tranh cãi (adj)', 'Nuclear power remains controversial.', 'Điện hạt nhân vẫn gây tranh cãi.', 68),
  ('debate', '/dɪˈbeɪt/', 'cuộc tranh luận (n)', 'The debate continues today.', 'Cuộc tranh luận vẫn tiếp diễn.', 69),
  ('issue', '/ˈɪʃuː/', 'vấn đề (n)', 'This is a complex issue.', 'Đây là một vấn đề phức tạp.', 70),
  ('aspect', '/ˈæspekt/', 'khía cạnh (n)', 'Consider the financial aspect.', 'Hãy xem xét khía cạnh tài chính.', 71),
  ('assume', '/əˈsjuːm/', 'giả định (v)', 'We cannot assume everyone agrees.', 'Không thể giả định ai cũng đồng ý.', 72),
  ('assumption', '/əˈsʌmpʃn/', 'giả định (n)', 'This rests on a false assumption.', 'Điều này dựa trên một giả định sai.', 73),
  ('arguably', '/ˈɑːɡjuəbli/', 'có thể nói rằng (adv)', 'It is arguably the best option.', 'Có thể nói đó là lựa chọn tốt nhất.', 74),
  ('undoubtedly', '/ʌnˈdaʊtɪdli/', 'chắc chắn (adv)', 'Technology has undoubtedly changed work.', 'Công nghệ chắc chắn đã thay đổi công việc.', 75),
  ('it is widely believed', '/ɪt ɪz ˈwaɪdli bɪˈliːvd/', 'người ta tin rộng rãi rằng', 'It is widely believed that exercise helps.', 'Người ta tin rộng rãi rằng tập thể dục có ích.', 76),
  ('tend to', '/tend tuː/', 'có xu hướng', 'Young people tend to prefer apps.', 'Người trẻ có xu hướng thích ứng dụng.', 77),
  ('likely', '/ˈlaɪkli/', 'có khả năng (adj)', 'Prices are likely to rise.', 'Giá có khả năng tăng.', 78),
  ('may', '/meɪ/', 'có thể (modal, giảm nhẹ)', 'This may not apply everywhere.', 'Điều này có thể không đúng ở mọi nơi.', 79),
  ('appear', '/əˈpɪə/', 'dường như (v)', 'The policy appears to work.', 'Chính sách dường như hiệu quả.', 80),
  ('seem', '/siːm/', 'có vẻ (v)', 'It seems reasonable to wait.', 'Có vẻ hợp lý khi chờ.', 81),
  ('generally', '/ˈdʒenrəli/', 'nhìn chung (adv)', 'Generally, rents are higher in cities.', 'Nhìn chung, tiền thuê nhà ở thành phố cao hơn.', 82),
  ('particularly', '/pəˈtɪkjələli/', 'đặc biệt là (adv)', 'This is particularly true for students.', 'Điều này đặc biệt đúng với sinh viên.', 83),
  ('essential', '/ɪˈsenʃl/', 'thiết yếu (adj)', 'Clean water is essential.', 'Nước sạch là thiết yếu.', 84),
  ('crucial', '/ˈkruːʃl/', 'then chốt (adj)', 'Timing is crucial.', 'Thời điểm là then chốt.', 85),
  ('vital', '/ˈvaɪtl/', 'sống còn (adj)', 'Sleep is vital for memory.', 'Giấc ngủ sống còn với trí nhớ.', 86),
  ('beneficial', '/ˌbenɪˈfɪʃl/', 'có lợi (adj)', 'Reading is beneficial for children.', 'Đọc sách có lợi cho trẻ em.', 87),
  ('detrimental', '/ˌdetrɪˈmentl/', 'có hại (adj)', 'Smoking is detrimental to health.', 'Hút thuốc có hại cho sức khoẻ.', 88),
  ('inevitable', '/ɪnˈevɪtəbl/', 'không thể tránh khỏi (adj)', 'Some change is inevitable.', 'Một số thay đổi là không thể tránh khỏi.', 89),
  ('take steps', '/teɪk steps/', 'có biện pháp, hành động', 'Governments should take steps to reduce waste.', 'Chính phủ nên có biện pháp giảm rác thải.', 90),
  ('solution', '/səˈluːʃn/', 'giải pháp (n)', 'There is no easy solution.', 'Không có giải pháp dễ dàng.', 91),
  ('address', '/əˈdres/', 'giải quyết (vấn đề) (v)', 'We must address the root cause.', 'Phải giải quyết nguyên nhân gốc.', 92),
  ('tackle', '/ˈtækl/', 'đối phó, xử lý (v)', 'How can we tackle pollution?', 'Làm sao xử lý ô nhiễm?', 93),
  ('emphasise', '/ˈemfəsaɪz/', 'nhấn mạnh (v)', 'The report emphasises prevention.', 'Báo cáo nhấn mạnh phòng ngừa.', 94),
  ('highlight', '/ˈhaɪlaɪt/', 'làm nổi bật (v)', 'The study highlights a key risk.', 'Nghiên cứu làm nổi bật một rủi ro chính.', 95),
  ('acknowledge', '/əkˈnɒlɪdʒ/', 'thừa nhận (v)', 'We acknowledge some limitations.', 'Chúng tôi thừa nhận vài hạn chế.', 96),
  ('compelling', '/kəmˈpelɪŋ/', 'rất thuyết phục (adj)', 'There is a compelling reason to act.', 'Có lý do rất thuyết phục để hành động.', 97),
  ('balanced', '/ˈbælənst/', 'cân bằng (adj)', 'A balanced view considers both sides.', 'Cái nhìn cân bằng xét cả hai phía.', 98),
  ('coherent', '/kəʊˈhɪərənt/', 'mạch lạc (adj)', 'The essay is coherent and well organised.', 'Bài luận mạch lạc và có tổ chức tốt.', 99),
  ('in my view', '/ɪn maɪ vjuː/', 'theo quan điểm của tôi', 'In my view, the benefits are clear.', 'Theo quan điểm của tôi, lợi ích là rõ ràng.', 100)
) as w(term, phonetic, meaning_vi, example_en, example_vi, position) on true
where d.slug = 'hoc-thuat-lap-luan'
on conflict (deck_id, term) do nothing;

-- Số liệu & xu hướng (100 từ)
insert into public.decks (slug, name, description, level, category, position)
values ('hoc-thuat-so-lieu', 'Số liệu & xu hướng', 'Biểu đồ, tăng giảm, so sánh, IELTS Task 1', 'advanced', 'hoc-thuat', 30)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, level = excluded.level,
  category = excluded.category, position = excluded.position;

insert into public.words (deck_id, term, phonetic, meaning_vi, example_en, example_vi, position)
select d.id, w.term, w.phonetic, w.meaning_vi, w.example_en, w.example_vi, w.position
from public.decks d
join (values
  ('chart', '/tʃɑːt/', 'biểu đồ (n)', 'The chart shows sales by region.', 'Biểu đồ thể hiện doanh số theo vùng.', 1),
  ('graph', '/ɡrɑːf/', 'đồ thị (n)', 'The graph compares two countries.', 'Đồ thị so sánh hai quốc gia.', 2),
  ('bar chart', '/bɑː tʃɑːt/', 'biểu đồ cột (n)', 'The bar chart illustrates energy use.', 'Biểu đồ cột minh hoạ mức dùng năng lượng.', 3),
  ('line graph', '/laɪn ɡrɑːf/', 'biểu đồ đường (n)', 'The line graph shows changes over time.', 'Biểu đồ đường thể hiện thay đổi theo thời gian.', 4),
  ('pie chart', '/paɪ tʃɑːt/', 'biểu đồ tròn (n)', 'The pie chart shows the proportions.', 'Biểu đồ tròn thể hiện các tỉ lệ.', 5),
  ('column', '/ˈkɒləm/', 'cột (bảng) (n)', 'The first column lists the countries.', 'Cột đầu tiên liệt kê các quốc gia.', 6),
  ('diagram', '/ˈdaɪəɡræm/', 'sơ đồ (n)', 'The diagram explains the process.', 'Sơ đồ giải thích quy trình.', 7),
  ('illustrate', '/ˈɪləstreɪt/', 'minh hoạ (v)', 'The graph illustrates population growth.', 'Đồ thị minh hoạ tăng trưởng dân số.', 8),
  ('depict', '/dɪˈpɪkt/', 'mô tả, thể hiện (v)', 'The chart depicts car ownership.', 'Biểu đồ thể hiện tỉ lệ sở hữu xe.', 9),
  ('represent', '/ˌreprɪˈzent/', 'biểu thị (v)', 'Each bar represents one year.', 'Mỗi cột biểu thị một năm.', 10),
  ('axis', '/ˈæksɪs/', 'trục (n)', 'The vertical axis shows percentages.', 'Trục dọc thể hiện phần trăm.', 11),
  ('unit', '/ˈjuːnɪt/', 'đơn vị (n)', 'The units are millions of tonnes.', 'Đơn vị là triệu tấn.', 12),
  ('statistic', '/stəˈtɪstɪk/', 'số liệu thống kê (n)', 'One striking statistic is the 40% drop.', 'Một số liệu đáng chú ý là mức giảm 40%.', 13),
  ('increase', '/ɪnˈkriːs/', 'tăng (v, n)', 'Sales increased by 10%.', 'Doanh số tăng 10%.', 14),
  ('rise', '/raɪz/', 'tăng lên (v, n)', 'Prices rose steadily.', 'Giá tăng đều đặn.', 15),
  ('grow', '/ɡrəʊ/', 'tăng trưởng (v)', 'The population grew rapidly.', 'Dân số tăng nhanh.', 16),
  ('climb', '/klaɪm/', 'leo lên, tăng (v)', 'Exports climbed to a record high.', 'Xuất khẩu leo lên mức kỷ lục.', 17),
  ('soar', '/sɔː/', 'tăng vọt (v)', 'Oil prices soared in 2008.', 'Giá dầu tăng vọt năm 2008.', 18),
  ('surge', '/sɜːdʒ/', 'tăng đột biến (v, n)', 'Demand surged during the holiday.', 'Nhu cầu tăng đột biến dịp lễ.', 19),
  ('rocket', '/ˈrɒkɪt/', 'tăng chóng mặt (v)', 'Rents rocketed after 2015.', 'Tiền thuê tăng chóng mặt sau 2015.', 20),
  ('decrease', '/dɪˈkriːs/', 'giảm (v, n)', 'Unemployment decreased slightly.', 'Thất nghiệp giảm nhẹ.', 21),
  ('fall', '/fɔːl/', 'giảm, rơi (v, n)', 'Profits fell sharply.', 'Lợi nhuận giảm mạnh.', 22),
  ('drop', '/drɒp/', 'giảm, rớt (v, n)', 'There was a sudden drop in sales.', 'Doanh số rớt đột ngột.', 23),
  ('decline', '/dɪˈklaɪn/', 'suy giảm (v, n)', 'Birth rates declined over the decade.', 'Tỉ lệ sinh suy giảm trong thập kỷ.', 24),
  ('plunge', '/plʌndʒ/', 'lao dốc (v)', 'Shares plunged after the news.', 'Cổ phiếu lao dốc sau tin đó.', 25),
  ('plummet', '/ˈplʌmɪt/', 'giảm thẳng đứng (v)', 'Tourist numbers plummeted in 2020.', 'Lượng khách du lịch giảm thẳng đứng năm 2020.', 26),
  ('dip', '/dɪp/', 'giảm nhẹ tạm thời (v, n)', 'There was a small dip in March.', 'Có một đợt giảm nhẹ vào tháng Ba.', 27),
  ('fluctuate', '/ˈflʌktʃueɪt/', 'dao động (v)', 'Prices fluctuated throughout the year.', 'Giá dao động suốt năm.', 28),
  ('fluctuation', '/ˌflʌktʃuˈeɪʃn/', 'sự dao động (n)', 'There were minor fluctuations.', 'Có những dao động nhỏ.', 29),
  ('remain stable', '/rɪˈmeɪn ˈsteɪbl/', 'giữ ổn định', 'Costs remained stable for five years.', 'Chi phí giữ ổn định trong năm năm.', 30),
  ('level off', '/ˈlevl ɒf/', 'chững lại', 'Growth levelled off after 2018.', 'Tăng trưởng chững lại sau 2018.', 31),
  ('plateau', '/ˈplætəʊ/', 'đi ngang (v, n)', 'Sales plateaued at 2 million.', 'Doanh số đi ngang ở mức 2 triệu.', 32),
  ('stabilise', '/ˈsteɪbəlaɪz/', 'ổn định lại (v)', 'The rate stabilised in 2021.', 'Tỉ lệ ổn định lại vào 2021.', 33),
  ('peak', '/piːk/', 'đỉnh (n); đạt đỉnh (v)', 'Sales peaked in December.', 'Doanh số đạt đỉnh vào tháng Mười Hai.', 34),
  ('reach a high', '/riːtʃ ə haɪ/', 'đạt mức cao', 'Exports reached a high of $5bn.', 'Xuất khẩu đạt mức cao 5 tỉ đô.', 35),
  ('hit a low', '/hɪt ə ləʊ/', 'chạm đáy', 'The rate hit a low of 3%.', 'Tỉ lệ chạm đáy 3%.', 36),
  ('bottom out', '/ˈbɒtəm aʊt/', 'chạm đáy rồi ngừng giảm', 'Prices bottomed out in 2009.', 'Giá chạm đáy năm 2009.', 37),
  ('recover', '/rɪˈkʌvə/', 'phục hồi (v)', 'The market recovered quickly.', 'Thị trường phục hồi nhanh.', 38),
  ('rebound', '/rɪˈbaʊnd/', 'bật tăng trở lại (v)', 'Tourism rebounded in 2022.', 'Du lịch bật tăng trở lại năm 2022.', 39),
  ('trend', '/trend/', 'xu hướng (n)', 'The overall trend is upward.', 'Xu hướng chung là đi lên.', 40),
  ('upward trend', '/ˈʌpwəd trend/', 'xu hướng tăng', 'There was an upward trend in spending.', 'Chi tiêu có xu hướng tăng.', 41),
  ('downward trend', '/ˈdaʊnwəd trend/', 'xu hướng giảm', 'Smoking shows a downward trend.', 'Hút thuốc có xu hướng giảm.', 42),
  ('sharp', '/ʃɑːp/', 'mạnh, đột ngột (adj)', 'There was a sharp rise in costs.', 'Chi phí tăng mạnh.', 43),
  ('sharply', '/ˈʃɑːpli/', 'mạnh, đột ngột (adv)', 'Numbers fell sharply.', 'Con số giảm mạnh.', 44),
  ('dramatic', '/drəˈmætɪk/', 'đáng kể, kịch tính (adj)', 'A dramatic increase occurred in 2010.', 'Một mức tăng đáng kể xảy ra năm 2010.', 45),
  ('dramatically', '/drəˈmætɪkli/', 'một cách đáng kể (adv)', 'Use rose dramatically.', 'Mức sử dụng tăng đáng kể.', 46),
  ('noticeable', '/ˈnəʊtɪsəbl/', 'rõ rệt (adj)', 'There was a noticeable rise after 2015.', 'Có mức tăng rõ rệt sau 2015.', 47),
  ('considerable', '/kənˈsɪdərəbl/', 'đáng kể (adj)', 'There was considerable growth.', 'Có mức tăng trưởng đáng kể.', 48),
  ('substantial', '/səbˈstænʃl/', 'lớn, đáng kể (adj)', 'Substantial gains were recorded.', 'Ghi nhận mức tăng lớn.', 49),
  ('steady', '/ˈstedi/', 'đều đặn (adj)', 'There was a steady increase.', 'Có mức tăng đều đặn.', 50),
  ('steadily', '/ˈstedɪli/', 'đều đặn (adv)', 'Income grew steadily.', 'Thu nhập tăng đều đặn.', 51),
  ('gradual', '/ˈɡrædʒuəl/', 'từ từ (adj)', 'A gradual decline is expected.', 'Dự kiến giảm từ từ.', 52),
  ('gradually', '/ˈɡrædʒuəli/', 'dần dần (adv)', 'Costs gradually fell.', 'Chi phí giảm dần.', 53),
  ('slight', '/slaɪt/', 'nhẹ (adj)', 'There was a slight drop.', 'Có mức giảm nhẹ.', 54),
  ('slightly', '/ˈslaɪtli/', 'nhẹ (adv)', 'Figures rose slightly.', 'Số liệu tăng nhẹ.', 55),
  ('marginal', '/ˈmɑːdʒɪnl/', 'không đáng kể (adj)', 'The change was marginal.', 'Thay đổi không đáng kể.', 56),
  ('modest', '/ˈmɒdɪst/', 'khiêm tốn, vừa phải (adj)', 'A modest rise of 2% was seen.', 'Ghi nhận mức tăng vừa phải 2%.', 57),
  ('rapid', '/ˈræpɪd/', 'nhanh (adj)', 'Rapid growth continued.', 'Tăng trưởng nhanh tiếp tục.', 58),
  ('rapidly', '/ˈræpɪdli/', 'nhanh chóng (adv)', 'Cities expanded rapidly.', 'Thành phố mở rộng nhanh chóng.', 59),
  ('proportion', '/prəˈpɔːʃn/', 'tỉ lệ, phần (n)', 'A large proportion of users are young.', 'Phần lớn người dùng còn trẻ.', 60),
  ('per cent', '/pə ˈsent/', 'phần trăm', 'Sales grew 12 per cent.', 'Doanh số tăng 12 phần trăm.', 61),
  ('rate', '/reɪt/', 'tỉ lệ, tốc độ (n)', 'The unemployment rate is 4%.', 'Tỉ lệ thất nghiệp là 4%.', 62),
  ('ratio', '/ˈreɪʃiəʊ/', 'tỉ số (n)', 'The ratio of men to women was 3:2.', 'Tỉ số nam trên nữ là 3:2.', 63),
  ('share', '/ʃeə/', 'phần, thị phần (n)', 'Coal''s share fell to 20%.', 'Phần của than giảm còn 20%.', 64),
  ('majority', '/məˈdʒɒrəti/', 'đa số (n)', 'The majority preferred trains.', 'Đa số thích tàu hoả hơn.', 65),
  ('minority', '/maɪˈnɒrəti/', 'thiểu số (n)', 'Only a minority cycled to work.', 'Chỉ thiểu số đạp xe đi làm.', 66),
  ('a quarter', '/ə ˈkwɔːtə/', 'một phần tư', 'A quarter of the budget went to health.', 'Một phần tư ngân sách dành cho y tế.', 67),
  ('a third', '/ə θɜːd/', 'một phần ba', 'About a third of students work part-time.', 'Khoảng một phần ba sinh viên làm thêm.', 68),
  ('half', '/hɑːf/', 'một nửa (n)', 'Half of the respondents agreed.', 'Một nửa người trả lời đồng ý.', 69),
  ('twofold', '/ˈtuːfəʊld/', 'gấp đôi (adj, adv)', 'There was a twofold increase.', 'Có mức tăng gấp đôi.', 70),
  ('double', '/ˈdʌbl/', 'tăng gấp đôi (v)', 'Sales doubled in two years.', 'Doanh số tăng gấp đôi trong hai năm.', 71),
  ('triple', '/ˈtrɪpl/', 'tăng gấp ba (v)', 'Output tripled.', 'Sản lượng tăng gấp ba.', 72),
  ('halve', '/hɑːv/', 'giảm một nửa (v)', 'Emissions halved since 1990.', 'Khí thải giảm một nửa từ 1990.', 73),
  ('approximately', '/əˈprɒksɪmətli/', 'xấp xỉ (adv)', 'Approximately 60% agreed.', 'Xấp xỉ 60% đồng ý.', 74),
  ('roughly', '/ˈrʌfli/', 'khoảng chừng (adv)', 'Roughly half were female.', 'Khoảng một nửa là nữ.', 75),
  ('just over', '/dʒʌst ˈəʊvə/', 'hơn một chút', 'Just over 30% own a car.', 'Hơn 30% một chút sở hữu ô tô.', 76),
  ('just under', '/dʒʌst ˈʌndə/', 'kém một chút', 'Just under a million visited.', 'Gần một triệu lượt (kém một chút) đã ghé thăm.', 77),
  ('respectively', '/rɪˈspektɪvli/', 'lần lượt (adv)', 'France and Spain scored 45% and 40% respectively.', 'Pháp và Tây Ban Nha lần lượt đạt 45% và 40%.', 78),
  ('compared with', '/kəmˈpeəd wɪð/', 'so với', 'Sales rose 5% compared with last year.', 'Doanh số tăng 5% so với năm ngoái.', 79),
  ('in comparison', '/ɪn kəmˈpærɪsn/', 'khi so sánh', 'In comparison, Asia grew faster.', 'Khi so sánh, châu Á tăng nhanh hơn.', 80),
  ('while', '/waɪl/', 'trong khi (so sánh) (conj)', 'Exports rose, while imports fell.', 'Xuất khẩu tăng, trong khi nhập khẩu giảm.', 81),
  ('by contrast', '/baɪ ˈkɒntrɑːst/', 'ngược lại', 'By contrast, rural use stayed flat.', 'Ngược lại, mức dùng ở nông thôn đi ngang.', 82),
  ('account for', '/əˈkaʊnt fɔː/', 'chiếm (tỉ lệ)', 'Cars account for 40% of emissions.', 'Ô tô chiếm 40% khí thải.', 83),
  ('make up', '/meɪk ʌp/', 'chiếm, cấu thành', 'Women make up 55% of staff.', 'Phụ nữ chiếm 55% nhân sự.', 84),
  ('constitute', '/ˈkɒnstɪtjuːt/', 'cấu thành (v)', 'Rent constitutes the biggest expense.', 'Tiền thuê cấu thành khoản chi lớn nhất.', 85),
  ('over the period', '/ˈəʊvə ðə ˈpɪəriəd/', 'trong giai đoạn', 'Over the period, usage doubled.', 'Trong giai đoạn đó, mức dùng tăng gấp đôi.', 86),
  ('throughout', '/θruːˈaʊt/', 'suốt (prep)', 'Prices rose throughout the decade.', 'Giá tăng suốt thập kỷ.', 87),
  ('from … to …', '/frɒm tuː/', 'từ … đến …', 'It rose from 10% to 25%.', 'Nó tăng từ 10% lên 25%.', 88),
  ('by', '/baɪ/', '(tăng/giảm) một mức', 'Sales fell by 8%.', 'Doanh số giảm 8%.', 89),
  ('reach', '/riːtʃ/', 'đạt tới (v)', 'The figure reached 1 million.', 'Con số đạt tới 1 triệu.', 90),
  ('stand at', '/stænd æt/', 'ở mức', 'Inflation stood at 3% in June.', 'Lạm phát ở mức 3% vào tháng Sáu.', 91),
  ('start at', '/stɑːt æt/', 'bắt đầu ở mức', 'The line starts at 20%.', 'Đường bắt đầu ở mức 20%.', 92),
  ('end at', '/end æt/', 'kết thúc ở mức', 'It ended at just 5%.', 'Nó kết thúc chỉ ở mức 5%.', 93),
  ('in general', '/ɪn ˈdʒenrəl/', 'nhìn chung', 'In general, the trend was positive.', 'Nhìn chung, xu hướng là tích cực.', 94),
  ('notably', '/ˈnəʊtəbli/', 'đáng chú ý là (adv)', 'Notably, Japan bucked the trend.', 'Đáng chú ý, Nhật Bản đi ngược xu hướng.', 95),
  ('it is clear that', '/ɪt ɪz klɪə ðæt/', 'rõ ràng là', 'It is clear that demand is rising.', 'Rõ ràng là nhu cầu đang tăng.', 96),
  ('as can be seen', '/əz kæn biː siːn/', 'như có thể thấy', 'As can be seen, the gap widened.', 'Như có thể thấy, khoảng cách nới rộng.', 97),
  ('forecast', '/ˈfɔːkɑːst/', 'dự báo (n, v)', 'Sales are forecast to rise.', 'Doanh số được dự báo tăng.', 98),
  ('projected', '/prəˈdʒektɪd/', 'dự kiến (adj)', 'The projected figure for 2030 is 8 million.', 'Con số dự kiến cho 2030 là 8 triệu.', 99),
  ('estimate', '/ˈestɪmeɪt/', 'ước tính (v, n)', 'Costs are estimated at $2m.', 'Chi phí ước tính 2 triệu đô.', 100)
) as w(term, phonetic, meaning_vi, example_en, example_vi, position) on true
where d.slug = 'hoc-thuat-so-lieu'
on conflict (deck_id, term) do nothing;

-- Xã hội & chính sách (100 từ)
insert into public.decks (slug, name, description, level, category, position)
values ('hoc-thuat-xa-hoi', 'Xã hội & chính sách', 'Giáo dục, môi trường, công nghệ, chính phủ', 'advanced', 'hoc-thuat', 40)
on conflict (slug) do update set
  name = excluded.name, description = excluded.description, level = excluded.level,
  category = excluded.category, position = excluded.position;

insert into public.words (deck_id, term, phonetic, meaning_vi, example_en, example_vi, position)
select d.id, w.term, w.phonetic, w.meaning_vi, w.example_en, w.example_vi, w.position
from public.decks d
join (values
  ('society', '/səˈsaɪəti/', 'xã hội (n)', 'Technology has transformed society.', 'Công nghệ đã biến đổi xã hội.', 1),
  ('community', '/kəˈmjuːnəti/', 'cộng đồng (n)', 'Local communities need support.', 'Cộng đồng địa phương cần hỗ trợ.', 2),
  ('citizen', '/ˈsɪtɪzn/', 'công dân (n)', 'Every citizen has the right to vote.', 'Mọi công dân đều có quyền bầu cử.', 3),
  ('government', '/ˈɡʌvənmənt/', 'chính phủ (n)', 'The government raised taxes.', 'Chính phủ tăng thuế.', 4),
  ('policy', '/ˈpɒləsi/', 'chính sách (n)', 'The new policy targets pollution.', 'Chính sách mới nhắm vào ô nhiễm.', 5),
  ('legislation', '/ˌledʒɪsˈleɪʃn/', 'luật pháp, đạo luật (n)', 'New legislation bans plastic bags.', 'Đạo luật mới cấm túi nhựa.', 6),
  ('regulation', '/ˌreɡjuˈleɪʃn/', 'quy định (n)', 'Stricter regulations are needed.', 'Cần quy định nghiêm ngặt hơn.', 7),
  ('authority', '/ɔːˈθɒrəti/', 'cơ quan chức năng (n)', 'Local authorities manage schools.', 'Cơ quan địa phương quản lý trường học.', 8),
  ('public sector', '/ˈpʌblɪk ˈsektə/', 'khu vực công (n)', 'The public sector employs millions.', 'Khu vực công tuyển dụng hàng triệu người.', 9),
  ('private sector', '/ˈpraɪvət ˈsektə/', 'khu vực tư nhân (n)', 'The private sector drives innovation.', 'Khu vực tư nhân thúc đẩy đổi mới.', 10),
  ('funding', '/ˈfʌndɪŋ/', 'nguồn tài trợ (n)', 'Schools need more funding.', 'Trường học cần thêm kinh phí.', 11),
  ('subsidy', '/ˈsʌbsədi/', 'trợ cấp (n)', 'Farmers receive subsidies.', 'Nông dân nhận trợ cấp.', 12),
  ('tax', '/tæks/', 'thuế (n)', 'A sugar tax could reduce obesity.', 'Thuế đường có thể giảm béo phì.', 13),
  ('welfare', '/ˈwelfeə/', 'phúc lợi (n)', 'Welfare programs help the poor.', 'Chương trình phúc lợi giúp người nghèo.', 14),
  ('infrastructure', '/ˈɪnfrəstrʌktʃə/', 'cơ sở hạ tầng (n)', 'Good infrastructure attracts investors.', 'Hạ tầng tốt thu hút nhà đầu tư.', 15),
  ('economy', '/ɪˈkɒnəmi/', 'nền kinh tế (n)', 'The economy grew by 6%.', 'Nền kinh tế tăng trưởng 6%.', 16),
  ('economic growth', '/ˌiːkəˈnɒmɪk ɡrəʊθ/', 'tăng trưởng kinh tế (n)', 'Economic growth creates jobs.', 'Tăng trưởng kinh tế tạo việc làm.', 17),
  ('unemployment', '/ˌʌnɪmˈplɔɪmənt/', 'thất nghiệp (n)', 'Youth unemployment is high.', 'Thất nghiệp ở giới trẻ cao.', 18),
  ('inflation', '/ɪnˈfleɪʃn/', 'lạm phát (n)', 'Inflation reduces purchasing power.', 'Lạm phát làm giảm sức mua.', 19),
  ('poverty', '/ˈpɒvəti/', 'nghèo đói (n)', 'Millions still live in poverty.', 'Hàng triệu người vẫn sống trong nghèo đói.', 20),
  ('inequality', '/ˌɪnɪˈkwɒləti/', 'bất bình đẳng (n)', 'Income inequality is widening.', 'Bất bình đẳng thu nhập đang nới rộng.', 21),
  ('wealth gap', '/welθ ɡæp/', 'khoảng cách giàu nghèo (n)', 'The wealth gap has grown.', 'Khoảng cách giàu nghèo đã tăng.', 22),
  ('standard of living', '/ˈstændəd əv ˈlɪvɪŋ/', 'mức sống (n)', 'The standard of living has improved.', 'Mức sống đã cải thiện.', 23),
  ('quality of life', '/ˈkwɒləti əv laɪf/', 'chất lượng cuộc sống (n)', 'Parks improve quality of life.', 'Công viên cải thiện chất lượng cuộc sống.', 24),
  ('globalisation', '/ˌɡləʊbəlaɪˈzeɪʃn/', 'toàn cầu hoá (n)', 'Globalisation connects markets.', 'Toàn cầu hoá kết nối các thị trường.', 25),
  ('urbanisation', '/ˌɜːbənaɪˈzeɪʃn/', 'đô thị hoá (n)', 'Rapid urbanisation strains cities.', 'Đô thị hoá nhanh gây áp lực lên thành phố.', 26),
  ('migration', '/maɪˈɡreɪʃn/', 'di cư (n)', 'Migration to cities continues.', 'Di cư vào thành phố vẫn tiếp diễn.', 27),
  ('population', '/ˌpɒpjuˈleɪʃn/', 'dân số (n)', 'The population is ageing.', 'Dân số đang già đi.', 28),
  ('ageing population', '/ˈeɪdʒɪŋ ˌpɒpjuˈleɪʃn/', 'dân số già (n)', 'An ageing population raises health costs.', 'Dân số già làm tăng chi phí y tế.', 29),
  ('overpopulation', '/ˌəʊvəˌpɒpjuˈleɪʃn/', 'quá tải dân số (n)', 'Overpopulation strains resources.', 'Quá tải dân số gây áp lực lên tài nguyên.', 30),
  ('birth rate', '/bɜːθ reɪt/', 'tỉ lệ sinh (n)', 'The birth rate is falling.', 'Tỉ lệ sinh đang giảm.', 31),
  ('life expectancy', '/laɪf ɪkˈspektənsi/', 'tuổi thọ trung bình (n)', 'Life expectancy has risen to 80.', 'Tuổi thọ trung bình tăng lên 80.', 32),
  ('education', '/ˌedʒuˈkeɪʃn/', 'giáo dục (n)', 'Education should be free for all.', 'Giáo dục nên miễn phí cho mọi người.', 33),
  ('curriculum', '/kəˈrɪkjələm/', 'chương trình học (n)', 'The curriculum includes coding.', 'Chương trình học bao gồm lập trình.', 34),
  ('literacy', '/ˈlɪtərəsi/', 'biết chữ, năng lực đọc viết (n)', 'Literacy rates have improved.', 'Tỉ lệ biết chữ đã cải thiện.', 35),
  ('tuition fees', '/tjuˈɪʃn fiːz/', 'học phí (n)', 'Tuition fees have doubled.', 'Học phí đã tăng gấp đôi.', 36),
  ('scholarship', '/ˈskɒləʃɪp/', 'học bổng (n)', 'She won a scholarship abroad.', 'Cô ấy giành học bổng du học.', 37),
  ('vocational training', '/vəʊˈkeɪʃənl ˈtreɪnɪŋ/', 'đào tạo nghề (n)', 'Vocational training suits many students.', 'Đào tạo nghề phù hợp với nhiều học sinh.', 38),
  ('lifelong learning', '/ˈlaɪflɒŋ ˈlɜːnɪŋ/', 'học tập suốt đời (n)', 'Lifelong learning keeps skills current.', 'Học tập suốt đời giữ kỹ năng luôn cập nhật.', 39),
  ('environment', '/ɪnˈvaɪrənmənt/', 'môi trường (n)', 'We must protect the environment.', 'Chúng ta phải bảo vệ môi trường.', 40),
  ('climate change', '/ˈklaɪmət tʃeɪndʒ/', 'biến đổi khí hậu (n)', 'Climate change threatens coastal cities.', 'Biến đổi khí hậu đe doạ các thành phố ven biển.', 41),
  ('global warming', '/ˈɡləʊbl ˈwɔːmɪŋ/', 'nóng lên toàn cầu (n)', 'Global warming melts the ice caps.', 'Nóng lên toàn cầu làm tan băng.', 42),
  ('pollution', '/pəˈluːʃn/', 'ô nhiễm (n)', 'Air pollution harms health.', 'Ô nhiễm không khí gây hại sức khoẻ.', 43),
  ('emissions', '/ɪˈmɪʃnz/', 'khí thải (n)', 'Carbon emissions must fall.', 'Khí thải carbon phải giảm.', 44),
  ('renewable energy', '/rɪˈnjuːəbl ˈenədʒi/', 'năng lượng tái tạo (n)', 'Renewable energy is getting cheaper.', 'Năng lượng tái tạo ngày càng rẻ.', 45),
  ('fossil fuels', '/ˈfɒsl fjuːəlz/', 'nhiên liệu hoá thạch (n)', 'We rely too much on fossil fuels.', 'Chúng ta phụ thuộc quá nhiều vào nhiên liệu hoá thạch.', 46),
  ('sustainable', '/səˈsteɪnəbl/', 'bền vững (adj)', 'Sustainable farming protects soil.', 'Canh tác bền vững bảo vệ đất.', 47),
  ('sustainability', '/səˌsteɪnəˈbɪləti/', 'tính bền vững (n)', 'Sustainability is a priority.', 'Tính bền vững là ưu tiên.', 48),
  ('conservation', '/ˌkɒnsəˈveɪʃn/', 'bảo tồn (n)', 'Wildlife conservation needs funding.', 'Bảo tồn động vật hoang dã cần kinh phí.', 49),
  ('deforestation', '/ˌdiːˌfɒrɪˈsteɪʃn/', 'phá rừng (n)', 'Deforestation destroys habitats.', 'Phá rừng huỷ hoại môi trường sống.', 50),
  ('biodiversity', '/ˌbaɪəʊdaɪˈvɜːsəti/', 'đa dạng sinh học (n)', 'Biodiversity is declining fast.', 'Đa dạng sinh học đang suy giảm nhanh.', 51),
  ('waste', '/weɪst/', 'rác thải (n)', 'Cities produce tonnes of waste.', 'Thành phố tạo ra hàng tấn rác thải.', 52),
  ('recycle', '/ˌriːˈsaɪkl/', 'tái chế (v)', 'Only 30% of plastic is recycled.', 'Chỉ 30% nhựa được tái chế.', 53),
  ('natural resources', '/ˈnætʃrəl rɪˈzɔːsɪz/', 'tài nguyên thiên nhiên (n)', 'Natural resources are limited.', 'Tài nguyên thiên nhiên có hạn.', 54),
  ('technology', '/tekˈnɒlədʒi/', 'công nghệ (n)', 'Technology changes how we work.', 'Công nghệ thay đổi cách ta làm việc.', 55),
  ('innovation', '/ˌɪnəˈveɪʃn/', 'đổi mới sáng tạo (n)', 'Innovation drives the economy.', 'Đổi mới sáng tạo thúc đẩy kinh tế.', 56),
  ('automation', '/ˌɔːtəˈmeɪʃn/', 'tự động hoá (n)', 'Automation may replace some jobs.', 'Tự động hoá có thể thay thế một số việc làm.', 57),
  ('artificial intelligence', '/ˌɑːtɪfɪʃl ɪnˈtelɪdʒəns/', 'trí tuệ nhân tạo (n)', 'Artificial intelligence raises ethical questions.', 'Trí tuệ nhân tạo đặt ra câu hỏi đạo đức.', 58),
  ('digital divide', '/ˈdɪdʒɪtl dɪˈvaɪd/', 'khoảng cách số (n)', 'The digital divide affects rural areas.', 'Khoảng cách số ảnh hưởng vùng nông thôn.', 59),
  ('social media', '/ˈsəʊʃl ˈmiːdiə/', 'mạng xã hội (n)', 'Social media shapes public opinion.', 'Mạng xã hội định hình dư luận.', 60),
  ('privacy', '/ˈprɪvəsi/', 'quyền riêng tư (n)', 'Data collection threatens privacy.', 'Thu thập dữ liệu đe doạ quyền riêng tư.', 61),
  ('cybersecurity', '/ˌsaɪbəsɪˈkjʊərəti/', 'an ninh mạng (n)', 'Cybersecurity is a growing concern.', 'An ninh mạng là mối lo ngày càng lớn.', 62),
  ('public health', '/ˈpʌblɪk helθ/', 'y tế công cộng (n)', 'Vaccination is a public health success.', 'Tiêm chủng là thành công của y tế công cộng.', 63),
  ('healthcare', '/ˈhelθkeə/', 'chăm sóc sức khoẻ (n)', 'Healthcare should be affordable.', 'Chăm sóc sức khoẻ nên vừa túi tiền.', 64),
  ('obesity', '/əʊˈbiːsəti/', 'béo phì (n)', 'Childhood obesity is rising.', 'Béo phì ở trẻ em đang tăng.', 65),
  ('epidemic', '/ˌepɪˈdemɪk/', 'dịch bệnh (n)', 'The epidemic spread quickly.', 'Dịch bệnh lan nhanh.', 66),
  ('mental health', '/ˈmentl helθ/', 'sức khoẻ tinh thần (n)', 'Mental health services are underfunded.', 'Dịch vụ sức khoẻ tinh thần thiếu kinh phí.', 67),
  ('prevention', '/prɪˈvenʃn/', 'phòng ngừa (n)', 'Prevention is cheaper than cure.', 'Phòng ngừa rẻ hơn chữa trị.', 68),
  ('crime', '/kraɪm/', 'tội phạm (n)', 'Crime rates fell last year.', 'Tỉ lệ tội phạm giảm năm ngoái.', 69),
  ('punishment', '/ˈpʌnɪʃmənt/', 'hình phạt (n)', 'Harsh punishment does not always deter crime.', 'Hình phạt nặng không phải lúc nào cũng ngăn tội phạm.', 70),
  ('justice', '/ˈdʒʌstɪs/', 'công lý (n)', 'Everyone deserves equal justice.', 'Ai cũng xứng đáng được công lý bình đẳng.', 71),
  ('human rights', '/ˈhjuːmən raɪts/', 'quyền con người (n)', 'Human rights must be protected.', 'Quyền con người phải được bảo vệ.', 72),
  ('gender equality', '/ˈdʒendə ɪˈkwɒləti/', 'bình đẳng giới (n)', 'Gender equality benefits everyone.', 'Bình đẳng giới có lợi cho mọi người.', 73),
  ('discrimination', '/dɪˌskrɪmɪˈneɪʃn/', 'phân biệt đối xử (n)', 'Laws prohibit discrimination at work.', 'Luật cấm phân biệt đối xử nơi làm việc.', 74),
  ('culture', '/ˈkʌltʃə/', 'văn hoá (n)', 'Culture shapes our values.', 'Văn hoá định hình giá trị của chúng ta.', 75),
  ('tradition', '/trəˈdɪʃn/', 'truyền thống (n)', 'Traditions are fading in cities.', 'Truyền thống đang phai nhạt ở thành phố.', 76),
  ('heritage', '/ˈherɪtɪdʒ/', 'di sản (n)', 'We should preserve cultural heritage.', 'Chúng ta nên gìn giữ di sản văn hoá.', 77),
  ('generation', '/ˌdʒenəˈreɪʃn/', 'thế hệ (n)', 'Each generation faces new challenges.', 'Mỗi thế hệ đối mặt thách thức mới.', 78),
  ('consumerism', '/kənˈsjuːmərɪzəm/', 'chủ nghĩa tiêu dùng (n)', 'Consumerism fuels waste.', 'Chủ nghĩa tiêu dùng thúc đẩy lãng phí.', 79),
  ('advertising', '/ˈædvətaɪzɪŋ/', 'quảng cáo (n)', 'Advertising targets children.', 'Quảng cáo nhắm vào trẻ em.', 80),
  ('tourism', '/ˈtʊərɪzəm/', 'du lịch (ngành) (n)', 'Tourism boosts local incomes.', 'Du lịch tăng thu nhập địa phương.', 81),
  ('transport', '/ˈtrænspɔːt/', 'giao thông vận tải (n)', 'Public transport reduces traffic.', 'Giao thông công cộng giảm kẹt xe.', 82),
  ('congestion', '/kənˈdʒestʃən/', 'tắc nghẽn (n)', 'Congestion costs the city billions.', 'Tắc nghẽn khiến thành phố tốn hàng tỉ.', 83),
  ('housing', '/ˈhaʊzɪŋ/', 'nhà ở (n)', 'Affordable housing is scarce.', 'Nhà ở giá phải chăng rất khan hiếm.', 84),
  ('employment', '/ɪmˈplɔɪmənt/', 'việc làm (n)', 'Employment rose in the service sector.', 'Việc làm tăng ở khu vực dịch vụ.', 85),
  ('workforce', '/ˈwɜːkfɔːs/', 'lực lượng lao động (n)', 'The workforce is becoming more diverse.', 'Lực lượng lao động ngày càng đa dạng.', 86),
  ('productivity', '/ˌprɒdʌkˈtɪvəti/', 'năng suất (n)', 'Remote work can raise productivity.', 'Làm việc từ xa có thể tăng năng suất.', 87),
  ('work-life balance', '/ˌwɜːk laɪf ˈbæləns/', 'cân bằng công việc – cuộc sống (n)', 'Flexible hours improve work-life balance.', 'Giờ linh hoạt cải thiện cân bằng công việc – cuộc sống.', 88),
  ('investment', '/ɪnˈvestmənt/', 'đầu tư (n)', 'Investment in education pays off.', 'Đầu tư vào giáo dục sinh lợi.', 89),
  ('developing country', '/dɪˈveləpɪŋ ˈkʌntri/', 'nước đang phát triển (n)', 'Developing countries need fair trade.', 'Các nước đang phát triển cần thương mại công bằng.', 90),
  ('developed country', '/dɪˈveləpt ˈkʌntri/', 'nước phát triển (n)', 'Developed countries emit more carbon per person.', 'Các nước phát triển thải nhiều carbon trên đầu người hơn.', 91),
  ('international cooperation', '/ˌɪntəˈnæʃnəl kəʊˌɒpəˈreɪʃn/', 'hợp tác quốc tế (n)', 'Climate change requires international cooperation.', 'Biến đổi khí hậu đòi hỏi hợp tác quốc tế.', 92),
  ('raise awareness', '/reɪz əˈweənəs/', 'nâng cao nhận thức', 'Campaigns raise awareness of recycling.', 'Chiến dịch nâng cao nhận thức về tái chế.', 93),
  ('impose', '/ɪmˈpəʊz/', 'áp đặt (v)', 'The city imposed a congestion charge.', 'Thành phố áp phí tắc nghẽn.', 94),
  ('ban', '/bæn/', 'cấm (v, n)', 'Some cities ban cars downtown.', 'Một số thành phố cấm ô tô ở trung tâm.', 95),
  ('invest in', '/ɪnˈvest ɪn/', 'đầu tư vào', 'Governments should invest in public transport.', 'Chính phủ nên đầu tư vào giao thông công cộng.', 96),
  ('encourage', '/ɪnˈkʌrɪdʒ/', 'khuyến khích (v)', 'Tax breaks encourage green energy.', 'Ưu đãi thuế khuyến khích năng lượng xanh.', 97),
  ('priority', '/praɪˈɒrəti/', 'ưu tiên (n)', 'Health must be a national priority.', 'Y tế phải là ưu tiên quốc gia.', 98),
  ('challenge', '/ˈtʃælɪndʒ/', 'thách thức (n)', 'Ageing is a major challenge.', 'Già hoá là một thách thức lớn.', 99),
  ('civic', '/ˈsɪvɪk/', 'thuộc về công dân (adj)', 'Voting is a civic duty.', 'Bầu cử là nghĩa vụ công dân.', 100)
) as w(term, phonetic, meaning_vi, example_en, example_vi, position) on true
where d.slug = 'hoc-thuat-xa-hoi'
on conflict (deck_id, term) do nothing;
